### ISSUE TITLE
使用magicType切换折线图，原有样式会变化

### ISSUE THREAD

**Issue by qianzhangsheng** [apache/echarts#10014]
### Version
4.1.0-release

### Steps to reproduce
https://jsfiddle.net/qianzhangsheng/r9wvtn1s/4/

点击右上角的切换折线图以后，当前折线图样式会变化，坐标到0开始了

option = {
    xAxis: {
        type: 'category',
        data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
    },
    yAxis: {
        type: 'value'
    },
    series: [{
        data: [820, 932, 901, 934, 1290, 1330, 1320],
        type: 'line'
    }],
    toolbox: {
        show: true,
        feature: {
            magicType: {type: ['line', 'bar']},
        }
    },
};

### What is expected?
加载出来折线图点击magicType里的折线图样式不发生变化

### What is actually happening?
变化了样式

**Comment by yufeng04** [comment]
The reason of this issue is the value of boundaryGap changed. 

In the function `proto$3.onclick`
![image](https://user-images.githubusercontent.com/22974511/56126991-caa0e100-5fae-11e9-8fde-0a6346a96b3a.png)

The default value of `boundaryGap`  is `true` , but the `boundaryGap` will be set to `false` when the value of type is not bar, .
