### ISSUE TITLE
Sunburst miniAngle didn't work at first render

### ISSUE THREAD

**Issue by susiwen8** [apache/echarts#10414]
### Version
4.2.1-rc.3

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=x1oZUPM5kO&v=1](https://gallery.echartsjs.com/editor.html?c=x1oZUPM5kO&v=1)

### Steps to reproduce
1. Open the link, then you will see children2 and children3 label is on chil area
2. Click children2 or children3 label
3. Click the inner ring
4. then click the third ring
5. We see children2 and children3 appear.

### What is expected?
Children2 and Children3 show up at first render

### What is actually happening?
Children2 and Children3 didn't show up at first render

---
This bug is relate to https://github.com/apache/incubator-echarts/issues/10413

**Comment by susiwen8** [comment]
Also, series-sunburst.miniAngle is working, but did't mention in the document
https://www.echartsjs.com/option.html#series-sunburst
Should we add it on?

**Comment by Ovilia** [comment]
Yes, this is a bug and we need `minAngle` in doc.

**Comment by Ovilia** [comment]
Sunburst `minAngle` is not available currently. If we wish to support it, there's a big question here. Say that we have a Sunburst chart with two levels, whose value is `[{ value: 100, name: 'A' }, { value: 2, name: 'B', children: [{ value: 1, name: 'B1' }, {value: 1, name: 'B2'}]}]` and the `minAngle` is set to be `45`.
In order to apple `minAngle` to both levels, `B1` and `B2` has to be 45 degrees each and thus make `B` 90 degrees. This problem goes on when there are more levels and cause a big problem of data understanding with it.
Before we have a good idea to solve this problem, `minAngle` will remain not usable.

**Comment by susiwen8** [comment]
@Ovilia Yes, That's what I encountered when I tried to solve it.
