### ISSUE TITLE
When adding units to the x Axis labels, the split area in the heatmap chart does not function correctly

### ISSUE THREAD

**Issue by lauraxm** [apache/echarts#10769]
### Version
4.2.1

### Steps to reproduce
**Context:** I want to use time intervals in my x axis. 
Passing an array of xAxisLabels to the `xAxis` object, with a `p` for denoting `pm` like so: 

`['1p', '2p', '3p']`

### What is expected?
If I pass an array of just numbers:

`['1','2','3']`

It looks fine:

![image](https://user-images.githubusercontent.com/4047521/60294459-64f69c80-98ef-11e9-8def-0f30aa0e8210.png)

### What is actually happening?
The split area styles do not seem to function correctly:

![image](https://user-images.githubusercontent.com/4047521/60294450-60ca7f00-98ef-11e9-9156-1dd6c68bce21.png)

---
I am not sure if this is a bug or the intended behavior. @Ovilia

**Comment by Ovilia** [comment]
Please provide a demo for your chart: https://jsfiddle.net/ovilia/n6xc4df3/

**Comment by laurapizza** [comment]
@Ovilia I've updated the fiddle. 

After trying to reproduce it there, I realized that it only seems to happens when you add the `type: time` to `xAxis`. The heatmap boxes then seem to overlap some of the axis labels as well. So I'm not sure right now if it's:
a) a bug, since `type: time` should technically work
b) a problem with the way I am passing the data in to the x axis. If so - please let me know and I can make a clarifying PR for the documentation :)
