### ISSUE TITLE
折线图在图表容器宽高更高情况下，图表被严重压缩，无法正确显示

### ISSUE THREAD

**Issue by CeleKing** [apache/echarts#11267]
### Version
4.3.0

### Reproduction link
[https://jsfiddle.net/ne62xqrc/1/](https://jsfiddle.net/ne62xqrc/1/)

### Steps to reproduce
a容器的高度比b容器的高度高，但是显示的内容没有b容器多

### What is expected?
图表容器越高显示的内容多

### What is actually happening?
图表容器高，图表却被压缩

**Comment by Ovilia** [comment]
An ad-hoc could be adding `grid: { top: 0 }`. But I'm not sure why this bug happens.

**Comment by alex2wong** [comment]
Hi team, I may find some clue. As you can see, the grid rect has a big top (about 60 px) relative to the canvas.

![image](https://user-images.githubusercontent.com/10528482/65290378-8e873300-db81-11e9-92c6-4e588cfd9390.png)

After some debug, I found a weird thing: the **gridModel**.getBoxLayoutParams() always get option.top with big value, which means the grid rect has unnecessray large margin-top, then it cause following height set as minus:
```
 function getLayoutRect(
    positionInfo, containerRect, margin
) {
    margin = normalizeCssArray$1(margin || 0);

    var containerWidth = containerRect.width;
    var containerHeight = containerRect.height;

    var left = parsePercent$1(positionInfo.left, containerWidth);
    var top = parsePercent$1(positionInfo.top, containerHeight);
    var right = parsePercent$1(positionInfo.right, containerWidth);
    var bottom = parsePercent$1(positionInfo.bottom, containerHeight);
    var width = parsePercent$1(positionInfo.width, containerWidth);
    var height = parsePercent$1(positionInfo.height, containerHeight);

    var verticalMargin = margin[2] + margin[0];
    var horizontalMargin = margin[1] + margin[3];
    var aspect = positionInfo.aspect;

    // If width is not specified, calculate width from left and right
    if (isNaN(width)) {
        width = containerWidth - right - horizontalMargin - left;
    }
    if (isNaN(height)) {
        //// containerHeight - 60 - 0 - 60 often result in minus number.
        height = containerHeight - bottom - verticalMargin - top;
    }
// ...

```

![Echart-issue1](https://user-images.githubusercontent.com/10528482/65290949-e9218e80-db83-11e9-980c-e04e577b15e4.jpg)

Finally, you would see the grid rect height result in 10 px, that's why our chart looks extremely short.

So, my question is where does the gridModel.option.top comes from ?? em, it may take top/bottom xAxis into consideration.. need further investigation. Do you guys have any idea?

btw, the official demo does not have this issue, it has responsive canvas container depend on the window size.

**Comment by Ovilia** [comment]
@alex2wong That's an excellent job!
@100pah Please help look at the comment to see if @alex2wong could make a pull request here.

**Comment by pissang** [comment]
Thanks, @alex2wong . The grid top is a fixed height for the space of legend, title, toolbox or other components. Currently, this is not automatically layout. 

About the issue @CeleKing asked. The container height is too small and it caused the grid height to a negative value. 

Perhaps we can limit the value to zero to avoid confusing. Of course, the best solution is adding automatically layout to utilize the space as much as possible.

**Comment by alex2wong** [comment]
@pissang , thanks for your helpfull suggestion. It is really not easy to autolayout all possible elements, and make them not overlap.. I compare same container height/width in chart.js which implement the autolayout among title/legend and grid itself, though in extremely small container height it still result in short grid.

As for tech detail, I can only come up with a simple idea right now, in **getLayoutRect** function, we get legend/title/toolbox's position and visibility then adjust the grid top/bottom. For instance, cut down grid top to zero or half of original value. But we can NOT fit all cases, since there are so many option can be configured..

maybe some thing like this: 
```
// layout ajustment NOT work when top/bottom typed number.
            switch (legend && (legend.top || legend.bottom)
                || title && (title.top || title.bottom)
                || toolbox && (toolbox.top || toolbox.bottom)) {
                case 'top':
                    bottom = bottom / 2;
                    break;
                case 'bottom':
                    // Elements only at bottom, adjust grid top.
                    top = top / 2;
                    break;
                default:
                    top = top / 2;
                    bottom = bottom / 2;
            }
```

Or as you said, just set the default grid Top as 0, or 10%. then reset it a bigger value if found Elements at bottom/top.

**Comment by pissang** [comment]
Hi @alex2wong.
The components are designed to be decoupled and don't know the exists of each other. We are planning to add a separate layout module to adjust all the components' position and size to avoid the overlap. It needs the default value of `left/top/right/bottom` to be changed and may cause breaking change. So we put it in the 5.0 roadmap.

Currently, the easiest way is still letting developers configure `grid.top` to 0 if there is only one grid component on the chart.

**Comment by alex2wong** [comment]
that's true, in each dummy module, they'd better know other component's state. I agree with you that we need to adjust layout in more global stage.. 

This case is not that urgent I believe, and there's work around as you said.

Thanks for your fast reply.😃
