### ISSUE TITLE
Fix arrow disappear in the SVG renderer of 4.4.0  4.4.0 BUG 在SVG模式下lines箭头和箭头文本消失 

### ISSUE THREAD

**Issue by eniaclyl** [apache/echarts#11593]
### Version
4.4.0

### Reproduction link
[https://gallery.echartsjs.com/editor.html?c=xW-C1oA98&v=2](https://gallery.echartsjs.com/editor.html?c=xW-C1oA98&v=2)

### Steps to reproduce
1、将mycharts设置为svg模式
2、箭头和文本消失

### What is expected?
和canvas模式一样，能正确显示箭头和文本

### What is actually happening?
svg模式和canvas模式行为不一样

---
哪个版本可以修复这个bug

**Comment by eniaclyl** [comment]
@Ovilia @pissang help me！！！Thank you！！！

**Comment by Ovilia** [comment]
This seems to be an SVG bug. Scheduled in 4.7.0.

**Comment by eniaclyl** [comment]
@Ovilia When is it released? 4.7.0

**Comment by Ovilia** [comment]
@eniaclyl About 1-2 months.

**Comment by eniaclyl** [comment]
@Ovilia 3Q

**Comment by Ovilia** [comment]
This problem is caused by transformed elements with clipPath. See [demo here](https://codepen.io/Ovilia/pen/BayJRPg).
The clipPath position in under global coordinate, but the element is transformed so it doesn't behave as expected.
In order to fix this, we need to create a group element for each transformed element with clipPath and set the clipPath on the group while the element itself is transformed.
We cannot find an easy way to fix this by now, so it's marked to be fixed later.

这个问题是由于同时使用 transform 和 clipPath 的元素引起的。
我们期望 clipPath 的位置是相对于全局的，但 SVG 中如果将 clipPath 作用于一个 transform 过的元素，它实际是相对于元素的。因此，最后计算出的位置不符合预期。
修复的方法可以是为每个带 transform 和 clipPath 的元素新建一个 group 元素，将 transform 作用于图形本身，将 clipPath 设置在 group 元素上。
修复成本较高，考虑在 zrender 重构之后再修复这个问题，所以先标记为 TBD 了。

**Comment by eniaclyl** [comment]
@Ovilia 请问有具体的修复时间吗？或者大概的修复时间也行？或者告诉我zrender啥时候重构也行，至少能给我个预期时间，不让我无限等，谢谢

**Comment by Ovilia** [comment]
三个月内会完成 zrender 的底层重构，到时候会有一个结论怎么修能不能修。谢谢。

**Comment by eniaclyl** [comment]
@Ovilia 好的，那我就一直等着了，至于你说的能不能修我不太懂，要是不能修那这个bug我得怎么解决呀，我还是挺看好这个库的。希望能解决这些错误，谢谢
