### ISSUE TITLE
[DISCUSS] How to choose color of legend when the color in series is a callback function

### ISSUE THREAD

**Issue by pissang** [apache/echarts#11736]
Normally, the `legend` component will pick the color from each series.
But color may varies if it's a callback function. 

For example:

```js
option = {
  legend: {},
  series: [{
      type: 'scatter',
      itemStyle: {
        color: function () {
            // Return customized color
         }
       }
   }]
}
```

It's hard for `legend` component to get the right color in this scenario. In the previous stragegy. The `legend` component will simply pick the first color returned from callback in each series. It covers some of the scenario. But may have problem if the first color is not we wanted.

Since 4.4.0. We changed it by using the color from default color palatte. The problem of this strategy is this color is not relevant to the colors on the chart.

So here is some possible strategies we can choose from:

1. Pick the median color from all colors returned by the callback function. It's a improved method of the original 'use first returned color' method.

2. Pick color from default color palatte.

3. Display multiple colors in a single legend item. It may be displayed as a grid or a gradient.

All these three strategies may have it's pros and cons. I think we need more discussions and scenarios to descide which strategy we should use to cover as more scenarios as possible.

**Comment by 100pah** [comment]
A related test case: `test/line-style.html`.


## For line chart

In this case:
```js
itemStyle: {
    color: (param) => { /* return a color */ }
},
lineStyle: {
    color: 'blue'
}
```
The legend should better show 'blue', but neither palette color (since 4.5.0) nor the first symbol color (before 4.5.0).

## For scatter chart

```js
itemStyle: {
    color: color: (param) => { /* return a color */ }
}
```

I modified it to use palette color (since 4.5.0) when callback exists. 
That modification cause a break change from selecting the first symbol color.
Use palette color is not a good solution, 
so **the break change is not good and should not have happened**.

About the better strategy, as @pissang mentioned, 
I prefer:
> Pick the median color from all colors returned by the callback function. It's a improved method of the original 'use first returned color' method.

Or probably it's better to chose the most returned color, I think.

## Do we need to enable users to specify color to `legend component` directly?
In case that the auto-calculated color is not what users expected.

**Comment by atealxt** [comment]
Upvoting for this thread, expect a config like `legend.data.itemStyle.color` or `legend.data.icon.color`

**Comment by Carlo0099** [comment]
I recently had a problem with the same requirement. I used the var function of css in series. When the global property css is changed, the echarts bar can change color accordingly, but the legend component and font color cannot use var function and cannot inherit the color of bar

**Comment by Rotario** [comment]
Hi - I'm hitting this problem too.
the Legend option doesn't seem to take a function

**Comment by Carlo0099** [comment]
> 嗨 - 我也遇到了这个问题。 该`legend.itemStyle.color`选项似乎没有功能
In fact, legend does not have a callback function, and I have to pass new rgba properties one at a time as required

**Comment by VVonderfu11** [comment]
it is still not working
