### ISSUE TITLE
heatmap item wrongly rendered to strip when axis type is 'time' 

### ISSUE THREAD

**Issue by LongLiveSocialism** [apache/echarts#12450]
### Version
4.6.0

### Steps to reproduce
1. open heatmap official examples : https://echarts.apache.org/examples/zh/editor.html?c=heatmap-large
2. set xAxis type to time
3. set corresponding data to timestamp such as follows:
origin:     data.push([i, j, noise.perlin2(i / 40, j / 20) + 0.5]);
timestamp version:    data.push([new Date(i*1000), j, noise.perlin2(i / 40, j / 20) + 0.5]);

Then heatmap is wrongly rendered to strip when timestamps are not continuous timestamp numbers.

### What is expected?
The heatmap item should be correctly rendered to proper rect to fill the picture

### What is actually happening?
Then heatmap item is wrongly rendered to strip when timestamps are not continuous timestamp numbers.

---
I found it when I need to draw a heatmap with one time axis

**Comment by quillblue** [comment]
@LongLiveSocialism 
It seems that currently heatmap will not support contiounus axis such as 'time', since intermediate value could not be determined without additional information. (for example, with value in 8:00 and in 9:00 provided we can not determine value in 8:30).
If using value in one moment could represent value in a period of time in your case, you can set axis type as 'category' and use axis label to represent time like example in https://www.echartsjs.com/examples/en/editor.html?c=heatmap-cartesian

**Comment by lafrech** [comment]
> If using value in one moment could represent value in a period of time in your case, you can set axis type as 'category' and use axis label to represent time like example in https://www.echartsjs.com/examples/en/editor.html?c=heatmap-cartesian

Obviously, the shortcoming of this workaround is that you don't get the nice features of time axis, like the clever subsampling of the axis. For instance, when displaying days for 1 whole year, a time axis would display month names while a categorical axis will display seemingly random dates picked along the axis.
