### ISSUE TITLE
Show the chart title only in saved image (jpeg or png)

### ISSUE THREAD

**Issue by leorigon** [apache/echarts#12755]
I don't found an approach to show the title only in artifact created by saveAsImage toolbox. 

I have been search on docs if there is an event/action to see the click on toolbar -> saveAsImage, but I don't had success.

So, it's possible? 

We use the latest echarts version.

**Comment by Ovilia** [comment]
You should create a custom `feature` (doc: [feature](https://echarts.apache.org/en/option.html#toolbox.feature)) rather than get the event, because even if you can get the event, the image has already been saved and there is no use to update title.
So you should use a custom feature, and in the `onclick` callback, call `chart.setOption` to add title and then [`chart.getDataURL()`](https://echarts.apache.org/en/api.html#echartsInstance.getDataURL) to get the image in base64 format.
