### ISSUE TITLE
Add option to automatically assign label position for sankey node labels

### ISSUE THREAD

**Issue by dominic-simplan** [apache/echarts#12890]
### What problem does this feature solve?
There are many options for configuration a sankey label position: https://echarts.apache.org/en/option.html#series-sankey.label.position.
However, using the left or the right option, the labels might not be visible if the nodes are at the corner of the diagram.
![grafik](https://user-images.githubusercontent.com/22240239/86284952-135cae00-bbe4-11ea-8726-bf7bc52a9f03.png)

An additional option which automatically finds the best position for the label (e.g. right, if the node is on the left half of the diagram, and left, if the node is on the right half of the diagram) would be useful.
![grafik](https://user-images.githubusercontent.com/22240239/86284974-1b1c5280-bbe4-11ea-937b-45871aef84e4.png)

### What does the proposed API look like?
label.position = "auto"

**Comment by albcunha** [comment]
In case someone like me, with the same problem, reaches this suggestion, there is a manual workaround.

You can set label position dynamically on the node. So, on the nodes on the right, instead of:
```
{
name:` "node on the right side"
}
```
you do this:
```
{
name:` "node on the right side",
label: {position: "left"}
}

```

Also, on options -> series, you can set padding if you want. You cant set left:0, right:0, to use the full chart space. Example:
```
series: [
      {
        type: "sankey",
        right: 0,
        left: 0,
        data: nodes,
        links: links,
        lineStyle: {
          color: "source",
          curveness: 0.5,
        },
      },
    ],
```
