### ISSUE TITLE
echarts : failed to load resource error

### ISSUE THREAD

**Issue by Prasanna-ai** [apache/echarts#12990]
![echartsIssue](https://user-images.githubusercontent.com/68467030/87852268-24b0f480-c91e-11ea-8a30-0b592387db87.PNG)
### Version
3.8.4

### Steps to reproduce
I developed all my dashboard graphs using echarts.The graphs are not loading it is showing empty. In the browser console, it is showing the following error
failed to load resource error: the server responded with a status of 404 (Not found) echarts.apahe.org/dist/echarts.min.js

### What is expected?
All graphs should be loaded

### What is actually happening?
Graphs(line,bar,donut...etc) are not showing in the dashboard

**Comment by susiwen8** [comment]
Please upgrade to latest version 4.8 and try it again.

**Comment by plainheart** [comment]
Sorry for that. I'm a little confused about the way you import ECharts script. It seems to be strange that your project is referring to the script from ECharts official website. Could you be more specific on this?
Anyway, if possible and allowed, it's still suggested to update the version of ECharts to the latest and then have a try again, as @susiwen8 says.

**Comment by Prasanna-ai** [comment]
Hi Apache/Incubator-Echarts,

Yes, I am calling the script from the official website like this
<script src="http://echarts.baidu.com/dist/echarts.min.js"></script>
What is the alternative to use this script?
@susiwen8 <https://github.com/susiwen8> : I actually don't know the version
which I am using.I checked for that but the version is not showing.I am
directly calling the online Js link.

Our Dashboard is showing empty. Some times showing graphs and some times
not showing up. I am facing this issue from so many days.
After doing lot of R & D I found a way to approach you. Charts loading also
taking a lot of time. Please help me on these two issues.

Thanks and Regards
Prasanna.

**Comment by plainheart** [comment]
The online script you are calling now has changed to `https://echarts.apache.org/en/dist/echarts.min.js`.
It is because the official website has moved to `echarts.apache.org` from `echarts.baidu.com`.
If you want to know the version of ECharts, you could open the dev panel and input `echarts.version` in the console to see it.
BTW, it's better to use a CDN like [jsDelivr](https://www.jsdelivr.com/package/npm/echarts?path=dist) for the online script.

**Comment by Prasanna-ai** [comment]
Hi Apache/Incubator-Echarts,

As per your suggestion,now I am not using
https://echarts.apache.org/en/dist/echarts.min.js.

I am using this online script file <script src="
https://cdn.jsdelivr.net/npm/echarts@4.8.0/dist/echarts.min.js"></script>

Now my browser console is not showing error and graphs are loading.But the
display of the graphs taking lot of time. Please help me on this.

Thanks & Regards
Prasanna.

**Comment by quillblue** [comment]
@Prasanna-ai Lots of reason may cause slow performance and it's hard to tell at very first glance. You may:

- Try to test your connection speed to jsdelivr.net since you are refering to existing builded file in CDN. If allowed, you can put this file on your local or referring to any known CDN which is faster on visiting from your country/region.
- Paste some of code here in this issue or to build a online demo to reproduce your issue at [online editor](http://gallery.echartsjs.com/editor.html) for community member better understanding your situation
