### ISSUE TITLE
Can not draw a rectangle on canvas on top of charts by drag&drop

### ISSUE THREAD

**Issue by ghost** [apache/echarts#13037]
### Version
4.6.0

### Steps to reproduce
Try to (drag and drop) draw a rectangle on canvas, which comes with echarts.

### What is expected?
A rectangle to be shown while trying to draw over canvas

### What is actually happening?
The rectangle is not shown as the charts visualization has priority over what you draw on canvas.

**Comment by Ovilia** [comment]
Please create a demo using https://codepen.io/Ovilia/pen/dyYWXWM

**Comment by evavranici** [comment]
> 
> 
> Please create a demo using https://codepen.io/Ovilia/pen/dyYWXWM

Hi Ovilia,

Thank you for your response. I tried to reproduce the code using your template, find it here : https://codepen.io/evavranici/pen/NWNKbxr but the problem is not appearing cause I can draw on top of the chart just like I want. Maybe some other configurations in my echarts code is preventing me from properly drawing in the embedded canvas. Also, a difference from yours to my code, in my case I 'import' echarts by including its module with the same name in my template's div not by initiating it with echarts.init (if that makes any difference) ... Can you help me if you may have any idea what can influence this behavior or if it has happened in the past?

Thank you,
Eva

**Comment by evavranici** [comment]
Update: I couldn't draw on canvas (as title of the issue) but since my purpose of doing so was to draw a rectangle/area in order to zoom in into the chat, I managed to so my using the 'brush' in the options.

**Comment by tchaton** [comment]
@ghost Any updates ?
