### ISSUE TITLE
setOption({},true)重绘失效

### ISSUE THREAD

**Issue by Homebrew1** [apache/echarts#13527]
### Version
4.5.0-rc.2

### Steps to reproduce
this.myCharts1 = echarts.init(this.$refs.myechart1);
this.myCharts2 = echarts.init(this.$refs.myechart2);
this.leftEchart.series.data = [];
this.leftEchart.data = [];
this.leftEchart.graphic[0].text = "总时长\r\n1";
this.myCharts1.setOption(this.leftEchart,true);
this.myCharts2.setOption(this.rightEchart,true);

### What is expected?
在对数据修改之后，使用setOption可以重绘

### What is actually happening?
没有重绘，数据在原图上没有改变

**Comment by eschao** [comment]
Yes, I have met the same problem with `stack bar`, when I reset the series data with empty, the stack bar still show the previous data on the chart instead of empty chart, from the chart animation, I think it redrew but seems used the old data not the new series. I didn't see the same problem on the `line` and `normal bar` charts.
