### ISSUE TITLE
The last label can not be displayed in time scale

### ISSUE THREAD

**Issue by 100pah** [apache/echarts#13676]
### Version
5.0.0

### Steps to reproduce
In v4.9, the last label can be displayed (if there is enough space).
At present, it can not be displayed, even set `showMaxLabel` as `true`.
Test case:
The second case in `/test/axis-lastLabel.html`.

**Comment by Ovilia** [comment]
This is a feature rather than a bug in ECharts 5. The consideration behind this is that, if the first/last label is not of the same level of the minimum time level, it should not be displayed.

![image](https://user-images.githubusercontent.com/779050/113262996-d3a62c80-9303-11eb-9dad-ff62d49e14b9.png)

For example, in the case, the last time label "8:00" may not be displayed because the minimum time level is day. If the developer think it is required to display in this case, he can set `axisLabel.showMaxLabel` to be `true`.
So this issue is closed due to not-a-bug.
