### ISSUE TITLE
Labels in time scale will overlap in some cases

### ISSUE THREAD

**Issue by 100pah** [apache/echarts#13682]
### Version
5.0.0

### Steps to reproduce
Test case:
    `/test/timeScale.html`
    `/test/tooltip-link.html`
Make the window narrow.
We should not depends on `splitNumber`. It should fit those cases automatically.

![image](https://user-images.githubusercontent.com/1956569/100093577-aef00300-2e92-11eb-86f3-3b49c828842e.png)

**Comment by majki600rr** [comment]
![image](https://user-images.githubusercontent.com/55019125/116980766-ed51df80-acc6-11eb-8311-0bba5095ff9c.png)
🙄🙄

**Comment by majki600rr** [comment]
We can not update echarts to version 5.x because of described problem above.
Please pay attention close to this matter.

![image](https://user-images.githubusercontent.com/55019125/119601909-65a15180-bdea-11eb-95e5-62afa66f9804.png)

**Comment by majki600rr** [comment]
We were waiting on version 5.1 mainly due to this problem and we are just disappointed.
We can not update echarts to version 5.x until you fix it. Please pay attention close to this matter.
![image](https://user-images.githubusercontent.com/55019125/119602542-a64d9a80-bdeb-11eb-9e04-7b34bde8ddd7.png)

**Comment by pissang** [comment]
Fixed in https://github.com/apache/echarts/pull/15712
