### ISSUE TITLE
Brushing causing repainting all with big data

### ISSUE THREAD

**Issue by helocean** [apache/echarts#13858]
### Version
4.9.0

### Reproduction link
[https://breeding.biobin.com.cn/welcome/echarts/scatter-matrix.html](https://breeding.biobin.com.cn/welcome/echarts/scatter-matrix.html)

### Steps to reproduce
使用scatter 散点图时，同时使用了legend和brush选择，为什么当界面上数据超过1W的时候，在legend和brush选的时候，整个散点图就重新刷新，在1w数据点以内的话就可以正常显示，不重新加载散点图
(Using scatter diagram, using the legend and brush to choose, why when the interface data on more than 70000 data quantity, at the time of legend and brush selected, the scatter plot is to refresh, you can within the 10000 data points, according to the normal not reload the scatter plot.)。

### What is expected?
数据量可以设定，在一定值后可以重新加载，或者不重新加载(The amount of data can be set and can be reloaded or not reloaded after a certain value)

### What is actually happening?
当数据超过1w数据就重新加载了(When the data exceeds 10000, it is reloaded)。

**Comment by Ovilia** [comment]
By default, scatter series has [progressiveThreshold](https://echarts.apache.org/next/zh/option.html#series-scatter.progressiveThreshold) as 3000, which means the data will be rendered progressively in the following frames if a series contains data more than 3000.
You can set the option to be a larger number, so that it will be rendered in a single frame, but this will take longer time for a frame.
