### ISSUE TITLE
xAxis "0" not found

### ISSUE THREAD

**Issue by cheqianxiao** [apache/echarts#14080]
### Version
5.0.1

### Reproduction link
[https://codesandbox.io/s/async-fast-n3sz9?file=/src/index.js](https://codesandbox.io/s/async-fast-n3sz9?file=/src/index.js)

### Steps to reproduce
访问reproduction link

### What is expected?
正常显示柱图

### What is actually happening?
报错： xAxis "0" not found

**Comment by susiwen8** [comment]
```js
// const echarts = require("echarts");
import * as echarts from "echarts/core";
import {
  GridComponent,
} from 'echarts/components';
import {
  BarChart,
} from 'echarts/charts';
import {
  CanvasRenderer,
} from 'echarts/renderers';
echarts.use([GridComponent, BarChart, CanvasRenderer]);
var myChart = echarts.init(document.getElementById("main"));
// 指定图表的配置项和数据
var option = {
  title: {
    text: "ECharts 入门示例"
  },
  tooltip: {},
  legend: {
    data: ["销量"]
  },
  xAxis: {
    data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
  },
  yAxis: {},
  series: [
    {
      name: "销量",
      type: "bar",
      data: [5, 20, 36, 10, 10, 20]
    }
  ]
};

myChart.setOption(option);

```

**Comment by pissang** [comment]
In addition to @susiwen8 's answer. Since 5.0.1. `grid` component should be imported explicitly to have extreme tree-shaking.

import "echarts/lib/component/grid";

You can check the import code on the new example page

![image](https://user-images.githubusercontent.com/841551/105147100-aab32f80-5b3b-11eb-8635-e96704afacdf.png)

**Comment by cheqianxiao** [comment]
ok， thanks a lot !
