### ISSUE TITLE
Custom rendering broken for large datasets

### ISSUE THREAD

**Issue by marklbarlow** [apache/echarts#14144]
### Version
5.0.1

### Reproduction link
[https://stackblitz.com/edit/angular-ivy-fkqewp?file=src/app/app.component.ts](https://stackblitz.com/edit/angular-ivy-fkqewp?file=src/app/app.component.ts)

### Steps to reproduce
https://angular-ivy-fkqewp.stackblitz.io/

### What is expected?
Graph should display accurately.

### What is actually happening?
Graph rendering is VERY slow and in some cases only the last series to be defined is actually shown.

As you move the mouse pointer over the graph, render points appear and disappear randomly.  Some of these display a valid tooltip, others display empty data (debugging some of these points to the console shows that the data value here is null).

The effect is more pronounced if the dataset is zoomed, with entire series appearing / disappearing or other strange flashing artefacts.

(note, the same data set renders fine with a scatter graph)

**Comment by tkggwatson** [comment]
I also have this issue. Is there a fix or does anyone know a workaround please?

**Comment by tkggwatson** [comment]
I have done some digging in the debugger on this today and traced it as far as this:

The issue seems to occur at the point where a large dataset with a custom renderer switches FROM progressive rendering TO non-progressive rendering.

You can increase the repro rate by setting the option 'progressiveThreshold' to a lower value, e.g. 1000, and zooming in to your graph until you cross the threshold and there are less than 1000 items being rendered. At the point where you cross the threshold, existing render elements do not get cleaned up and are left visible and in the wrong place. If you then zoom out to the point where more than 1000 are visible again, the issue will correct itself.

You can work around this issue therefore by lowering 'progressiveThreshold' to 1, so that the graph is always in progressive mode. Another workaround is to set 'progressive' to 0 or 'progressiveThreshold' to a very large number, to effectively disable progressive rendering, though in that case rendering a large dataset can be very slow. By trial and error I have found a sweet spot for my data set with 'progressiveThreshold' set to 1 and 'progressive' set to 2000.

**Comment by tkggwatson** [comment]
I can confirm both of the above workarounds fix the issue in the repro link.

**Comment by tkggwatson** [comment]
@susiwen8 Hi there. Do you have an ETA for when this one might be fixed, please?
