### ISSUE TITLE
Dashed line rendering style changed from v4 -> v5

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14302]
### Version
5.0.2

### Steps to reproduce
Add a dashed markLine to a chart.

| v4 | v5 |
|-|-|
![image](https://user-images.githubusercontent.com/470626/108556547-16311e00-72ef-11eb-9733-32807f066ce0.png) | ![image](https://user-images.githubusercontent.com/470626/108556951-b6874280-72ef-11eb-8cb9-62ed1ce25395.png)

Both images are 1:1 scale.

### What is expected?

Dashed line is comprised of a repeating sequence of 4 pixels opaque and 4 pixels transparent.

### What is actually happening?

Dashed line is comprised of a repeating sequence of 4 pixels opaque and 2 pixels transparent.

---
This behaviour changed between 4.9.0 -> 5.0.2. There seems to be no option to control how dashed lines are drawn. For some reason, the distance of the transparent portion of the line was halved.

**Comment by susiwen8** [comment]
I think this was by design.

**Comment by plainheart** [comment]
The default dash offset has been changed since v5.0.0.

Currently we provide some new options:

`lineStyle.dashOffset`, `lineStyle.cap`, `lineStyle.join`, `lineStyle.miterLimit`

And `lineStyle.type` can now accept a `dashArray`, for example,

```js
{
    lineStyle: {
        type: [12, 3, 3], // before v5.0.0, it can only be `solid`, `dotted`, `dashed`
        dashOffset: 2 // To control the offset of dashed line
    }
}
```

But sorry that they are not documented yet. We'll add them later.
