### ISSUE TITLE
xAxis Label Overlap

### ISSUE THREAD

**Issue by dyoon-linevision** [apache/echarts#14528]
**Using v4.7.0:**
![Screen Shot 2021-03-24 at 4 07 37 PM](https://user-images.githubusercontent.com/58481200/112376638-12f8cb80-8cbb-11eb-9366-fbc9631d59fe.png)

**After upgrading to v5.0.2:**
![Screen Shot 2021-03-24 at 4 06 11 PM](https://user-images.githubusercontent.com/58481200/112376506-eba1fe80-8cba-11eb-8b1a-34c72dc37d44.png)

### Version
5.0.2

### Steps to reproduce
- Upgrade to eCharts 5.0.2

- Use the following options for xAxis:
```js
options.xAxis.push({
      gridIndex: ndx,
      type: 'time',
      axisLabel: {
            formatter: function (date, index) {
                  return DateTime.dateFormat(new Date(date), true)
            },
            showMaxLabel: false
      },
});
```

### What is expected?
Expect the xAxis intervals to be spread out far enough so that the labels don't overlap.

### What is actually happening?
After upgrading to eCharts v5, the labels now overlap. The chart options did not change.

**Comment by plainheart** [comment]
Thanks for your feedback. This is related to #13682 and #14266. It will probably be fixed in v5.1.0 or v5.2.0.

**Comment by JesperBalslev** [comment]
Any news?

**Comment by tomazk8** [comment]
Any more news? I have the same problem. I noticed that axis ticks are also irregularly placed which should not happen. I am using version 5.1.2.
![image](https://user-images.githubusercontent.com/9772517/131790628-409482e2-9ff5-49b8-856d-baefb316f1f2.png)

**Comment by tomazk8** [comment]
@plainheart Thanks a lot. I am anxiously waiting for the new version :). Do you already know when it'll be released?

**Comment by hannata** [comment]
when will it be fixed ? I'm using the v5.2.2 and it still overlaps

**Comment by tomazk8** [comment]
For us it works now with version 5.2.2 - well, sort of. What axis does now is that it simply hides the ones that overlap. It should rearange the layout of the axis instead because the result is not that good as it could be. The axis layout algorithm is in general implemented badly. I know that the problem is that you cannot calculate the tick positions directly because in order to check if two labels overlap, you already need the tick positions. I have implemented such an algorithm long time ago where I roughly estimated the tick positions, checked if texts overlap and if yes, increase the tick offset and continue until I got the correct positions. It usually took only a couple of cycles and produced perfect result.

**Comment by Wintermute79** [comment]
I had the same issue with 5.2.2. For me it was fixed with setting `xAxis.axisLabel.hideOverlap` to true.

**Comment by Wintermute79** [comment]
> I had the same issue with 5.2.2 when using label type 'time'. For me it was fixed with setting `xAxis.axisLabel.hideOverlap` to true.

Tip: if you have axis labels of different lengths (e.g. weekday names), pad the ends with spaces to the same length to get better results.
