### ISSUE TITLE
dispatchAction does not support component IDs

### ISSUE THREAD

**Issue by Bilge** [apache/echarts#14785]
### What problem does this feature solve?
`dispatchAction` supports addressing series and data by _name_ but not by _id_.

In the following excerpt from the documentation we can see it indexes and names of series and data, but not the _id_ of any of series.

![image](https://user-images.githubusercontent.com/470626/115957441-63518c00-a4fa-11eb-8b02-92c4d4b03d7e.png)

This seems to be the case for all `dispatchAction` targets, including the `legendToggleSelect` API which I want to use, that supports `name` but not `id`.

![image](https://user-images.githubusercontent.com/470626/115957477-a875be00-a4fa-11eb-89d7-301418c923e3.png)

This is despite the fact that the documentation explicitly states the ID can be used to address the component via the API.

![image](https://user-images.githubusercontent.com/470626/115957506-d0652180-a4fa-11eb-92c6-6b2795a70045.png)

I deliberately do not want to give a name to my series because I do not want it visible in the legend. I want to control it separately via the API. Yet, I cannot address it via its ID, only by its name, even though giving it a name has side-effects.

### What does the proposed API look like?
```js
dispatchAction({
    type: 'legendToggleSelect',
    id: 'seriesId',
})
```

**Comment by Ovilia** [comment]
First, you may define the name of the series and it does not have to be in the legend if you don't want to. Just don't put it inside `legend.data` will do.

If you wish to use id, most likely you have to specify the id in the series otherwise you may not know the default logic of series id (in fact, it looks like `"\u0000Series Name\u00000"`). So that won't be much difference if you specify `id` or `seriesName`.

I tried with `seriedId` and it does not work. I don't know why it is not supported by now. But if you still have this requirement, we can discuss it more.

**Comment by pissang** [comment]
Actually `legendToggleSelect` is dispatched to `legend` component, not series. So the `name` property is from `legend.data`. And default `legend.data` is comes from `series.name` not `series/id`
