### ISSUE TITLE
No timed emphasis animations in Graph with layout: "force"

### ISSUE THREAD

**Issue by joshuacassidygrant** [apache/echarts#14943]
### Version
5.0.2

### Reproduction link
[https://jsfiddle.net/eskjn6y3/](https://jsfiddle.net/eskjn6y3/)

### Steps to reproduce
Make a basic chart with series "graph" (works fine with the les miserables example)
Use layout: "force"
Hover over a node to emphasize; the animation will be instant.

Change layout to "circular"
Animations are now smooth and timed properly.

Adding animation properties etc. doesn't seem to change this.

### What is expected?
That layout: "force" graphs will have smooth emphasis transition animations like "none" and "circular" graphs

### What is actually happening?
They are all 0 second transitions and look glitchy.

---
I don't think that this is intentional, but it would make force graphs much nicer to have properly eased transitions.

**Comment by joshuacassidygrant** [comment]
Note that it seems that force layout graph get emphasis animations when animationLayout: false

**Comment by mvelzel** [comment]
Our code uses a graph with layout: "force" and we are facing this same issue. I had to disable emphasis for now since it just looks too jumpy with it enabled.

I would also like to see this fixed. And for the animationLayout: false fix, I have no idea what that is about, I found no mention of it anywhere in the documentation or this repository.
