### ISSUE TITLE
Grid border not closed at left-top corner (no z in SVG path)

### ISSUE THREAD

**Issue by mindon** [apache/echarts#15023]
### Version
v5.1.1

### Reproduction link
[https://qp9zl.csb.app/](https://qp9zl.csb.app/)

### Steps to reproduce
render with option 
```
const option = {
        grid: {
          show: true,
          borderWidth: 3,
          borderColor: "#000000"
        }
      };
```

### What is expected?
corner closed

### What is actually happening?
corner not closed

**Comment by plainheart** [comment]
I'm not sure why [this commit](https://github.com/ecomfe/zrender/commit/da94b645863f50d6975c4c56e3c97f08bd5edd4f#diff-e3a572e684749bd567f01d5a55350564cf17a3c73a38980f3e626568f72ee6a2L67) https://github.com/ecomfe/zrender/commit/da94b645863f50d6975c4c56e3c97f08bd5edd4f removed `ctx.closePath()`. @pissang

**Comment by pissang** [comment]
@plainheart I thought the first point and the last point has been connected in the `roundRect.ts` helper so there is no need to do `closePath` again, which is an extra cost in the case that drawing lots of rect(like in benchmark.html). But it seems to be a mistake in this case.

Also, only the SVG renderer that drawing a rectangle without border-radius will have this issue. Because canvas renderer will use `ctx.rect` command, which is closed underlying automatically. And drawing rectangle with `border-radius` also has no issue because there is an `arc` command connecting the first point and last point, which is like:

![image](https://user-images.githubusercontent.com/841551/119437249-51a91180-bd50-11eb-9837-475d6eaf3397.png)

So I think what we need is adding an `Z` command when rendering `rect` command in the SVG renderer https://github.com/ecomfe/zrender/blob/da94b645863f50d6975c4c56e3c97f08bd5edd4f/src/svg/graphic.ts#L229

**Comment by plainheart** [comment]
@pissang Yes. I agree with you. That's right.
