### ISSUE TITLE
pictorialBar 象形图 设置Y轴 最小值  ， 但图形依然在最小值之下 ，并未从最小值开始

### ISSUE THREAD

**Issue by juzhiqiang** [apache/echarts#15482]
### Version
5.1.2

### Steps to reproduce
https://echarts.apache.org/examples/zh/editor.html?c=doc-example/pictorialBar-patternSize 
y轴设置 min 即可重现

### What is expected?
重最小值开始

### What is actually happening?
出现在设置最小值底部了，覆盖了x轴

**Comment by juzhiyuan** [comment]
@juzhiqiang Please describe your issues in more detail :) then I would like to take a look at this one.

**Comment by linghaoSu** [comment]
> @juzhiqiang Please describe your issues in more detail :) then I would like to take a look at this one.

@juzhiqiang I have also encountered the problem he encountered. When the minimum value of the numerical dimension axis is set (usually greater than zero and the data is greater than zero), there will be a  `pictorialBar` overflowing the chart area, suspected to be `ClipShape` does not have any graphic elements in the `pictorialBar` to take effect?

The effect diagram of the problem is as follows
![image](https://user-images.githubusercontent.com/56526981/128593602-689a14ce-7ee0-4107-891a-332f14bd226c.png)

@juzhiqiang Does the screenshot match the problem you encountered?

**Comment by plustliang** [comment]
> > @juzhiqiang Please describe your issues in more detail :) then I would like to take a look at this one.
> 
> @juzhiqiang I have also encountered the problem he encountered. When the minimum value of the numerical dimension axis is set (usually greater than zero and the data is greater than zero), there will be a `pictorialBar` overflowing the chart area, suspected to be `ClipShape` does not have any graphic elements in the `pictorialBar` to take effect?
> 
> The effect diagram of the problem is as follows
> ![image](https://user-images.githubusercontent.com/56526981/128593602-689a14ce-7ee0-4107-891a-332f14bd226c.png)
> 
> @juzhiqiang Does the screenshot match the problem you encountered?

same problem. echarts version 5.0.2

**Comment by juzhiqiang** [comment]
https://echarts.apache.org/examples/zh/editor.html?c=doc-example/pictorialBar-patternSize 
问题重现代码

**Comment by yuanyuanshen** [comment]
How to solve it later
