### ISSUE TITLE
Value is shown as [object Object] in generated aria-label 

### ISSUE THREAD

**Issue by josve** [apache/echarts#15734]
### Version
5.2.0

### Reproduction link
[https://jsfiddle.net/2c8g1pqn/](https://jsfiddle.net/2c8g1pqn/)

### Steps to reproduce
1. Create a chart with the following options (for go to the jsfiddle) 
"{
    "dataset":{"dimensions":["c_0","c_1"],
    "source":[{"c_0":"Amount used","c_1":1699.0},{"c_0":"Amount left","c_1":2301.0}]},
    "series":[{"type":"pie","silent":true,
    "encode":{"itemName":"c_0","value":"c_1"},
    "radius":["60%","80%"]}],
    "aria":{"show":true}};"
2. Look at the aria label

### What is expected?
Aria label says: "This is a chart with type Pie chart.The data is as follows: the data for Amount used is 1699, the data for Amount left is 2301. "

### What is actually happening?
Aria label says: "This is a chart with type Pie chart.The data is as follows: the data for Amount used is [object Object], the data for Amount left is [object Object]. "

**Comment by Ovilia** [comment]
@josve Fixed in #15777 that the label will be "This is a chart with type Pie chart.The data is as follows: the data for Amount used is Amount used, 1699, the data for Amount left is Amount left, 2301. "

We cannot know which dimension to be used in the aria right now. Do you have such a requirement? If so, an option like `aria.label.data.dimension` may be required.

**Comment by josve** [comment]
Thanks for the fix, well it would be nicer if you could specify the dimension but it works for now.
