### ISSUE TITLE
Layer control for axis baseline and series data labels

### ISSUE THREAD

**Issue by hughess** [apache/echarts#15933]
### What problem does this feature solve?
By default, the x axis baseline is positioned behind the bars in a bar chart. This can make the bottom of the chart look messy, especially when the bar color is light (you can see it overlapping the axis line more):

![CleanShot 2021-10-22 at 15 30 52](https://user-images.githubusercontent.com/12602440/138601852-9124cf2a-9834-472e-9ec9-f6b361bd1764.png)

A workaround is to add a high `z` value to the axis line to bring it to the front:

![CleanShot 2021-10-22 at 15 30 31](https://user-images.githubusercontent.com/12602440/138601870-01e6bca1-fb25-4172-8980-50b24a26e758.png)

This doesn’t work if there are data labels close to the axis line - the axis line will overlap the label:
![CleanShot 2021-10-22 at 15 33 53](https://user-images.githubusercontent.com/12602440/138601873-0e509f11-d1bf-4692-b53a-1541f1491acf.png)

One way to solve this would be to add a `z` property to the data label element, so you can position the bars at the back, the axis baseline on top of those, and the bar labels on the very top. I assume an issue with this approach would be if it's not possible to separate the `z` values for individual graphic elements inside the same parent element.

### What does the proposed API look like?
Add a `z` property to the series data labels.

**Comment by ZeekoZhu** [comment]
I'm facing a similar issue, to avoid the axis line being overwritten by the bar chart, I set a higher `z` to the x-axis, but it also brings split lines up.

Adding a `z` property to the split lines is also necessary so that I can set a higher `z` to the axis line and a lower `z` to split lines.

![image](https://user-images.githubusercontent.com/13861843/180715123-10c66038-3a8d-47ff-97cd-bf48b4f84ba3.png)
