### ISSUE TITLE
Importing specific modules from CDN

### ISSUE THREAD

**Issue by LeaVerou** [apache/echarts#16054]
### What problem does this feature solve?
I'm not sure if this due to lack of docs around this, but it does not seem possible to only import specific modules as described [here][1] and let the browser do the tree-shaking when using the CDN (jsdelivr), only one large monolithic bundle is available. 

### What does the proposed API look like?
It would be good to have built versions on jsdelivr of all modules one can import via the npm syntax, so that people can do things like [this][1] while using a CDN as well. 

[1]: https://echarts.apache.org/handbook/en/basics/import#importing-required-charts-and-components-to-have-minimal-bundle

**Comment by plainheart** [comment]
I remember we ever built ES modules into the `esm` directory in several previous versions since [v5.0.0](https://www.jsdelivr.com/package/npm/echarts?version=5.0.2). But it seems only a minimized version remained since [v5.0.2](https://www.jsdelivr.com/package/npm/echarts?version=5.0.2). It would be great if we provide such a feature like the [uuid](https://www.jsdelivr.com/package/npm/uuid?path=dist) package, which provides ESM support for both browser and Node.

**Comment by pissang** [comment]
Hi, I'm afraid we can only import [the whole bundle](https://cdn.jsdelivr.net/npm/echarts/dist/echarts.esm.js) in the browser now. 

Importing ES module in the browser needs to have `.js` extension explictly. But we don't use `.js extension in our source code. If we importing modules from 'echarts/core', it will try to load other modules without giving `.js` extension and failed. 

`import-map` seems to be a potential solution, but it don't have wildcard to match all the paths.

I'm not sure if importing specific modules with hundreds of dependency files has the scenario rather than importing a single large bundled file.  If there is a scenario, I think we can plan to add '.js' extension to fix this issue in our `import` statements.

**Comment by plainheart** [comment]
Instead of changing the source code, how about handling the `.js` extension name in a build script?

**Comment by LeaVerou** [comment]
> Instead of changing the source code, how about handling the `.js` extension name in a build script?

Yeah, that's what I was suggesting. Keep your source code as-is, just mirror the structure of the `lib` directory in `dist`, with output files that *can* be used in a browser.
