### ISSUE TITLE
Efficient way to chart from a dataset that is a list of records, not a pivot table

### ISSUE THREAD

**Issue by LeaVerou** [apache/echarts#16083]
### What problem does this feature solve?

Currently, while Echarts supports providing the data via a dataset, the dataset needs to be in pivot table format: that is two dimensions (x and y) with a value where they meet. 

Let's take the World population example data from [this demo](https://echarts.apache.org/examples/en/editor.html?c=bar-y-category).
While in that demo the data is not provided by a dataset, we can define a dataset to create the same result like so (reducing to 3 countries for brevity):

```js
dataset: {
	dimensions: [
		'Country', '2011', '2012'
	],
	source: [
		['Brazil', 18203, 19325],
		['Indonesia', 23489, 23438],
		['USA', 29034, 31000],
	]
},
```
Result [here](https://codepen.io/leaverou/pen/oNemwEz?editors=0010).

However, this format only works for certain types of data. For example, how would you now draw a chart that further breaks down population by Male population and Female population (as stacked bars)? 

It also has other, more minor, problems:
- This format assumes you have exactly one data point per year per country, which may not be the case (though you can just specify `undefined`)
- This format is clumsy if the data from 2011 and 2012 come from different collections: we first need to iterate over both arrays and combine them.
- The header is a weird mix of the name of one dimension ("Country") with the *values* of the other. There is no way to say what these values actually *are* (Year).

In the database world, it's more common to represent data as *records*, i.e.: 

```js
dataset: {
	  dimensions: [
		    'Country', 'Year', 'Population'
	  ],
	  source: [
		    ['Brazil', 2011, 18203],
		    ['Brazil', 2012, 19325],
		    ['Indonesia', 2011, 23489],
		    ['Indonesia', 2012, 23438],
		    ['USA', 2011, 29034],
		    ['USA', 2012, 31000]
	  ]
},
```

However, there doesn't seem to be a simple way to draw the same chart with this kind of dataset ([failed demo here](https://codepen.io/leaverou/pen/mdMvwwm?editors=0010)). I've literally tried every combination of `encode`, `name` on series, etc since yesterday and it simply does not seem possible.
I know there is a way involving data transform, with one filter per year, but that's inefficient in the general case (O(N) per filter means O(N^2) worst case).
Apologies if I’m missing something and that's already possible (without one filter per year!).

*(Note that this World population demo is just example data to illustrate the problem, I'm not actually drawing world population charts!)*

### What does the proposed API look like?

I'm not yet familiar enough with the Echarts API to propose changes to it. Perhaps a way to declare that data is in record format? Or a data transform to essentially do group by?

**Comment by pissang** [comment]
This feature sounds like data aggregation. @100pah has written a simple lib that integrates a basic aggregation transform support. https://github.com/100pah/echarts-simple-transform . But I'm not sure if it's ready for this purpose. Perhaps @100pah can give more explanation on this.

**Comment by 100pah** [comment]
@LeaVerou Thanks for the very details investigation and  description!

It's a very good case that echarts should better to enhance.

You mentioned
> In the database world, it's more common to represent data as records

For years the data format (both `series.data` and `dataset`) that echarts can accept are relatively "near" the display of charts but "far from" the format that users and data storage commonly used. That cause that users need to write some data transformation code themselves.

Since echarts v5.0, a new mechanism [data-transform](https://echarts.apache.org/handbook/en/concepts/data-transform/#data-transform) is introduced, which aims to provide a plugin mechanism to embed data transformation code into echarts workflow, so that end users can use some transformation code (no matter from third-party or official) in out-of-box way, rather than write them themselves.

But this mechanism is still at a start-up phase. The pro of the mechanism is the convenience for end user. But the con, where I am worried about IMO, might be that transformers may introduce complex configurations, which brings to users extra cost of investigating how to use them, and after that investigation, some of the users may find it's not what they want, and still need to write some transformation code to match their specific requirements.

But your issue and some other relevant issues provide that there are real needs of it and we should better move forward on it, probably marking more out-of-box transformations and see what them will bring to users.

---

Go back to the case:

```js
dataset: {
	  dimensions: [
		    'Country', 'Year', 'Population'
	  ],
	  source: [
		    ['Brazil', 2011, 18203],
		    ['Brazil', 2012, 19325],
		    ['Indonesia', 2011, 23489],
		    ['Indonesia', 2012, 23438],
		    ['USA', 2011, 29034],
		    ['USA', 2012, 31000]
	  ]
},
```

Yes, at present inside echarts there is no way to convert this format of data to its pivot table. The built-in transformers can only filter and sort, and some other transformers like [echarts-simple-transform](https://github.com/100pah/echarts-simple-transform) and only do simple aggregation by one dimension. 

It's a good case that echarts probably need to add pivot table transformer to accept that kind of format.

---

About detail of the implementation, I think it could be either integrated with an aggregation transformer, or standalone and possible to be piped after an aggregation transformer, taking the aggregation output (aggregated by two specified dimensions) as the input.

**Comment by alonahmias** [comment]
why was this issue closed? i think it is very neccary

**Comment by Skaidus** [comment]
I agree

**Comment by namannitr** [comment]
This thread was closed by the stale bot but the gap is unchanged on current ECharts: `dataset` + `encode` still cannot split long/tidy records into series without one `filter` per group.

Per the contributing guide (do not piggy-back on a stale closed issue), I opened a new feature request with a concrete `pivot` / `groupBy` API proposal and production context:

**#21742**

Related still-open work: built-in aggregate #15306, draft migration #16903.
