### ISSUE TITLE
Hi Team, I am looking for a feature where user can edit the Chart Elements, Chart Axis, Chart Area etc., dynamically (ad-hoc modification of Chart elements). Thanks Ravalika

### ISSUE THREAD

**Issue by RavalikaP** [apache/echarts#16253]
### What problem does this feature solve?

User interaction with the Chart elements

### What does the proposed API look like?

With an example

**Comment by Ovilia** [comment]
I'm afraid this is not an easy thing to do, otherwise we would provide such a tool at the first place. That being said, you could still do something about it. For example, if you would like to provide a feature that user can click the chart area to change axis.splitArea.areaStyle, you could check the click position with grid location (grid.left, right, ...).
