### ISSUE TITLE
[Bug] 时间轴maxInterval设置2天间距，刻度宽度分配不均

### ISSUE THREAD

**Issue by zengyuehao** [apache/echarts#16484]
### Version

5.2.2

### Steps to Reproduce

![企业微信截图_16444589389057](https://user-images.githubusercontent.com/70467633/153323577-b80d72c1-3412-49a0-8ef9-968fa6409e17.png)

### Current Behavior

设置maxInterval：2 * 24 * 60 * 60 * 1000

### Expected Behavior

设置maxInterval：2 * 24 * 60 * 60 * 1000时 刻度宽度能够均匀分配

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by lefex** [comment]
You need to provide a demo so that we can solve the problem more quickly。

**Comment by Ovilia** [comment]
The splitLines of time axes are expected to have varied intervals because time axes have special rules to determine where the label lies. For example, in the demo you provided, most of the intervals are 2 days like 1-27, 1-29 and 1-31. But in order to display 2-1, the interval from 1-31 is one day so its space is smaller.
We choose to display coarse-grained labels over fine-grained ones so that 2-1 is choosen over 2-2.
There's not much can be done here. If you insist on having the same gap, maybe you could try with category axes.
