### ISSUE TITLE
[Bug] 柱状图在横轴为时间时，无法按照时间正常堆叠

### ISSUE THREAD

**Issue by Sorakado-Aoo** [apache/echarts#16700]
### Version

5.3.1

### Steps to Reproduce

在5.2.2中正常，5.3.0之后异常
示例option
```ts
option = {
  title: { left: 'center' },
  color: [
    '#F73809',
    '#0909F7',
    '#09F7F7'
  ],
  toolbox: { right: 30, feature: { saveAsImage: {} } },
  tooltip: { trigger: 'axis' },
  legend: {
    show: true,
    padding: [10, 50],
    data: [
      'bar1',
      'bar2',
      'bar3'
    ]
  },
  grid: { left: '6%', right: '6%', bottom: '12%', containLabel: true, top: 40 },
  xAxis: {
    type: 'time',
    minInterval: 86400000,
    splitLine: { show: false },
    axisLabel: { rotate: 0 }
  },
  yAxis: {
    scale: true,
    type: 'value',
    axisLabel: { formatter: '{value} kWh' },
    min: 0,
    max: null
  },
  series: [
    {
      name: 'bar1',
      type: 'bar',
      stack: 'one',
      data: [
        ['2020/03/09', 2.498],
        ['2020/03/10', 0.501]
      ]
    },
    {
      name: 'bar2',
      type: 'bar',
      stack: 'one',
      data: [['2020/03/10', 0.827]]
    },
    {
      name: 'bar3',
      type: 'bar',
      stack: 'one',
      data: [['2020/03/10', 0.814]]
    }
  ]
};
```
### Current Behavior

![image](https://user-images.githubusercontent.com/42763278/158949120-711186b3-9a30-4f2e-9b2a-90a4fd3a02e6.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/42763278/158949157-75bd5e8b-a10c-45b2-a81c-9a62c3789085.png)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
### Problem locating
In one sentence, Echarts is stacking value by index, not by name.
Both 5.2.x and 5.3.x deal with stack data here and put it in `storage`:
https://github.com/apache/echarts/blob/3961cefc0329cfa8782602fc2aea46cc76c3f50e/src/processor/dataStack.ts#L123-L139
However, `stackedDataRawIndex` is only decided by index of data. So if you have a hole in your stacked data, it will cause wrong stack.

#### Why it works in 5.2.x
The reason why no error occurs in 5.2.x is that it's using a completely new variable to store stack info instead of taking from `storage`. Check the variable `lastStackCoords` here:
https://github.com/apache/echarts/blob/000ee7d2d1272cee96b0bd19bff9207301096c8d/src/layout/barGrid.ts#L445
This is no longer the case in 5.3.x.

#### Why it doesn't work in 5.3.x
Echarts now pick up stack data directly from `storage` and the 'stack-by-index' error is unveiled as long as there's a hole in stack data. Take a look at the new function in 5.3.x.
https://github.com/apache/echarts/blob/3961cefc0329cfa8782602fc2aea46cc76c3f50e/src/layout/barGrid.ts#L465

So the 'stack-by-index' problem exists in **BOTH** version but the way to handle it changes in 5.3.x so the error pops up.

### Solution
A good and general solution is not yet found by me, but I'll be looking for one and update it when I find it.
