### ISSUE TITLE
[Bug] Data plotted at false position after zooming with filterMode "none"

### ISSUE THREAD

**Issue by lukas-sl** [apache/echarts#16746]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-datazoom-bug-q196p9

### Steps to Reproduce

1. I have created a chart that contains both line and scatter series objects.
2. The x-axis is of **type "category"**.
3. The **filterMode** of the dataZoom feature is set to **"none"** in order to prevent the line from disappearing if only one point of the line is in view after zooming.
4. Zoom in with the dataZoom feature in such a way that only one tick of the x-axis but the entire range of the y-axis is in view.

Following picture shows the chart before zooming in:
![image](https://user-images.githubusercontent.com/5834134/160074666-1729eaa1-7809-40b8-800a-99789fc8d08e.png)

### Current Behavior

After zooming in as described in step 4, the data of the other ticks is plotted at the same x-position (see picture below). 
![image](https://user-images.githubusercontent.com/5834134/160074555-9f9b1092-312a-44c8-86c7-e3949d29acb0.png)

### Expected Behavior

After zooming in as described in step 4, only the data in view should be plotted at the correct position (as when filterMode is not set to "none").
![image](https://user-images.githubusercontent.com/5834134/160075006-762193bb-c010-4013-9d57-d56614ecb148.png)

### Environment

```markdown
- OS: Windows 10
- Browser: Google Chrome 99.0.4844.51
- Framework: React 17.0.2
```

**Comment by jiawulin001** [comment]
#### #16852 is also caused by this bug.
### This bug is caused by two logic problems.

#### The first one is here:
When Echarts tries to determine the location of each series 
https://github.com/apache/echarts/blob/a5257e38ad7776c766879c83854b1faa2771a454/src/coord/Axis.ts#L122-L133
We enters:
https://github.com/apache/echarts/blob/a5257e38ad7776c766879c83854b1faa2771a454/src/scale/helper.ts#L129-L132
Here we have `extent = [320, 320]` which means there's only one category to be shown.
However a TOO simple judgement is used here and make position of all three categories of line 0.5, so they all locate at the middle of the chart after zooming to one only category.

#### The second one is here:
https://github.com/apache/echarts/blob/a5257e38ad7776c766879c83854b1faa2771a454/src/util/number.ts#L47-L65
We have r1 = r0 = 320 here (come from `extent = [320, 320]`) so subRange is 0 and won't distinguish categories at all.

**Submitting a PR to solve this.**
