### ISSUE TITLE
[Bug] treemap.data.itemStyle.colorAlpha is not work, when color has value.

### ISSUE THREAD

**Issue by fuchunhui** [apache/echarts#16749]
### Version

5.3.1

### Link to Minimal Reproduction

https://stackblitz.com/edit/js-xudcjr?file=index.js

### Steps to Reproduce

use link or copy the following content.
```
option = {
  series: [
    {
      type: 'treemap',
      label: {
        color: 'black',
      },
      data: [
        {
          name: 'nodeA',
          value: 10,
          color: ['red', 'pink'],
          children: [
            {
              name: 'nodeAa',
              value: 4,
              itemStyle: {
                color: 'cyan',
                colorAlpha: 0.3, // not work
              },
            },
            {
              name: 'nodeAb',
              value: 6,
              itemStyle: {
                color: 'rgba(0, 255, 255, 0.3)', // this is right
              },
            },
          ],
        },
        {
          name: 'nodeB',
          value: 20,
          children: [
            {
              name: 'nodeBa',
              value: 20,
              children: [
                {
                  name: 'nodeBa1',
                  value: 20,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
```

### Current Behavior

![image](https://user-images.githubusercontent.com/29879262/160117047-cc94f3d8-cf9a-4f3f-8ee9-c1446d0b0df0.png)
`nodeAa` and `nodeAb` are different color.

### Expected Behavior

![image](https://user-images.githubusercontent.com/29879262/160117518-7ade5429-afc4-444a-a3fa-ce4aebc9177d.png)
the two are same color.

### Environment

```markdown
- OS: macOS Catalina
- Browser: Chrome 99.0.4844.83
- Framework:
```

### Any additional comments?

[style.ts#L159](https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/visual/style.ts#L159)

maybe it's here.

**Comment by jiawulin001** [comment]
To solve this bug, we might need a little discussion.
Let's find the problem step by step.

## Problem location
After correctly dealing with color at:
https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/chart/treemap/treemapVisual.ts#L95-L99
Echarts tries to reset the data (which I don't know why) at:
https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/core/Scheduler.ts#L625-L639
and from line 632 we enters:
https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/visual/style.ts#L137-L173
and finally from line 156 we enters:
https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/model/mixin/makeStyleMapper.ts#L27-L54
The bug comes at line 46. The function `getShallow` finds the value of `model.propName`, which is `model.color = 'cyan'` here., ignoring the property `model.colorAlpha` at all. Then it returns it to `val` and make `style.fill = val = 'cyan'`. 
Then when style is returned, it overwrites the existsStyle 
(where `existsStyle={fill: 'rgba(0, 255, 255, 0.3)'}` before overwriting!) 
as @fuchunhui said at:
https://github.com/apache/echarts/blob/d3dbf1215a0ae0c5075efffb10b17fe4de37582c/src/visual/style.ts#L159

## Plan of fixing
Since this problem has involved serveral models, changing which might cause unknown problem, I could offer two plans of fixing. 
- One is to remove colorAlpha completely because we can directly define the opacity at itemStyle.color. 
- The second one is to add a judgment inside `getShallow`. If 'color' is asked to be found, then try finding colorAlpha as well and return a correct color. 

**I can submit a PR for either one and I respect the decision of echarts member.**

**Comment by Ghostbird** [comment]
Quite silly. `colorAlpha` has been removed citing this bug. However the opacity behaviour of `treemap.data.itemStyle.color` has never been fixed. So now it's borked.

Demonstration: codesandbox.io/s/3kf2c8

Or if the codesandbox has expired:
1. Open https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&theme=dark
2. Add this to the first `data` entry:
    ```ts
          itemStyle: {
            color: 'rgba(255,255,255, 0.1)'
          },
    ```

### The problem

The colour is not actually opaque, it is pure white, even in dark mode. The area becomes painfully bright, and unreadable, even though the colour specified should have made it a dark-grey in dark mode and a light-grey in light mode.

**Comment by helgasoft** [comment]
> colorAlpha has been removed

@Ghostbird, _colorAlpha_ is working in v.5.6.0 - [Demo](https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&theme=dark&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5GDllgLYCGITANFQoATLmC7Ey1aqilToXDo1hNowIVgCC_WbEGyIYTgGU6AGyVJYAY2CngOZgHM2WaNpt2cG0yAAW4gAYAOgBWAF8BHQoANy5TAFclAEYAyKjrXwhTITZoCT0dGXTqeUVmVXUNLn4CqNiEpQAWWqkIlul2uQUlFTVNACMa4up6xOIANk70MM6AXRa2qKKo0p6KrAAhIfTRpQAmVM6rTOzc_OHKC_RV8r6N6rSL3eIDx-HjrJzXc6v0Zd_YDdlOt7kltgDYM9YAcpq1Yeh5hcZsVETpkVJUdNyPMwgBuIA)
But it's true that alpha transparency does not work with color _white_.

**Comment by Ghostbird** [comment]
> > colorAlpha has been removed
> 
> [@Ghostbird](https://github.com/Ghostbird), _colorAlpha_ is working in v.5.6.0 - [Demo](https://echarts.apache.org/examples/en/editor.html?c=treemap-simple&theme=dark&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXLANprrLkWxgCeIWxA5GDllgLYCGITANFQoATLmC7Ey1aqilToXDo1hNowIVgCC_WbEGyIYTgGU6AGyVJYAY2CngOZgHM2WaNpt2cG0yAAW4gAYAOgBWAF8BHQoANy5TAFclAEYAyKjrXwhTITZoCT0dGXTqeUVmVXUNLn4CqNiEpQAWWqkIlul2uQUlFTVNACMa4up6xOIANk70MM6AXRa2qKKo0p6KrAAhIfTRpQAmVM6rTOzc_OHKC_RV8r6N6rSL3eIDx-HjrJzXc6v0Zd_YDdlOt7kltgDYM9YAcpq1Yeh5hcZsVETpkVJUdNyPMwgBuIA) But it's true that alpha transparency does not work with color _white_.

The underlying issue is that regardless of `colorAlpha: 0.1` or `color(255,255,255,0.1)` echarts treemap fundamentally doesn't support alpha. Follow the instructions I give in my earlier comment, and it's readily apparent. You can insert `itemStyle: { color: 'rgba(255,255,0, 0.1)' }` instead if you're convinced this is a white-only issue.

You'll see that instead of alpha blending, the colour is actually blended with pure white.

In our software we built a workaround:
1. Lookup the background colour for the treemap
2. Alpha blend between the tile colour and the background colour in code
3. Use the resulting opaque colour for the tile.

 That's sufficient for our purpose. We don't _need_ actual alpha support. We're not showing the graph on a background image. We just wanted to leverage alpha blending to automatically adapt to a light/dark background.
