### ISSUE TITLE
[Bug] Changing area chart to step chart is not removing the area shading

### ISSUE THREAD

**Issue by dirslashls** [apache/echarts#16769]
### Version

5.3.1

### Steps to Reproduce

1. Go to https://echarts.apache.org/examples/en/editor.html?c=area-basic

2. At the end place the following code

```js
setTimeout(() => {
  option.series.map(s => {
    s.step = 'end';
    delete s.areaStyle;
  });
  myChart.setOption(option,{ notMerge: true });
},4000);
```  

### Current Behavior

After the 4 seconds timeout, the chart changes to step line chart but the area shading is not removed.

### Expected Behavior

The area shading should be removed.

Note that, if instead of setting the step to 'end', only the areaStyle is deleted, it does remove the area shading and show only the line chart as expected.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
This seems to be a bug.
## Problem Analysis
The problem comes at Lineview.ts.
When `notMerge` is set to `true`, Echart tries rendering from scratch.
Echarts finds that 'step' has changed so it enters this `if` branch:
https://github.com/apache/echarts/blob/977bba1350eb9158699a81223b753b08a25b7d46/src/chart/line/LineView.ts#L701-L703
But when it comes to here:
https://github.com/apache/echarts/blob/977bba1350eb9158699a81223b753b08a25b7d46/src/chart/line/LineView.ts#L729-L733
`isAreaChart` is false, but the `polygon` in the previous view is not cleared!

Note: Such situation is dealt with inside its `else` branch:
https://github.com/apache/echarts/blob/977bba1350eb9158699a81223b753b08a25b7d46/src/chart/line/LineView.ts#L744-L755

## Plan to fix
My plan is to add an `else` to dump `polygon` if `isAreaChart` is false. 
**Submitting a PR to solve this.**

**Comment by dirslashls** [comment]
As I am trying the changing of chart types, I am noticing a few more discrepancies.

1. First bar chart and then change the type to 'pie'. The legend is not shown.
2. First pie chart with %age labels inside the sectors and then change the type to 'bar'/'line'/'area'. The data labels are showing.

I thought 'noMerge' is as good as completely replacing the old options  with the new ones.
