### ISSUE TITLE
[Bug] markLine 中 label 的 distance 设置为数组时纵向偏移不生效

### ISSUE THREAD

**Issue by ZXYT** [apache/echarts#16829]
### Version

5.2.2

### Link to Minimal Reproduction

https://codepen.io/zxyt/pen/wvpmqNw?editors=0010

### Steps to Reproduce

将option设置为如下格式

```js
option = {
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value',
  },
  series: [
    {
      name: 'Highest',
      type: 'line',
      data: [10, 11, 13, 11, 12, 12, 9],
      markLine: {
        data: [{
          type: 'average',
          name: 'Avg',
          label: {
            distance: [0, 10]
          }
        }],
      }
    },
  ]
};
```
修改distance[1]的值

### Current Behavior

纵向间距未发偏移

### Expected Behavior

纵向间距发偏移

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
首先，`label`应放在`markline`下而不是`data`下。
其次，`label`默认的`position`为`end`，在此情况下只有横向间距可调节，当`position`为`middle`, `insideMiddleTop`, `insideMiddleBottom`时才可以调整纵向间距（此时横向不可调节）。

First, `label` should be placed under `markline` instead of `data`.
Secondly, the default `position` of `label` is `end`. In this case, only the horizontal spacing can be adjusted. When the `position` is `middle`, `insideMiddleTop`, `insideMiddleBottom`, the vertical spacing can be adjusted (at this time horizontal spacing not adjustable).

**Comment by ZXYT** [comment]
我希望为每个marline的label设置不同的样式😂
