### ISSUE TITLE
[Bug] showDelay配置数值偏大后鼠标移出图表后，tooltip还是会出现

### ISSUE THREAD

**Issue by xingfuyumin** [apache/echarts#16859]
### Version

5.3.1

### Steps to Reproduce

1、配置tooltip.showDelay = 2000
2、鼠标移到点或柱子上触发tooltip
3、鼠标立刻离开图表
4、tooltip消失后2s内又自动出现

### Current Behavior

tooltip延迟展示混乱

### Expected Behavior

鼠标移出图表后，tooltip就不该展示

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
`showDelay: 2000` 代表希望延时 2s 显示 tooltip，不是很确定光标移出后是否需要清除该延时。

**Comment by xingfuyumin** [comment]
> `showDelay: 2000` 代表希望延时 2s 显示 tooltip，不是很确定光标移出后是否需要清除该延时。

应该需要清除，如果用户不想tooltip消失，应该配置[alwaysShowContent]，如果没配置说明用户需要鼠标移出图表后就不要再出现tooltip，不清除延迟，就会出现意料之外的展示，肯定不能满足用户要求

**Comment by guoxunbo** [comment]
@xingfuyumin 解决了吗？这个问题

**Comment by guoxunbo** [comment]
@plainheart 有计划解决这个问题吗。最新的5.5还有这个问题。

**Comment by Ghostbird** [comment]
This really should be fixed. It persists in echarts 5.5.1 and made me not use tooltips at all, since they are completely unusable due to this issue.

When there's no delay they're annoyingly intrusive.

When there's a delay they're maddeningly intrusive.
- They pop up on every item you've moved the mouse across, unexpectedly.
- They don't disappear until you move the mouse into the item, and out of it again.
- However that makes a new one appear once the delay expires.
- With multiple graphs on a dashboard it's completely incomprehensible. There's tooltips seemingly randomly popping up all over the place, and trying to close them only makes it worse.
