### ISSUE TITLE
[stacked line chart overlap]

### ISSUE THREAD

**Issue by jairdean** [apache/echarts#16974]
### Version

5.3.2

### Steps to Reproduce

```js
option = {
  title: {
    text: 'Stacked Line'
  },
  tooltip: { trigger: 'axis', confine: true },
  legend: {
    orient: 'horizontal',
    itemGap: 3,
    bottom: 0,
    align: 'left'
  },
  grid: {
    left: '10%',
    right: '10%',
    bottom: '20%',
    containLabel: true
  },
  emphasis: { focus: 'series' },
  xAxis: {
    type: 'category',
    boundaryGap: false,
    data: [
      '2020-01-31',
      '2020-02-29',
      '2020-03-31',
      '2020-04-30',
      '2020-05-31',
      '2020-06-30',
      '2020-07-31',
      '2020-08-31',
      '2020-09-30',
      '2020-10-31',
      '2020-11-30',
      '2020-12-31',
      '2021-01-31',
      '2021-02-28',
      '2021-03-31',
      '2021-04-30',
      '2021-05-31',
      '2021-06-30',
      '2021-07-31',
      '2021-08-31',
      '2021-09-30',
      '2021-10-31',
      '2021-11-30',
      '2021-12-31',
      '2022-01-31',
      '2022-02-28'
    ],
    axisLabel: { rotate: 0 },
    axisTick: { alignWithLabel: true }
  },
  yAxis: {
    type: 'value',
    min: 14,
    axisLabel: {}
  },
  series: [
    {
      smooth: true,
      name: 'ABC',
      type: 'line',
      data: [
        22.35, 22.41, 22.24, 21.07, 22.25, 22.34, 22.44, 22.49, 22, 21.38,
        21.53, 21.9, 21.75, 21.85, 21.73, 22.51, 22.33, 22.17, 22.48, 22.35,
        22.33, 22.31, 22.45, 18.55, 16.92
      ],
      color: '#2B2C28',
      label: { show: true, hideOverlap: true }
    },
    {
      smooth: true,
      name: 'DEF',
      type: 'line',
      data: [
        22.65, 23.15, 23.64, 24.85, 23.8, 22.86, 21.18, 21.98, 22.02, 22.04,
        23.13, 23.4, 23.47, 22.43, 20.13, 19.83, 20.04, 19.55, 19.01, 21.92,
        21.19, 23.06, 23.07, 23.06, 22.15, 21.8
      ],
      color: '#05FCFE',
      label: { show: true, hideOverlap: true }
    },
    {
      smooth: true,
      name: 'GHI',
      type: 'line',
      data: [
        21.29, 20.8, 21.24, 22.74, 21.5, 21.53, 22.1, 22.03, 21.99, 22.02,
        21.97, 19.69, 19.49, 18.27, 17.85, 18.83, 20.67, 20.55, 21.65, 19.58,
        20.97, 20.91, 21.45, 19.09, 20.3, 19.8
      ],
      color: '#E75A25',
      label: { show: true, hideOverlap: true }
    },
    {
      smooth: true,
      name: 'JKL',
      type: 'line',
      data: [
        21.25, 21.5, 21.03, 19.33, 19.83, 20.43, 19.93, 20.22, 20.56, 21.16,
        21.47, 21.53, 21.48, 21.58, 21.44, 20.97, 20.82, 19.6, 20.67, 18.92,
        18.63, 18.72, 18.7, 17.2, 18.56, 18.7
      ],
      color: '#1C7293',
      label: { show: true, hideOverlap: true }
    },
    {
      smooth: true,
      name: 'MNO',
      type: 'line',
      data: [
        20.42, 20.38, 20.18, 20.88, 19.89, 19.81, 19.81, 20.16, 20.26, 20.18,
        20.29, 20.42, 20.06, 20.16, 20.17, 19.97, 19.84, 20.15, 20.04, 19.95,
        19.93, 20.02, 19.09, 18.8, 18.38, 18.31
      ],
      color: '#6761A8',
      label: { show: true, hideOverlap: true }
    }
  ]
};
```

### Current Behavior

Labels overlap

### Expected Behavior

labels ds not overlap

### Environment

```markdown
- OS: Windows MacOs
- Browser: Edge, Chrome, Safari, Firefox
- Framework: Ionic + Angular
```

**Comment by plainheart** [comment]
You should set [`labelLayout.hideOverlap`](https://echarts.apache.org/option.html#series-line.labelLayout.hideOverlap) instead of `label.hideOverlap`. See this [demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQDKYAhgMYDWOAJrADITQ6VEC-AGiJhgwLJBAEkGAE4QA5gpyyqdUhADOlQbAYwAZt3xyArjlhCiuZdFbSi6YPJzQKsSgAtnEAF4x6LB1HWAgwHABbAHE6KVgAZmFiWAAjYDBRCIIABiTiOixFaCpcAzA-dCt0BXl7QmTS90oARmyAUmDk-QVPJtaOvPQ0jOAsjwAmds7ifTc6bg46FJwsAjBZcwE8yJBPOk0taVgDYAZTTSpNFQgcbUs80gBBDQv64jAATxATSgY6cIUzg-0yGwFMdjosg-MTiBgKV0GsFY_zoBAA2iF0JRJpMALTZZq4-LNEHEbHZPEU3HjACcpKxOOy-PiRJJiIZFKZ2QALETsvSJpz8QBWVkC8mUgBsfPFjPxAHYxezBZSABxKzEqrk0mXKiVM1oa5IcvHNQnxfl6uXNcZG40SwkEu3JB3423jVWyimOlnEr3jR28i3-x2iv1W7346XBiMBhXOsk4x3q8Oa13ZHUxtNJ3GG1PGlWEs267ORm0Jk22p35-04qvuz0hAC6iPUWkWy1WyFgsnS_xM2XuITbmgAKhBmEcCkUAOphTwdlZrDYWfhbIgfZ6HN7oT7fKgANwK5lJEW4BGa3NbL0XXaQa8qeSuLleGOSqALmgiYjAnmX5mVaA6AiH5HgAIQAYQFPcfkKHgBWReh0U1dBxnGAA6eJhV0ND0O5ZocIw8Yr1gAN0OyeVCPQ8ZsNIjD4hI3DuUYjDuRpQicOaTDVWVVCuOFRJSK49ihPQ-VaLI1UJK4-VBNw4UCLozC5Iw5pKKU7keKUrDeO0lTMMUpjaOaVV0OFYzJXQmlxk1FtNX0LBnCoABicYwPGCCPQFLAliXbtNG8AB3f9V2VHzO0WD4wXcD8C1gTwIFYHAAHkDxUHy4nWTYCwfYgqmIWLki_H8_zMHBAOAn4ABEAFEADFoK-WDjAQlFkLipTJQk-J0Oabr0MlRjuXQqScJ6rTcNVSVON6ibhImjCKSonldPGHrmjknrGK29SmLk7JesE5oaRG_byJI46zOMk6CRm6zVq446xvI6bSJ6ijnuyV7cL6mbVVs5UHKcjxnOyYU6oguqau83y71gALgGCsqhwLcKVki6KHA6hKktS9LYhCzVcsfEJCuIYr0lKrLys1ICQKoKIAAkAElGv3Dw4N4ZVENRWA3zisjaRwg65uolixMY_iZoEqjDMWuThJE3ClpQ0SaXUy7JREy62N0EzqI1-URuM0zVTOyVdoO8yZq6vWTuFHjVcmKzLaswyuO5a7yKVg6jpO_6CzsgsgdUEGavEx4aJhzsjgRpHqZR400awDHTBi1WcZStLZAywmcpCfL0DJ9AKd_EKKvpjwACkAGkODZ5r4O5tq-adriaOlmbsj95S7dO4W8J7mkzrQgfhW-x7prbvDdv4hW8NFh2ZuYgf1YH1Vxj776DotvXTPu1X9clI7TPlTfYH1w3qL3szXsvgH7PEYHKGc5oILP4fo78mQ45CxOGlhqndO2NEpZ3xplFcRMC6ImLvDb8lNy600qlQAAsgAOWSg3EoLVm5IVbh1Z23Jz7O3iBNA6Jl15aUuqqbW_tFLUMMuQ7e1FmEUKdgdIWpEDpEIHl9AezRWEaxOmvC-_tGLkIkgdFaoirLYUPsIs6S0ZEZhvlQ0ypCb7EgfsHJ-ocX4W0lM0R4nowqw1jkFP-hdiDJyAVjOKmc8Y5wJmVKByRcpNhQPwAA3EAA).
