### ISSUE TITLE
[Bug] the second log Y axis affects the first log

### ISSUE THREAD

**Issue by FM3631** [apache/echarts#16992]
### Version

5.2.2

### Link to Minimal Reproduction

[Reproduction Link](https://echarts.apache.org/examples/editor.html?code=MYewdgzgLgBAJgQygmBeGBtAUDTByAJgAYSBaIgNnIFY8AaGARkYoF06d9izLyL6mBAJztOGQiSJ9yAdgGMAzNVG5x3KbyIAOAVrYdVEnlSJCBMhSq6TpjIruUHrx0s3OWnam70YEBFLSsvF0UBIQIgow0qRgAWeQUiSPVbWgYCWMcxKNt-BkURTxyfOXzGLMMUnx0yxmTvGLMGRMLsqqpiAWJ9NobSAkYEmXqXAj98gkCi9v6FBxHo_viGIViF6QI0mBk66b6CPKZKdd4CUpgtNb3RmpghD17RpouK50XE9xOZckGGLQfKt5vkRxoJXsENMC5vkiMNrpDyMsLhF4bIaAJYldHgjKOYUdi0bD5MdUbDyLc7HCCWTTP4eoCeN87GFdtSmb87viGQjfPJFF9XNCjlTuWi4glWaKyeU-ZK3mLDhQsVKmecKK0Va5blopmzXM8ZCL5WTOn8AcbvgNZQKxgJqEaIWiCELqODipakRQklhWABuLCgSCwRBQACmABkAJbQNDwJAIAB0AFsEAAHAAU6cjYaTAEo0AA-GDZ0NJjBJXP-wMxgBuCAANgBXCPR2DoEOJlMZrM5_OoIslst1StYECpqCR8CxgDenAnUHroYAXJhOLhZ7hNzBFwAzKArvDAUNgMMAJ3oa83YYAHvuYHgAOKnhBwSPH2AN8AAcxgUAAFqGMAAJ4wAg17Rngl4AL5OOul64FAY4Hq6ACkF5brgu53oe76huesFXqGt4Hk-L5vieoH1t-v4ATA16geBECQVuUGcFYiEgPWE6piuG5XqekZfl-eEHmBEGcDBnDXgAgoxK7YFufFbh2K4hi20DQQRSmbipcZhlG0AEbgX4CXAACSYBwERK6MNBbFOEBsnRvJl7aQhQGpsu95UV-6EYUmkZgCuRAJkQtksVp8G_h5Xl4D5flbiZkbmZZ1lMEZMABUFMAhYwGViRA4YIAARqG9a8VFuA7uAUAAMqRgAXrFCjxFFrEsfZnBJXALmKVFxUgFAiFJgeXpoZprlRYhPH3mNzGbu1MBWBAeFvhAvWbm50WeQe9aBaGCWbhAf4gAA7rVQFJgN5UwDuDYrRlul1k26lQBNfUYdtsV7WAB0ZcdZ0XVdnErnd9YPVFT0Ns2BlQBlMmMRZVnXjZGWOYjqUo0wdm4KwWBQb6QA)

### Current Behavior

<img src="https://user-images.githubusercontent.com/29879262/167251374-8c5470d2-f479-4188-bcd7-f96d0975d892.png" width="600">

### Expected Behavior

The two don't affect each other.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
### Problem locating
This problem exist here:
https://github.com/apache/echarts/blob/5cf53e24ac751650ce8d76dde957f1b0d0bd50e6/src/scale/Log.ts#L74-L76
When Echarts tries to obtain the extent of data and set ticks, it's trying to use the precision of `originalExtent` to fix `powVal`. This behavior is to fix the problem of #4158, where precision issue is caused by logarithm and exponentiation. However here `powVal` can be user-set min/max, which is 0.01 here and `originalExtent` is the real extent of data, which is 44 here. When using the precision of 44 to fix 0.01, tick value becomes 0 and it has nowhere to go on log axis. That's the reason why there's a big 0 up there.

### Plan to fix
The way to fix #4158 is not fixing it completely (a user-set max of 2000000000000 still displays wrongly) and it also causes #16992. My plan is to change the way to fix #4158 and can fix #16992 in the same time.

**Submitting a PR to solve this**
