### ISSUE TITLE
[Bug] Pie chart with large data has performance issue. 大数据量下饼图存在性能问题

### ISSUE THREAD

**Issue by LeoB-O** [apache/echarts#17173]
### Version

5.3.2

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=pie-legend

### Steps to Reproduce

Change the params of genData in the reproduction link (default value is 50) to bigger value (eg. 1000)
将复现链接中genData函数的参数（默认是50）替换为更大的值（例如1000）

### Current Behavior

page stuck
页面卡顿

### Expected Behavior

render takes shorter time
渲染更迅速

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

Seems like the function getPercentWithPrecision is called too many times, even though all the params is same (except idx). The result of seats can be reused.

看起来getPercentWithPrecision函数被调用了太多次，每次调用传的参数都是一致的（除了idx）。计算出来的seats结果是可以被复用的。

**Comment by Ovilia** [comment]
Pie charts are not expected to have large amount number of data. https://echarts.apache.org/examples/zh/editor.html?c=pie-legend is an example to show how legend paging works but from the perspect of data visualization, it's definitely a bad example of pie charts. This is because when there are a lot of data, the pie pieces are hard to tell which data is bigger and how much bigger they are to each other. It is better to use bar charts to show the difference.
For that reason, this performance issuse may not be prioritized.
