### ISSUE TITLE
[Bug] onDrag, not in sync with data on line plot.

### ISSUE THREAD

**Issue by wigsnes** [apache/echarts#17191]
### Version

5.3.2

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-react-draggable-0szzfl?file=/src/echartTest.tsx

### Steps to Reproduce

1. Drag one of the dashed points.
2. Release point between two dates.
3. Now you can not drag the same point by click and hold on the point, you have to find where you let go last time.

### Current Behavior

You drag a point off-axis on the X-axis it does not line up next time you want to drag, and you have to remember where you let go.

### Expected Behavior

Expect it to stick to the point, and be draggable on the point and not where you left it.

### Environment

```markdown
- OS: CodeSandbox
- Browser: Chrome
- Framework: React
```

### Any additional comments?

https://user-images.githubusercontent.com/10787984/172821831-a88b6169-b02f-434b-95ac-a989b779915b.mp4

**Comment by plainheart** [comment]
This bug may have been fixed in #17007 and the next version v5.3.3 is under release.

Try this [demo](https://echarts.apache.org/examples/editor.html?version=5.3.3-dev.20220609&code=MYewdgzgLgBBCeBbARiANgZQJYC8CmMAvDAEwAMA3AFCiSwAmAhlI0TANpUwcAsZANDAC0ARjIBdflw5CAzAOEBWSdPZCA7ADYAdIsHkV3NZtm7BfQzJIltIwYolVx1KiAAOULODYBvaZ6g0PAAuGD9ubig8AA8oUIByABUAJ3gYABFkxgBzbKwwbJgoAAs8CAIABRB8qAh4qQiYIIAzOJh44DwwKOT46QBfBqKQdE83UPCIqGSsXLxkgHkwBLBwPHrpbmaQZMRmHtDmgFcwYE9vAAo3RizECABKMM2I5LwoI-SwGAvnxviADQSMAA1L8ItdbhBtEwWOwJNooCAAGJYaJ4egXEiPUGNP4AHmQyQAfABNIE43HcCGMO7Q5iMdgicQI5Go9GY-5g-7URr9AZDbIzegTZ6I8btAAcAFINo1UFBEYgEiISDL-dJogBBaJYCAixqIfKhURkATPPbRULqM2NKDwNwhdoAN0YaCO6yG3EYOogABl8o6fDBwAAteYgQ6u8owPncQbSeDa3X6iKG5bCeSemAW0KaG1Te2O-Iut0e57e3X-sCB4NgMPJCMwZpRgixmNDGGMEMjJUcZ6TW2FhIQNBYejzWW4rU-gCSYHHlpg-cazSwaB6AFkQOOVms-ryswOCw7h6Px70s9xE7P5zFQsuIqv1_Mtzv2qtq_uIvHGkfIkP2nyCAxzLSlp11OcF3vS8mzXTdtyLD91meH8Ij_IoAPiICQMnRprwg29FwfLY4JfBDd0_FDpEscoZjKUJOF_MExwSRhcOPItR0_GCIEQEYSlCaZ3R4pBUEwXBHQQFB0GwfAYM7UJOyo7hxCofoXGOU5zi-CBihAAB3RIRnXLA3AuTtIJiR5JkQeAAGFihuKBoV1a4oGAYpNTOLwwAuI87RPdpdIMxJTPY2isDKSyiKzCzCMU-looGbk1KoKhNO87xihAozRlM8zEsI6zpFshynJciA3I8rztL80VMOy8dQrcL9-hSvl0pOTKvnAKoakyHI8gKAqWGiwQ3BAB4nm4Tt2DihdxDYUrHOSZzaCdeYoCRBtEAqNk0AueJBTHeoYAmh4XG4AB6K6YAAVTcGECCU7hlvK8ooAWDwfLqxoIvovtKXQ7gWPaNiYJm-kEpYME2xU5LqA6j7QsQPAQCOKALgy7TvmK67bs1eh6DgRz6AMmBgCwZJgCCCBvn07KPJgXUYFWWAnV1LBkCCR5ERgLpGG556smybQSvslbnI-r7aqPQVGDcRnocYbQ9jM7GfO-LAokQQR5qs6bcVed5PkNykAqLSnqaCdjGnO7WfNCN7Vu0dbNqMva0QOo6hVO7W8EQe4IZJhXAzBRpgBi8OImAeBoOj7hklCKSxNkghbpIaPUMpfIOeAoXBOSYTo_oEXskFoJC-LyluHAUuckOLqcfM6I9fgPGa9rsA-u6AbcnybIRsYMaOBKXVtFbopsqheBxBSzvs9xcA-KOco-I2xutM1i4O874LDOMsYh-i-ea8Xxpl_R8p0baDXLl3mvGrwXKTLM_XolPylz4iHBQjEMhYY8m_JyOM7VBBkBSp1Le3gjiPWYHgKowFaod2dlLN4MsfpyyyIrLAwBlaqwVljJu29_a6xgO_B-ic3gfC-MDM6k0HbgCdhLcqbtVoe32odY69A_Y6xAbidSKF-FtURmlfS-Qyb6W0IwImABRDa3R_TQC6PMQ6rxgL4FOrAp6iDGFgEgag7Q4BDqdm7CARAWi4FRF0dpbkQA) to check if it works.

**Comment by tarogege** [comment]
why cannot i drag this points in your demo in chrome？

**Comment by wigsnes** [comment]
> why cannot i drag this points in your demo in chrome？

Not sure why my demo do not work anymore.

Here is the code from echarts that show the problem: [Try this](https://echarts.apache.org/examples/en/editor.html?version=5.3.3-dev.20220609&code=MYewdgzgLgBBCeBbARiANgZQJYC8CmMAvDAEwAMA3AFCiSwAmAhlI0TANpUwcAsZANDAC0ARjIBdflw5CAzAOEBWSdPZCA7ADYAdIsHkV3NZtm7BfQzJIltIwYolVx1KiAAOULODYBvaZ6g0PAAuGD9ubig8AA8oUIByABUAJ3gYABFkxgBzbKwwbJgoAAs8CAIABRB8qAh4qQiYIIAzOJh44DwwKOT46QBfBqKQdE83UPCIqGSsXLxkgHkwBLBwPHrpbmaQZMRmHtDmgFcwYE9vAAo3RizECABKMM2I5LwoI-SwGAvnxviADQSMAA1L8ItdbhBtEwWOwJNooCAAGJYaJ4egXEiPUGNP4AHmQyQAfABNIE43HcCGMO7Q5iMdgicQI5Go9GY-5g-7URr9AZDbIzegTZ6I8btAAcAFINo1UFBEYgEiISDL-dJogBBaJYCAixqIfKhURkATPPbRULqM2NKDwNwhdoAN0YaCO6yG3EYOogABl8o6fDBwAAteYgQ6u8owPncQbSeDa3X6iKG5bCeSemAW0KaG1Te2O-Iut0e57e3X-sCB4NgMPJCMwZpRgixmNDGGMEMjJUcZ6TW2FhIQNBYejzWW4rU-gCSYHHlpg-cazSwaB6AFkQOOVms-ryswOCw7h6Px70s9xE7P5zFQsuIqv1_Mtzv2qtq_uIvHGkfIkP2nyCAxzLSlp11OcF3vS8mzXTdtyLD91meH8Ij_IoAPiICQMnRprwg29FwfLY4JfBDd0_FDpEscoZjKUJOF_MExwSRhcOPItR0_GCIEQEYSlCaZ3R4pBUEwXBHQQFB0GwfAYM7UJOyo7hxCofoXGOU5zi-CBihAAB3RIRnXLA3AuTtIJiR5JkQeAAGFihuKBoV1a4oGAYpNTOLwwAuI87RPdpdIMxJTPY2isDKSyiKzCzCMU-looGbk1KoKhNO87xihAozRlM8zEsI6zpFshynJciA3I8rztL80VMOy8dQrcL9-hSvl0pOTKvnAKoakyHI8gKAqWGiwQ3BAB4nm4WhoBgEs2FKxzkmc2gnXmKAkQbRAKjZNALniQUx3qGAJoeHkYE7dg4oXcQ2Gu-kHtGwjxDhSR5tdRlxGcNLuAAej-mAAFU3BhAglO4JbyvKKAFg8Hy6saCL6L7Sl0O4Fj2jYmDuAUy76TBNsVOS6gOph0LEDwEAjigC4Mu075iv-wHNXoeg4Ec-gDJgYAsGSYAgggb59OyjyYF1GBVlgJ1dSwZAgkeREYC6Rh5fBrJsm0Er7OW5yYbh2qj0FRg3FFhKWG0PYzPpnzviwKJEEEG6rOm3FXneT5XcpAKi15_mgnYxozvtnzQihlbtDWjajN2tF9sOoUTvtvBEHuHGOZNwMwUaYAYuziJgHgaD8-4ZJQiksTZIIQGSHz1DKXyGXgLVwTkmE_P6A17JVaCVv28pbhwE7nJDi6hnzOiJ34CZgfB7APrugG3J8myEbGDGjgSl1bRJ6KbKoXgcQUtn-vcXAPijnKPj1tHrTbYuGfZ-CwzjLGNfouPgfT8ac_qfKam2g20uI_AejU8C5RMmZZ20RP6Um_hEHAoQxBkEJhdOMnJ0Gk0EGQFKnU77eCOKDZgeAqjAVqjPcOes3gGwRkbLIpssDAHNowS2Js6Zj3vsnR2-NnoLhAaXN4Hwvjo1OpNEO4Aw463KlHFaMc9oHSOvQJODsMG4nUihVRbVSZpX0vkLm-ltCMDZgAUXWt0f00AujzAOq8YC-ATqELBqQ8RYBcGUO0OAA6nZuwgEQA4ohURnHaW5EAA)

**Comment by plainheart** [comment]
@wigsnes Set `invisible` of the draggable shadow circle to be `false`, you may see some interesting. You can follow that to try to find out the reason.
