### ISSUE TITLE
[Feature] support waffle chart

### ISSUE THREAD

**Issue by zirain** [apache/echarts#17261]
### What problem does this feature solve?

Is there any plan support waffle chart in echarts? https://datavizproject.com/data-type/percentage-grid/

### What does the proposed API look like?

NONE

**Comment by Ovilia** [comment]
We don't plan to create new chart types unless they are fequently required. Please follow the [custom series](https://echarts.apache.org/en/tutorial.html#Custom%20Series) tutorial to create the chart.

**Comment by zirain** [comment]
got it, thx!

**Comment by bala-27** [comment]
Pie charts dont really represent a good way to do an impactful storytelling
Waffle chart overcomes the story telling limitations of Pie charts and create strong impactful storylines.

Many chart libraries are adding waffle charts Eg:
https://nivo.rocks/waffle/
Apache eCharts is missing Waffle charts today. if Apache echarts is serious about creating components for impactful story lines., it needs waffle charts @OviliaZhang

**Comment by psarin** [comment]
Agree that waffle chart should be added to echarts

**Comment by murphydan** [comment]
Highcharts calls it an item chart, so you can change to a horizontal/parliamant/circle view, change the marker style, etc. to however you want it to look. On that linked page, it defaults to parliament, but you can play around with the options. Here's one we have, using Highcharts (hiding labels/titles because it is sensitive data)...

![Image](https://github.com/user-attachments/assets/b05048e5-6155-44cb-917a-1fa1b42afc7e)

What is nice with their implementation is that it resizes well. You don't have to set the grid size exactly, it just figures it out based on the size of the screen or space you give it and adjusts rows/columns accordingly. It is really easy to implement.
