### ISSUE TITLE
[Bug] Series symbol rotation is not respected in legends

### ISSUE THREAD

**Issue by MNHarshitha** [apache/echarts#17350]
### Version

5.3.0

### Link to Minimal Reproduction

https://codepen.io/Harshitha19/pen/RwMRxEd

### Steps to Reproduce

1. Create a scatter series with different symbols, symbolRotation, and enable legends.
2. Observe that series symbol rotation is not being inherited by the legends symbol.

### Current Behavior

Series symbol rotation is not inherited by the legends symbol.
![image](https://user-images.githubusercontent.com/97500674/178235543-8e31d32a-6a96-4944-87c0-7ddbc7e1c80d.png)

### Expected Behavior

Legends symbol should inherit the series symbol rotation.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by jiawulin001** [comment]
## Conclusion
Adding a method `getLegendIcon()` to scatterSeriesModel can solve this problem. Submitting a PR to solve this.

## Problem location
<details>
<summary>More info</summary>

Interesting enough, I've found that line series would not have such problem becasue of a judgement here:
https://github.com/apache/echarts/blob/add11459ee43a56f7ff5b300c76b3f801f59f3c6/src/component/legend/LegendView.ts#L371
Since the method `getLegendIcon()` exists only in `LineSeriesModel` and `MapSeries`, the judgement is not satisfied for scatter chart so the icons styles are not inheritated.
</details>

**Comment by RavalikaP** [comment]
Hi, This is something we are also looking for the solution. Can I get the status or any suggestions/ workaround in this regard would be much appreciated.
