### ISSUE TITLE
[Feature] Aspect Ratio support

### ISSUE THREAD

**Issue by Depact** [apache/echarts#17368]
### What problem does this feature solve?

Example of layout I'm trying of achieve:
<img src="https://user-images.githubusercontent.com/19435553/178685808-f1925d5b-80c6-4b50-b588-4859c8242169.png" height="400">

What I have now, with default settings:
<img src="https://user-images.githubusercontent.com/19435553/178684624-89ccce4a-5964-4124-86a6-b9256092f894.png" height="400">
Next row is invisible due to height of first. So I'm looking way to set aspect ratio, so charts will follow it when page resized, not taking way too much height, and different for mobile view.

### What does the proposed API look like?

Chart.js have it: https://www.chartjs.org/docs/latest/configuration/responsive.html
```JS
options: {          
   aspectRatio: 0.5, 
}
```

**Comment by efj5n8** [comment]
Aspect ratio would be excellent. I had to go in and mess about with containers and CSS code to get my image scale properly, which was somewhat annoying to do.

**Comment by plainheart** [comment]
Perhaps you can apply the native CSS property [`aspect-ratio`](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio) on the container of the chart.

**Comment by robertabenassi** [comment]
This point is quite critical for my applications.
I often need to get the axis scaled.
Plotly.js has something that let me do that:
https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-scaleanchor

Playing with aspect ratio, as a CSS properties may be useful when you have just one vertical axis, for example,
but I need to handle  two or more y-axis.

Please, would you mind to consider to introduce the feature?

**Comment by helgasoft** [comment]
I see two issues at stake here.
1) [aspect-ratio](https://developer.mozilla.org/en-US/docs/Web/CSS/aspect-ratio), as @plainheart said, is about the container of a chart. It works fine.
2) responsiveness of a grid of ECharts, as @Depact says - _"Next row is invisible due to height of first"_.
This could be solved with CSS tricks like ```flex-direction: column;```.

[This Demo](https://codepen.io/helgasoft/pen/abPbGOq) shows both working nicely together, despite **not** being related.
For Mobile view see [this doc](https://echarts.apache.org/en/tutorial.html#Responsive%20Mobile-End).
