### ISSUE TITLE
How do I include the labels of polar bar chart or pie chart dynamically in container. 'containLabel' property only works in case of line or bar charts but not in the case of Pie chart or Polar bar chart 

### ISSUE THREAD

**Issue by abdullahw099** [apache/echarts#17462]
### Version

5.3.2

### Steps to Reproduce

Created the Polar Bar Chart a
and can't use containLabel and grid properties in Circular charts

### Current Behavior

<img width="260" alt="issue" src="https://user-images.githubusercontent.com/92432664/182377101-dce78186-2205-4d55-8f84-c7a424001f48.png">

### Expected Behavior

Either labels are long or short, the chart size should be dynamically adjustable according to the labels size and container size

### Environment

```markdown
- OS: windows 11
- Browser: Chrome
- Framework: React Js
```

**Comment by Ovilia** [comment]
This is not a bug because unlike in Descartes coordinate where you set `left` and `right` values, in polar coordinate you set `radius` of the polar so it's from the inside and should never consider `containLabel` or not. 

I think you should use the max length of axis labels to change `polar.radius` dynamically.
