### ISSUE TITLE
[Bug] polar使用visualMap时，只有折线标记的图形颜色正常变化

### ISSUE THREAD

**Issue by suzuyong** [apache/echarts#17492]
### Version

5.3.3

### Steps to Reproduce

const data = [];
for (let i = 0; i <= 50; i++) {
  let theta = (i / 50) * 360;
  let r = 5 * (1 + Math.sin((theta / 180) * Math.PI));
  data.push([r, theta]);
}
option = {
  title: {
    text: 'Two Value-Axes in Polar'
  },
  legend: {
    data: ['line']
  },
  polar: {},
  tooltip: {
    trigger: 'axis',
    axisPointer: {
      type: 'cross'
    }
  },
  angleAxis: {
    type: 'value',
    startAngle: 0
  },
  radiusAxis: {},
  visualMap: {
        top: 50,
        right: 10,
        dimension: 0,
        pieces: [
          {
            gt: 0,
            lte: 2,
            color: '#93CE07'
          },
          {
            gt: 2,
            lte: 4,
            color: '#FBDB0F'
          },
          {
            gt: 4,
            lte: 6,
            color: '#FC7D02'
          },
          {
            gt: 6,
            lte: 8,
            color: '#FD0100'
          },
          {
            gt: 8,
            lte: 10,
            color: '#AA069F'
          },
          {
            gt: 10,
            color: '#AC3B2A'
          }
        ],
        outOfRange: {
          color: '#999'
        }
      },
  series: [
    {
      coordinateSystem: 'polar',
      name: 'line',
      type: 'line',
      data: data
    }
  ]
};

### Current Behavior

![line-polar](https://user-images.githubusercontent.com/38196997/183797582-f2f298d4-23c1-4152-8ade-82d58737b31e.png)

### Expected Behavior

折线和标记的图形颜色都能根据visualMap的设置正常变化。

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by Ovilia** [comment]
After diving into the code, I found that gradient color is [not supported](https://github.com/apache/echarts/blob/master/src/chart/line/LineView.ts#L270-L275) for polar lines and visualMaps use gradient to implement. It is not easy to support gradient for polar lines because linear gradient is tricky in the polar system so to intentionally not support it in the polar line series.

Although the visualMap for polar line series may not be implemented in a near future, you can follow #17138 to see if this requirement can be fulfilled with that issue.
