### ISSUE TITLE
[Bug] echarts map.series nameProperty is setted, but ti

### ISSUE THREAD

**Issue by zhangjinsong** [apache/echarts#18005]
### Version

5.4.0

### Link to Minimal Reproduction

https://codepen.io/pen?template=xxZzxZd

### Steps to Reproduce

1、i want to use adcode key to relate gejson wdth the data wither the default value 'name'. but it also the key of 'name'
 

### Current Behavior

1、i want to use adcode key to relate gejson wdth the data wither the default value 'name'. but it also the key of 'name'

### Expected Behavior

```js
{
    tooltip: {
        triggerOn: "click",
        formatter: function(e, t, n) {
            return .5 == e.value ? e.name + "：有疑似病例" : e.seriesName + "<br />" + e.name + "：" + e.value
        }
    },
    visualMap: {
        min: 0,
        max: 1000,
        left: 26,
        bottom: 40,
        showLabel: !0,
        text: ["高", "低"],
        pieces: [{
            gt: 100,
            label: "> 100 人",
            color: "#7f1100"
        }, {
            gte: 10,
            lte: 100,
            label: "10 - 100 人",
            color: "#ff5428"
        }, {
            gte: 1,
            lt: 10,
            label: "1 - 9 人",
            color: "#ff8c71"
        }, {
            gt: 0,
            lt: 1,
            label: "疑似",
            color: "#ffd768"
        }, {
            value: 0,
            color: "#ffffff"
        }],
        show: !0
    },
    geo: {
        map: "nw",
        roam: !1,
        scaleLimit: {
            min: 1,
            max: 2
        },
        zoom: 1.23,
        top: 120,
        label: {
            normal: {
                show: !0,
                fontSize: "14",
                color: "rgba(0,0,0,0.7)"
            }
        },
        itemStyle: {
            normal: {
                //shadowBlur: 50,
                //shadowColor: 'rgba(0, 0, 0, 0.2)',
                borderColor: "rgba(0, 0, 0, 0.2)"
            },
            emphasis: {
                areaColor: "#f2d5ad",
                shadowOffsetX: 0,
                shadowOffsetY: 0,
                borderWidth: 0
            }
        }
    },
    series: [{
        name: "确诊病例",
        type: "map",
        nameproperty: 'adcode',
        geoIndex: 0,
        data: dataList
    }]
}
```

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by plainheart** [comment]
It should be `nameProperty` rather than `nameproperty`.

**Comment by zhangjinsong** [comment]
now, if i want to resolve this problem that i should do something.

**Comment by zhangjinsong** [comment]
i same get answer for this problem, The reason for this problem is that even with the nameProperty property set, echarts still matches the data through the name attribute

**Comment by plainheart** [comment]
Thanks for your feedback! This should be a bug. We will fix it later.

**Comment by zhangjinsong** [comment]
how long?

**Comment by zhangjinsong** [comment]
do you have a plan

**Comment by pengxiaotian** [comment]
发现 指定了 geoIndex 之后, visualMap 不生效了?

**Comment by zhangjinsong** [comment]
这个问题是设置了nameProperty属性后，visuMap不生效，tooltip也出现。调试代码后发现是echarts还是以nameProperty: 'name'的默认name属性来对geoJson地图和数据进行匹配。

**Comment by plainheart** [comment]
由于 v5.4.1 正在发布过程中，已经列到 v5.5.0 的 milestone 了，可能还需比较久的时间，计划日期是在明年 2 月份初发布。

**Comment by pengxiaotian** [comment]
果然如此! 和我这个问题一样 #18008, 我是用了 nameMap, 就不生效了

**Comment by pengxiaotian** [comment]
> 

但我觉得这个bug 还挺严重的啊!

**Comment by zhangjinsong** [comment]
好的，我暂时使用了另外一种方法去处理了这个问题。期待这个问题的完整解决。

**Comment by helgasoft** [comment]
@zhangjinsong,   @plainheart - this not a bug.
[nameProperty](https://echarts.apache.org/en/option.html#series-map.nameProperty) is just a link from a geojson property to the [data name](https://echarts.apache.org/en/option.html#series-map.data.name). It works as intended - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbA5BHHAA5IAXAHphAY1yEEAKyS5GAG3wA3GAkLNhxCMIWoS6VEnz6tjVLP0BaYFD5WxEIlAACtpHEYxxTwlBlI-pwANOxsAGYAroRicCaEbKSOAFKBhORsAN5hHClpCOGMUHCRMIxIBagwAKJQjqThbAC8AHxZORwRCHwwqHxeceUIAFrDfsCMzV09fQP4Q-OMNJ2d4d29_fDzFYtThJEKCsudAL7kHaCQsIhO8th4RGRUHYyO1xVlxPgeXgCydqROI5gCE2Hl9M8VspYGxcMUoJhvnApgBtDocTJsRaCLiAfz1ADhygEB3UHQhSRRg4gAsCAAHABmNgnUIrDFYqATHGcXGAf0jAHcagHnTQBXgYBum0AXMokqBkilsOk0hAABkZzJZmOxXEA7raAdWVicE2KTyTiAOzUgCcSvRWTZHK4gFZYwB7ujq9ZKDWwAGwAVnd5pZlrVnEAiXLaiVSnHyhAAJhNAEZGR0ALo0Dp9OL6KbZH1xOAKaXpn1sJCRABGngAHnBOYsAAobAYgNjfCJERghC0cbPhctcGD4bRwTgWpkWuCoVAKOJ8HG5jPd4hMGCc_CeEHKn0oDAAEUUUBAoZXLLgMCghGMKcI69KxXioYjA73HGU30ikv-E_aebY7c74ddd86hdQvCoMAVLyr-HBrlgUCFooOIAISga2bClp2KKcIAG1mgpwgBy8pwcZgWwfDzGI5Q4mi74YohKzEJ2Ubygh5GdAoUEwVwbS0YqgBdci2DG5KOVScgAxIa4RRux_YMYODFTuR1HSrR-ErGOcl0QpjHMQonK0WwVhsOxbBcapvF6POXACeE4TupS4Y0uJ5GSeR0nvrJOJRoZH40fRPFMdBGlcDGOlmgZlGdGIfEmZwZnhDSYiGlGtnvvZ76OXm1G7sFbY0W53ksZwgCJroAPPLcTxoXGYJ5m4Iaro2cFiV5slPr6tKnkMSV_GmeZHXhPFeYnIheGIRBcHyreFpIF42ykYh9WdH61aoA-MTNqpcAgP0nK2HwRXvr07I4ge5K6gAXiOwHhrqxGEJ4JkoqJdIRoa366uGd1Rs9dImv1DEbZywJbXmjDAHw0DGEIb5eepk7pZ0g1ITA5JQ71EmqVWNbwDuXCjIsf0-nCcBQDiuMIkiiGIyycYdCcxwcJc0DwMgzAAPJ8KepDJvEkKxlQQA).

![image](https://github.com/apache/echarts/assets/13038071/d4c80a9f-96e5-42ad-ae14-a9758257c288)

The Minimal Reproduction code is defining ```data.adcode``` instead of ```data.name```, which is not supported.

**Comment by Ovilia** [comment]
> @zhangjinsong, @plainheart - this not a bug. [nameProperty](https://echarts.apache.org/en/option.html#series-map.nameProperty) is just a link from a geojson property to the [data name](https://echarts.apache.org/en/option.html#series-map.data.name). It works as intended - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-usa&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZynUAEbA5BHHAA5IAXAHphAY1yEEAKyS5GAG3wA3GAkLNhxCMIWoS6VEnz6tjVLP0BaYFD5WxEIlAACtpHEYxxTwlBlI-pwANOxsAGYAroRicCaEbKSOAFKBhORsAN5hHClpCOGMUHCRMIxIBagwAKJQjqThbAC8AHxZORwRCHwwqHxeceUIAFrDfsCMzV09fQP4Q-OMNJ2d4d29_fDzFYtThJEKCsudAL7kHaCQsIhO8th4RGRUHYyO1xVlxPgeXgCydqROI5gCE2Hl9M8VspYGxcMUoJhvnApgBtDocTJsRaCLiAfz1ADhygEB3UHQhSRRg4gAsCAAHABmNgnUIrDFYqATHGcXGAf0jAHcagHnTQBXgYBum0AXMokqBkilsOk0hAABkZzJZmOxXEA7raAdWVicE2KTyTiAOzUgCcSvRWTZHK4gFZYwB7ujq9ZKDWwAGwAVnd5pZlrVnEAiXLaiVSnHyhAAJhNAEZGR0ALo0Dp9OL6KbZH1xOAKaXpn1sJCRABGngAHnBOYsAAobAYgNjfCJERghC0cbPhctcGD4bRwTgWpkWuCoVAKOJ8HG5jPd4hMGCc_CeEHKn0oDAAEUUUBAoZXLLgMCghGMKcI69KxXioYjA73HGU30ikv-E_aebY7c74ddd86hdQvCoMAVLyr-HBrlgUCFooOIAISga2bClp2KKcIAG1mgpwgBy8pwcZgWwfDzGI5Q4mi74YohKzEJ2Ubygh5GdAoUEwVwbS0YqgBdci2DG5KOVScgAxIa4RRux_YMYODFTuR1HSrR-ErGOcl0QpjHMQonK0WwVhsOxbBcapvF6POXACeE4TupS4Y0uJ5GSeR0nvrJOJRoZH40fRPFMdBGlcDGOlmgZlGdGIfEmZwZnhDSYiGlGtnvvZ76OXm1G7sFbY0W53ksZwgCJroAPPLcTxoXGYJ5m4Iaro2cFiV5slPr6tKnkMSV_GmeZHXhPFeYnIheGIRBcHyreFpIF42ykYh9WdH61aoA-MTNqpcAgP0nK2HwRXvr07I4ge5K6gAXiOwHhrqxGEJ4JkoqJdIRoa366uGd1Rs9dImv1DEbZywJbXmjDAHw0DGEIb5eepk7pZ0g1ITA5JQ71EmqVWNbwDuXCjIsf0-nCcBQDiuMIkiiGIyycYdCcxwcJc0DwMgzAAPJ8KepDJvEkKxlQQA).
> 
> ![image](https://private-user-images.githubusercontent.com/13038071/292583807-d4c80a9f-96e5-42ad-ae14-a9758257c288.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUzMjcxNzEsIm5iZiI6MTcxNTMyNjg3MSwicGF0aCI6Ii8xMzAzODA3MS8yOTI1ODM4MDctZDRjODBhOWYtOTZlNS00MmFkLWFlMTQtYTk3NTgyNTdjMjg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEwVDA3NDExMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkN2VkN2NkNDQwY2E1YmVmNTI1ZGE3ZWY0YjI1MmZjMjdkMTU3MzIyY2EyNDFlM2RiYmNlMzYyMjFiMjViMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nQsXkglFYZoaCfOmlRTn7n-8Gaom0H_Uo3kGAws05ug)
> 
> The Minimal Reproduction code is defining `data.adcode` instead of `data.name`, which is not supported.

Thank you @helgasoft . You really helped a lot to this project!
