### ISSUE TITLE
 series-map 指定了geoIndex 之后 visualMap 就失效了

### ISSUE THREAD

**Issue by pengxiaotian** [apache/echarts#18008]
### Version

5.4

### Link to Minimal Reproduction

https://echarts.apache.org/examples/zh/editor.html?c=map-HK

### Steps to Reproduce

```js
myChart.showLoading();
$.get(ROOT_PATH + '/data/asset/geo/HK.json', function (geoJson) {
  myChart.hideLoading();
  echarts.registerMap('HK', geoJson);
  myChart.setOption(
    (option = {
      title: {
        text: 'Population Density of Hong Kong （2011）',
        subtext: 'Data from Wikipedia',
        sublink:
          'http://zh.wikipedia.org/wiki/%E9%A6%99%E6%B8%AF%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83#cite_note-12'
      },
      tooltip: {
        trigger: 'item',
        formatter: '{b}<br/>{c} (p / km2)'
      },
      toolbox: {
        show: true,
        orient: 'vertical',
        left: 'right',
        top: 'center',
        feature: {
          dataView: { readOnly: false },
          restore: {},
          saveAsImage: {}
        }
      },
      visualMap: {
        min: 800,
        max: 50000,
        seriesIndex: 0,
        text: ['High', 'Low'],
        realtime: false,
        calculable: true,
        dimension: 'value',
        // inRange: {
        //   color: ['lightskyblue', 'yellow', 'orangered']
        // }
      },
      geo: {
        map: 'HK',
        label: {
          show: true
        },
        itemStyle: {
          normal: {
            borderColor: '#ccc',
            borderWidth: 1
          },
          emphasis: {
            areaColor: '#f60'
          }
        },
      },
      series: [
        {
          name: '香港18区人口密度',
          type: 'map',
          geoIndex: 0,
          zlevel: 0,
          colorBy: 'data',
          data: [
            { name: '中西区', value: 20057.34 },
            { name: '湾仔', value: 15477.48 },
            { name: '东区', value: 31686.1 },
            { name: '南区', value: 6992.6 },
            { name: '油尖旺', value: 44045.49 },
            { name: '深水埗', value: 40689.64 },
            { name: '九龙城', value: 37659.78 },
            { name: '黄大仙', value: 45180.97 },
            { name: '观塘', value: 55204.26 },
            { name: '葵青', value: 21900.9 },
            { name: '荃湾', value: 4918.26 },
            { name: '屯门', value: 5881.84 },
            { name: '元朗', value: 4178.01 },
            { 
              name: '北区',
              value: 2227.92,
              itemStyle: {
                normal: {
                  color: '#ccc',
                  borderColor: '#ccc',
                  borderWidth: 1
                },
                emphasis: {
                  areaColor: '#f60'
                }
              }
            },
            { name: '大埔', value: 2180.98 },
            { name: '沙田', value: 9172.94 },
            { name: '西贡', value: 3368 },
            { name: '离岛', value: 806.98 }
          ],
          // 自定义名称映射
          nameMap: {
            'Central and Western': '中西区',
            Eastern: '东区',
            Islands: '离岛',
            'Kowloon City': '九龙城',
            'Kwai Tsing': '葵青',
            'Kwun Tong': '观塘',
            North: '北区',
            'Sai Kung': '西贡',
            'Sha Tin': '沙田',
            'Sham Shui Po': '深水埗',
            Southern: '南区',
            'Tai Po': '大埔',
            'Tsuen Wan': '荃湾',
            'Tuen Mun': '屯门',
            'Wan Chai': '湾仔',
            'Wong Tai Sin': '黄大仙',
            'Yau Tsim Mong': '油尖旺',
            'Yuen Long': '元朗'
          }
        }
      ]
    })
  );
});
```

### Current Behavior

整个地图都是一个颜色

### Expected Behavior

visualMap 可以生效

### Environment

```markdown
Chrome
```

**Comment by pengxiaotian** [comment]
文档上有写: 
https://echarts.apache.org/zh/option.html#series-map.geoIndex

**Comment by helgasoft** [comment]
Short answer looking at your code:  
If you want to just change map's **itemStyle**, you can do it inside the _map series_ instead of _geo_.

The longer explanation:  
Open [this code](https://echarts.apache.org/examples/en/editor.html?c=map-HK&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QzhAaQQArJKkJSANKIBmAV0IBjOPmOjSmgFJHC5UQG9qo0aCQsIgQ-LiM2HhEZFR-ooy20PBICDCMxPhIcIwwALJQAA6kUrpmom4esf6BSYhqcOwFDsakcf6kqE2OhKIAvD5t_qIOcAA2jABcA0Mzw4wAHnBTUnydVqMK3aIAIoyESPhwIKKoFqLCxsSiOpeigBD_AEwADACML4CQ_2aDM0hWAEbZRbLbYKKCWGCoYCiADq-AA1vgCowCFAvrMhr8_qMiHCJt9ZlIIHA4AUJjIZAAvCAIdDwxHI_BQBCoGDEGS0hEyACkAFEAJxcgQANi5fIFPJFACEAByCgBivNlAheXOlYF5Ir5ABYuZKFTyAKyq7aqp68o3SgSqgDMAGJbIdGDxCKhsgBaF4PKT4gC-pnxcFQqFGDlJ03Rwxg-GITBgy0dwDREYsLOACmycek3j-PoAPH8YDIAHzeWw-5wFUQyURw4APcje9F-gNB0Z_VDzKa-COiFAYKZwGBWRj-nss_B7JbSABuOQctigoyT6PGFinUijxCJy9mgbDUlsk5yO5mFkYCisaS7-Jm8kUADUJ-gu6I0nh2IRRiAphZF2pRM2Pb-GkWQspMPiAUBSBQLOAhIAAkmmTBdj6N4Ab6o6zNOmRWIu-Rht2EbAEQUzSk8TyYeiaadqIBrkeRlG7gsU4ANolNGEBlFI2DoFIAC6jEzG-Ib4MA4G_qMaiCUMC6jLY6xQFi4GDsO0n-GoUaMAhhDhDRFFVtWtjBiyASFG6GkTicn4gGhRCsFAJDgYRPZGaMLJTGx2JbnASBwiAWLDlxICMKMbm8eYUgsg5sbIvxaGoU20nkqIBDQUp0iaFIoh_McaQFBsDokKItJwBA0jzJl5hIAuxI5L2OSWbSoXZYwohENhBxKfimjXj2ab7qUamiBsfwhS-vZoM-kbDgBQ0JgAykc4y9UBjDAAU0AHEgL6wOeYDGZmUi2hYQpPFlCURpBMxXRiDVaR5aHORGRxIss_VlP1yyDa-ODAAOQ4jmh_jkpo8E6QsUz6UMyX4GceyKeMuDmKVmT1ZpxX4M1o1tYQHX4F1QHDYpY0-Opk3_TNN3oneUAPYT_jeKIhBQGJyyALRygD-kYAXMplNOi7DlMzxPAaADsCDWlqs1A0MjPM6z0iAH52gArcrz_PgS8BpaiLYtatKUv06TcvgVIgA4cjz5h86MAuiNaLxCtKQoIC8-v07LLPG4A6srm6IlvW0KYoPAgQou4Tbvy1IgCdNoAaDqAF-mqtW-BWpak8WoGggWp8iHQFh8bgCPtoALDaAOvq8fW8n9t8kHktUxGOfLIAunKAJn5gBz6iX4HWiLQoGhXIt69X6K19IgAjeYA5JqAJtyrdTKnLxkQgfIi1nPYD1IgBDkYAGhoT7RBrPFqCAPMHfezEvgCuIYASukbw8Lx8uRs8LzXTPu8sgDCwQrG8Z9Pu_70NMxL4A9jqABepG8DTSmlC8BA0oq5fxlvfcOgBhRUAOjmr8Xg9wQK8W-_doHG0AOjK3tfbgQePgsWfIHhoMPhg5Yw9AAr6ufaeTxZ690gQzMh0hACZNoABlcN58iQYHbUJDv5MKkBzQAhLEb2tNae2vCoFG2WIAbs9ADZOhvMijs-S92lgJaWRt8IrUJlIMAk4YCLlEA5XAMItIZhMOzbmJ4Iw8hUGY5YZsrHongkgDYOltrSDkY4gkNx0BuScGAQ4IApD12bl4mYUgdDoCgPgUQXADgkGCdIU-YShgRPQDYWJlxEkr3Xgw0QAA5FkpVljYJSf4KQ81onXBsMQbJQiynSHmtAWJRBslsIaRU6AUImlWBiasbJBdi55PmqgKwpUciEGWF7DpXAqn9PIVQvJUg4nDh6NCBy2Tn4zNWaIXINhsn_w6esnoQR8DZOVkc24syYnzVacsEe48lkAE0oBWFiQcKEuQsnLGjnHZ5OzsAJOWPAxsQED4HyeuiF6xtqrpmPOYIyLICDM2yPNEAWQ1rLEqqZAaOgUlIBAMAdsoxbkUjbtacwC0lpOVcu5DcsUD7-Bph5Fibwd522lA8aUfJzD4N3h3B41oHgCVEKyl4O9BXShFlrXlgctRCs4SLPiog-LxXxKq665A4ixB9FQIAA) and do the following experiments:
  - hit {Run} - both series are visible. Grab a region and drag aside, the **geo map** for the scatter series shows underneath
  - disable 'geo' by replacing with 'xgeo', {Run}, the scatter serie becomes invisible (it relies on the geo map)
  - do the opposite: revert back to 'geo', uncomment line 'geoIndex: 0', {Run}, now the **map serie** becomes invisible. The **geo map** is visible but cannot be colored since it has no data.

**Conclusion** from experiments:  
Visualmap-colored series type _map_ should not be linked to _geoIndex_. Both act as separate maps on their own.
