### ISSUE TITLE
"time" scale axis but ordered by "dataset". Is this possible somehow?

### ISSUE THREAD

**Issue by andresgutgon** [apache/echarts#18071]
### Version

5.3.3

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-playground-forked-ulq2zv

### Steps to Reproduce

In the codesandbox is the code. You can see there are 2 charts. All the same. The only difference is:

### First chart has in `xAxis` type of `time`
![image](https://user-images.githubusercontent.com/49499/208062931-6885dfb6-5855-437d-a857-8fb8c7a4dc5d.png)
☝️ with `time` we lost sorting of data

### Second chart has in `yAxis` type of `category`
![image](https://user-images.githubusercontent.com/49499/208062980-c092ef58-b8de-46c8-9f95-1418618d4b90.png)
☝️ with `category` we lost axis formatting as time and time scale nice spacing (Look that nice `Dec` month in first chart).

If you check the small dataset you'll see it's ordered in `ASC` order.

```
const dataset = [
  ["date", "amount"],
  ["2022-11-01", "1"],
  ["2022-11-02", "2"],
  ["2022-11-05", "3"],
  ["2022-11-13", "4"],
  ["2022-11-20", "5"],
  ["2022-12-07", "6"],
  ["2022-12-04", "7"],
  ["2022-11-10", "8"],
  ["2022-12-15", "9"],
  ["2022-12-24", "10"]
];
```

### Current Behavior

First chart where `xAxis` is of type `time` the order of the dataset is not respected.

### Expected Behavior

I'm not sure if this is possible or even expected but I would love to be able to have the nice work Echarts does with `time` scale axis formatting and deciding the right amount of ticks based on volume but respecting the order of the dataset. 

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

What I would want is to have a time series axis with formatting and tick spacing but the order would be mark by dataset.

**Comment by helgasoft** [comment]
This is by design. 
When xAxis is _type='time'_,  **X axis values** are sorted automatically b/c they need to be in (time) order.
 &nbsp; Result: "2022-12-07" shows after "2022-12-04" correctly.
When xAxis is _type='category'_, order does not matter and **X axis values** appear as they are in the dataset.
 &nbsp; Result: "2022-12-07" shows **before** "2022-12-04", which is incorrect.
**Y values** ('amount') show always in their original dataset sequence. That's why after sorting the dataset with ```source: dataset.sort()```, we get a different polyline, even though the individual values remain the same.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygiBTWBeGBtAUDHAIkSlUIBoZCEBbEAVzCkIF1z8iAmABk84FoAjIP7dBFKuLYdshHnyEjeEua3YFZ8gcNEBWFQGY1Mub20jBRyoQAsxjaYU6eK_dIdahA7gHYVANnsuMy9RO2s_d2CnC24VAA4gzRDBbX1rAE4kx20BTnDJOJZcFgBuXBAABygAS3AYLABvDgAPAEEWmogALhhmggIAekGoAE9K1F6AcmAkVABzEAAnUan1AbGJ6dqaVDWOAF910Y6u3sajjhIUdF68Ab6YCAYl4En4JBuoADpnpagABQAShgBw4UTQSxqqB6OEem3ehAANjUwGRQTBigdSkA)
![image](https://user-images.githubusercontent.com/13038071/208284829-4ebb6e55-e565-4a7c-8ba1-de0263b07974.png)

**Comment by andresgutgon** [comment]
> This is by design.

That was my suspicion. 

My question is if it's possible to get the benefits of `time` scale [cascading automatic formatted time based](https://echarts.apache.org/en/option.html#yAxis.axisLabel.formatter) without enforced time sorting on X axes

**Comment by helgasoft** [comment]
But _"[Cascading Templates](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter:~:text=formed%20in%20Function-,Cascading%20Templates,-%3A%20to%20adopt%20different): to adopt different formatters for different time granularity"_ - is just 'makeup' (formatting) of the values, it does not affect the axis-values order.

If you want **"without enforced time sorting on X axes"**, the answer is already in your example - use _xAxis type='category'_.
Could you provide a **desired** output chart to clarify your goal ?

**Comment by andresgutgon** [comment]
So I guess my question is how I can use cascading templates on a `category` type axis?

**Comment by helgasoft** [comment]
In fact [Cascading Templates](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter:~:text=formed%20in%20Function-,Cascading%20Templates,-%3A%20to%20adopt%20different) are for _time_ type axis only.
For _category_ type axis one could use [Callback Functions](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter:~:text=like%20%27Day%202%27-,Callback%20Functions,-Callback%20functions%20can) formatting.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAJgQygiBTWBeGBtAUDHAIkSlUIBoZCEBbEAVzCkIF1z8iAmABk84FoAjIP7dBFKuLYdshHnyEjeEua3YFZ8gcNEBWFQGY1Mub20jBRyoQAsxjaYU6eK_dIdahA7gHYVANnsuMy9RO2s_d2CnC24VAA4gzRDBbX1rAE4kx20BTnDJOJZcFgBuXBAABygAS3AYLABvGA4oEBAAG1rKgC5GgF91GAAPAEFhmogemEaOAgB6eagAT0rUaYByWppUDaGCFbXN4CRUAHMQACdlvbmYBAmIABkEACNUDunmu4IAMyuaEhSJdpr9GMBavUABQANwQHXoqAAlDMfgQYHQGjgNoI9htOHiDHibHjdHj_HifHj4niMniAPIQvEAORAMLxABFUMANmU0QQ4Zd4KcsWBUAB3GAc06w-GIgDUGwAKtxuD1VeruBskeV0XqYIKYKRhlAIFjsHRsCRUAA6M7oACy4CgAAsoUi2MLSHb0NLSO6-fr0Zd0PRLmAjagTRAbQArEA1MBQjY27W6_WDO79DiZgjLcaTL65r0odDTPB65oQBiXYDrEtoKD9GCLG3Vy5Qd0wbMEKJoS41VBTHAzI2reuEDqJsjdmDFfqlIA)
![image](https://user-images.githubusercontent.com/13038071/208488445-30f4b49f-7395-4284-b2a9-efa971910364.png)

**Comment by andresgutgon** [comment]
I know I can use a callback function. I was asking for a way of using cascading templates without reimplementing it myself : ) . Thanks anyway
