### ISSUE TITLE
using dataset + encode.itemGroupID  doesnt seem te work for Drilldown pie chart

### ISSUE THREAD

**Issue by slindersAmsterdam** [apache/echarts#18201]
### Version

52.2

### Steps to Reproduce

The drilldown function doesnt work with encode. When 'data' gets activated, it does work.

---

var container = document.getElementById('main');
var chart = echarts.init(container);

const RV = [['met', 52],['zonder', 14]];
const RA = [['met', 6], ['zonder', 10]];
const GL = [['met', 6], ['zonder', 1]];
const vri = [   ['RV', 5, 'A'],   ['RA', 2,  'B'],   ['GL', 40,  'C'] ];

chart.setOption({
  tooltip: {trigger: 'item'},
  dataset: [
    {
      dimensions: ['status', 'waarde', 'groupId'],
      source: vri
    }
  ],

  series: [
    {
      label: {show: false},
      emphasis: {label: {show: true,fontSize: 40, fontWeight: 'bold'}
      },
      type: 'pie',
      radius: ['35%', '65%'],
      center: ['50%', '55%'],
      id: "vri",
//----- itemgroupID doesn't seem to work in encode, drilldownfunction does not work
      encode: {
        itemName: 'status',
        value: 'waarde',
        tooltip: ['status', 'waarde','groupId'],
        itemGroupID: 'groupId',
      },

//----- groupID directly in data does work, drilldownfunction is active      
// data: [
//       { value: 5, groupId: 'A', name: 'RV' },
//       {value: 2, groupId: 'B', name: 'RA'},
//       {value: 40, groupId: 'C', name: 'GL'}]
    
    },]}
  
);

const drilldownData = [
  { dataGroupId: 'A', data: RV},
  { dataGroupId: 'B', data: RA},
  { dataGroupId: 'C', data:GL}
];

mychart.on("click", function (event) {
  console.log(event)
  if (event.data) {
    var subData = drilldownData.find(function (data) {
      return data.dataGroupId === event.data.groupId;
    });
    if (!subData) {
      return;
    }
    myChart.setOption({
      series: {
        type: "pie",
        radius: ['35%', '65%'],
        center: ['50%', '55%'],
        id: "test",
        dataGroupId: subData.dataGroupId,
        data: subData.data.map(function (item) {
          return {
            value: item[1],
            groupId: item[0],
            name: item[0],
          };
        }),
        universalTransition: {
          enabled: true,
          divideShape: "clone",
        },
      },
      graphic: [
        {
          type: "text", left: 50, top: 20,
          style: {text: "terug",fontSize: 18},
          onclick: function () {myChart.setOption(option, true);
          },
        },
      ],
    });}
});
// return option

### Current Behavior

The drilldown function for this pie works when groupid is included directly in data:

      data: [
       {value: 5, groupId: 'A', name: 'RV' },
       {value: 2, groupId: 'B', name: 'RA'},
       {value: 40, groupId: 'C', name: 'GL'}]

It doesnt seem to work when dataset is used (instead of data) and groupId is included in encode:

      encode: {
        itemName: 'status',
        value: 'waarde',
        tooltip: ['status', 'waarde','groupId'],
        itemGroupID: 'groupId',
      },

### Expected Behavior

The drilldown function should work based on a dataset.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

I copied the code to codepen but I get an error:
'ReferenceError: mychart is not defined'
https://codepen.io/slindersAmsterdam/pen/yLqpbLX

**Comment by helgasoft** [comment]
It works - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBASgNRgXhgbTQcgLYFMqYA0MArAEwC6hWAXuACa4BORMAjACwUUDcAsAChQkWHACCKdFjwFiANirpMdMIxbE2ABm78h4aDADiAGUkYc-VguK0GzVmx2DhBgG5MAlmaWJWJYphimIowPkHEZMQwmABCwVFKJqwcmlGYAMLBMLyCgiAADlAe4JIA3oKhUCAgADZF-QBcMKVQngDmbcxNmB5QuNiYAL6EFTD0AIZQ4xD4TWijoeUCoStjHniQxZBzmNCTAK4QrJgA7uPjTIzHbUwg-_kAkvTxCysQd0zAuE3uHq-DoyooxmnlwEDmS1WAHooTVxgAjXA1JqlCAACxAJyaADNxjUZsNXv18mjph5wc0YHDEcjmujMU1WvtcIRseAoABlDw0b4wFLENlgKAAdVwHjaaKg3XhtWegxghOWKygAE98rzMPkPLgiK8mON6B5DjsAMwkACkxzkFpeStCXyFXSUJE0loCJBtQLtMFwYFAjBRr1CvX6ADlxnhunsoIddd7Qq48czumcLlcRvGYCHsIZbvcHgARKNTGNHBIwzA3O6PZ5ZiAwMAgWCuckeeE1XAoVCNmDYEBMEkeMBtIMwKq1eo7aOxgKpy46gJV_PPL2rRWrfZgDyuZgQPEAFX1myK4EDmd9CI79EZTGZGdWoUNLcYHNJ6qj-RqvUw_3vCtXMDjFu2CTFsBb7PqJ5gAAqvkEx9E0bAuqkgiDLozj6LA9CeDUNT0JiYAFpM4xmKMpRjMRubVk83S-MQ8HjE0iDrpSDFUcutHhBRUxMWILHkWxeY1t0ST0cRTQmACAg5AIgjYCq6SkkwUAAHTgAAFAARMAX7AAA1ppAqbsAUEwOpuA7kKACUzSjB42JmRZvqqWAEa4DZkIrImTAwBA-zwkRUySNhHi4fhJyEcRKnYkO9DqdixmmepDEeaOTD4BBYDceMKmCdR9BdqgTlCiprl4Loa5WRVKz2WZACEfkBcRqWZulMZMGA1WhFJqzyYpFyqTMUAAPKFFs6measILahSk0Pqq74wJpWq4IZMD6oaxpKEhbrRGalqKA6fRMDsLq7ZgHoHX-D7Zexwm-f5gU5Xly7XQ-DFNI1T25VFIH5PFiVbGZ2YtTdqxtZltmZjdZW8tmaDaG9YMwImNTJlmfTYGgjhIw-aGjt1Vm46Em7bruB5HhAvRbGeyOhBe7a4NeY63iyBMrE-Hgvm-vKaRAn69IZ7MsWuuM3OMg7AHM7NzTdC2830AAeUBrR22JSqQqRjgUTRkCh0NvKqHYokrGuaTE4z6WtgqctyvJsAAHCLYPgDpHj6TigMlOpHkwOzvUKUpg34KNUHqQUUHEEy7ldWDzui6OAHdX73pVaMUmDFVQA)
Another option is to use a **dataset** instead of _drilldownData_ - take a look at "all datasets" example code in #18197.

**Comment by slindersAmsterdam** [comment]
Thanks a lot!

**Comment by slindersAmsterdam** [comment]
Thanks for the tip on the 'all datasets'. It works. 
I tried to add an extra filter on an extra column. But without effect.
For the example I use a fixed value for this second filter. 
 
The wanted outcome should give 2 values on a drilldown based on filter 1 (id) and filter 2 (fixed value). But filter 2 seems to have no effect, so I still get 4 values on the drilldown.

https://codepen.io/slindersAmsterdam/pen/OJwvLaM

**Comment by helgasoft** [comment]
You were very close to the solution. Take a look at [piped trasformations](https://echarts.apache.org/en/tutorial.html#Data%20Transform:~:text=Advanced%20usage-,Piped%20transform,-There%20is%20a).
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=bar-drilldown&code=MYewdgzgLgBAbgJwJYwLwwNoFgBQNMDkASgGoEA0MArJcWQLrm74bECCFMATLUR480IkAypwAsABloiC9XPQDcuXCAAOUJODQwA3oKggQAGw2qAXLphRkAcxsBTBBYJIo9gLYEYAXyZ4YACYAhlBBEPZQFtj--Hox-IFI7vaQmpBRBNAhAK4QnAQA7kFBCAH2-TYIINmqAJIBsn4JCRDVCMD2FohIgvjeggL-QWBJIWkAItkIY-AAqqrBbhZUElKC4cj2EFG9urv4HqoAFmFI25ZGQQBG9kYWOjAQRyAFFtbZ9pQAZuBQwkgAL06MEk31-AHV7EgbEdIjACFdjA0fD4ms0rABPVTAgiqJDlNHNaYBJC5DIAZioAFJ8gA2amNfYwDpgNxOQgrGm0KgMwbomApUBle5M_CuDwAOSCyWclWqdQahPRcCCRg-ziKJTKFFFMHF7gA4lUarVxrLjQrOLqDMZTBkslBcvlNaUCfC5SaGnJ4n0lfhsiM4I4IKqACrTVIacAin0JFLXIz2AJvBAfP0JElwJBlYQnbHOCCqIyuAhM_rxcv4b3eJQ4XCgSCwDb4iDaaIsAhuaAARiCnG7PHhpHyX2AEiojP8rC7UG7V37UiHZFoo_Hk47M64fco3d4y_hq9p68Im_nlFpe5HY6PfJPW1n2-4vA4K7HE9v0_vc_75OfV7XH6dveW79ruQ4vge17Hp-0BcGeMDdhe4H_jeaIwQ-_ZiNIoivgBaFAT28EAOzYf-774Zuj6DgQMi4ahgjoXBnC_vCtGQRIN7yLWuCJrAwBTAgKRQOMIRBEa8r1AAYkgJiONoABE8m1rxzICUJbDDIgxQ2FcVRgNJskIApSnKDgDbQIEyBGEYImhOEsDoNEcT4CSySpOA5ysB6lq0CqapugQixiRa9T5MUYBaUEOl6cerRTB0FjNlsuC-LgzkwPJ1jDBAPwIO48k7P4DyZVi9gFRlXwyWy8npvJDaVTY5Xpfy8muSkEBpOVrWieJno1bq8l-R85X8QggmsrZwUSQEBlsmWgipUVGVQKVXWVYZ_WxnV4ANU1A1te5YBdeFkXReAm38vgg2qsNFijeNUAaRF0xRbp4CzY46aVj4AwpYopnuBiADCJwIFAAB04AABQEMAxbAAA1pwXwBsAUZgDAUP2EGrIAJR7P4SBfJj2NCeDYDSvY-PNapY1CZNvUKh9RnoKTrLk5TtbNPd6maS9Z36VVcnoAQq4TlzGZWTZon2Rg3b0ODWWQLl7gYBICv1dC4NDfY2g8xNPUhTNQsIBLLlS5Nsvy4rEY5SAeVyxrO1azretqayT2nW9guGQozS7IDIMlBD9kAPLqGkUM0y5MsRBYAQW7HUDpkl5zRwkK35vCeIErqxKkp5BDdgytCUjSt78iybIZJy-Q8uX6Yx3ZES1GAZQAB4WLuuqCiAwqWBTMowIuOtd5Q-qM_UzhBZPyKLZdMABkgQYICGRjhtlrhpDGC8HBTVyJsmVipp8uoucv2b2LmQRZ5kRYlrq33NPP6KVDfRxIMAhUL-nzSZzibh25QB1LGZoiYvhwhWI3DOagLBcDWKAloK1Ew713vgQBcICAACEgiIxAWg_APxWT_CBF3AAHGfVElDwBw0_gjCwKMwBozSJjamlD8CB1BiHCI4d0ZQzUOjSg7wqZ-0oU_dE4iqy7G8LjCW5YZEKCAA)
![image](https://user-images.githubusercontent.com/13038071/214225467-f21ab27c-3586-4fff-ba05-b31f1aa8088f.png)
