### ISSUE TITLE
[Bug] Colour assigned to scatters change when toggling legend

### ISSUE THREAD

**Issue by jpmonette** [apache/echarts#18237]
### Version

5.3.2

### Link to Minimal Reproduction

https://jsfiddle.net/x0yq5gdc/

### Steps to Reproduce

1. Click on `Milwaukee WI` in the legend

Colors in the legend stay the same, but colours on the chart are now out of sync.

### Current Behavior

Colours of points on the map change, but the legend stays the same.

### Expected Behavior

All the colours should stay the same, no matter if some items are toggled on/off.

**Comment by helgasoft** [comment]
Culprit is ```"colorBy": "data"```.  Fixed in [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=map-bar-morph&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzGU1QyAqgGUBCAFZJUhKQBpRAMwCuhAMZx8p0aRtIoAKROFyogN7UoqKgkLCIEPi4jNh4RGRUQaKM9tDwSAgwjMT4SHCMMACyUAAOpFJ6Ahai7l4-loHBwQIANioA1lAAXAFJTaIyMqKAUUaA_GmAk0aA9aaABUqA356ADEqAcf6Av2qA3HKA5JqAYmmAZ7qA0HKAnaZ9TS2MVnA9ALQAjADMV-ZHwXCoJT0ATACsD_3B6FFwEB6Vw-RwAvt8msIoOgoPh8D1Gj8TmdLlcrgAGCH9Z6vURvAAcWKaf1wAJ6IP64KOUj4NgKz1ErHw9lQUgRjwGQ0ARzaALE1AHN5gBAVDnI86iC4AdgAbESni93tKOSSyXiwUlQYkki8nC4ALy9YKadn9YClHoAIkqZqJhCgwEYxVxZoAWvgSqIGVwCjB8M8YCArUcYDhgD04DA6UTBu7UKgWk5cf5RCgMD0rFAWmpRFT-j7GMBdHAQCcjT9YIwoGBY6gYOaWvhiBA4MQYFB_TLRAAjavRGCVlrV83N1sBylEvMlaBIXIl_oEDwdk64UPhxhgiHZ6Ox-MIjcnJiEJcBDcyABULP7NdEAG1qQBiG7igRvAAiVSJUnvbzAHwAogBOCw70lcUf3RH8bkA_oPz_AAxH9JQAIXxSCmg_GCYOfBCPjAFDgg_KwrD_KxxSsXDpFvKwO3FN4_wg99b1AyU3gEH8yI_eC_3RZ8rjY29GHFDt7CsOi7z_XA_0lKwPl4_EH3xH831ExD0JgqRRAAXUsKN7HcZ5gFEEp02YfImhPGQkjUb1GCQHor0RYIzRtO0zXNQp8BaGEbHaRhGFEAB1ABJEcmjNQsSkYFzRDNJB7AUfIYGChyWW7IgFEYXQQDyPNIrNTREs5M1z2rBD_XNeRFHys1yqgSK7I5RzbQi1z3M87zfMC_KHKQEBgC7FpdHwAAvJq8S-eqADd0zpWqLnxfEEHRB8ABZJT_N5LCWm4Fo-cU_z_D4PnUsEjuCcF9RCpyRrNZ8wBkAA1fAYByQh8BqolQpAcKcpiuKCkq5KYAIG18gyrLgByvLIxkQqqxgEqcuqyrEds-yLsanKbvux7ntezqou63rYwG4bIslBUfiiyaWmm2yJXFBb8RW4F1tEG55vxWj8WAt4TqaUFebO1GGuc81sBsXJxvck5RAAaQATUqsKrp-uB4v-mNAdSkHMvycHB0YVB8sGGGL3hsqFDeo4qot2rUYcy6crFiWpd8-W8einq-uJkabiW9szSpmnr1mj4EHxK5JXxD4rnFSw2YQK45r2iPedOgWGith3zQAOUYdBRHYGATigQgkFETABEVz7ldi1W_vegGgbS0HdYhg2kZtlH6qzqLc_zwvi9L8vK_9gmvaGkbxT9iappGq8Lk4hPGfFK59rj9EFtWj4bj_VOs3T877fR80ENQPIXEKEeraV77a7VhuNab7Wwbbw33uR687ainuzVP8_CFEJfd2Y8iYT0ig-f2gc54SiuAnDENxJRLT_BtN4CA7hLWjlzPe_M1QZ36MLK6hRUB2EUEQUQfA2hECQFXL65oVb3yto3LW6UdbZX1m_K2H86oUwITlIhJDYQAIoYI6ho9PagJJj0aikDZ4zQxH-TekorhvClHHUO6IyZLXRB8Xex1cGH2_sfKKblcAXF0MQgENCa6_QSg_FKwMWEv3YR3CqXceE_xMWYixEBgHiP6mAoEyCZ7U2gRiSUCAJI3A-EtAkaiGZvCiSo7BB8hY_1aB2EuIBRDZwVu9G-dC7710YY_ZhLc2FRUhpwzun9u5GLNOkzJ2Tcn1RAf4yRogp4yJCTNcUW1GY7XROiFmMSEBk3DjEnmejTp4LRiLXu1YATljyFY2-Nj1b2ObqwvWFT27v2qdwn4vCc4LIgEsuAvjCZtJGkgrpQd569LDhg8UgzhmoLGVcCZyT9GpLqX3UQP4SBtAPCsgpay7GawcWU7ZuVdlVNcTU9xvy87_MBSXXAFzx7tNWrc6B1EEDRLmh8JRG0lpL16X-Ja4ovnTIMUcqK5ibCLJUOcvJ1dVl11scUjZz9W7OL2fCg5-Cf4MqZcssRlzvaRQ-OtYJdyF4b0TpS1eXxWYbw0ftHe1KswzKPnMs0flrIsuvmy0FHL1kQs2U4nZHD8FcK_nS_VhqMUSMnkEnhUC5FvFQR8DRnx0T3FEFo_FU9Phav5uuGgSRQhpEQGoOA7ASjakIKQLUzhfCRvVJQIAA)

![image](https://user-images.githubusercontent.com/13038071/216800316-40f23c5e-1f49-4292-becd-770387134392.png)

**Comment by jpmonette** [comment]
@helgasoft Exactly what I needed, thanks!
