### ISSUE TITLE
[Bug] Custom arrows are  covered by node. And series-graph && layout = 'circular'

### ISSUE THREAD

**Issue by LiangJavaDS** [apache/echarts#18247]
### Version

5.3.1

### Link to Minimal Reproduction

https://codesandbox.io/s/echrtsdemo-kfd7ij?file=/index.html

### Steps to Reproduce

1. Create a series-graph chart with circular layout.
2. Add svg image as custom arrows to the chart.
3. Observe that the custom arrows are covered by the nodes.

### Current Behavior

The custom arrows are covered by the nodes.

### Expected Behavior

Custom arrows should be able to adjust the distance from the node

### Environment

```markdown
- OS:windows 11 企业版
- Browser: Chrome 88.0.4324.150（正式版本）
- Framework: React 17.2.2
```

**Comment by helgasoft** [comment]
A workaround using SVG command [translate](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/translate).
Turns out _some_ SVG commands are allowed, but need experimentation. They are not documented for [path://](https://echarts.apache.org/en/option.html#series-graph.symbol).
 [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=M4NwjAvABARADgQwC4AsBcB6DATCByAWSjAE4A6ABhOIFYyAWAdigBliwywaoAmV4ilEFsAHGRHc-bCmRJhaDZtOJLegsMwBaUIgGYyPHhWMnTJgGwKm_MIP0ldN82UYir5kp6_evUTXhgAagBYACgoCIiYJAAnBAA7YAAbZABTAApBAFpdXQBKGABuMIB7OCQASxL4qAgAbzCIyqQk1LQoBvDIpFSADyR2mABRAGEUBBikYCgAcTi4FCgh3oQAWzhWnhhGqABfABodpBKSpMq4drqDneBUmIrU4EudpoBPODbYAHN5lBhDroRFKvEoAVwGsAAxhUYpDQSkYv8XlAYiU1u1YqDUgDIlB4iVsI92gBtZERTq43EVbCDACCSMBlPia0-MHpOMpEWAr1WACNTgBlCoAL0-RjJew5uIpnKg1MGACEGbK8SzFcrZdy-YKRWKKBLrozyRKIvLYCMNZzmatWRapZStfykkLRe1xUbJRKZZyzTAACKWplq2AB-24x0610CfUe3bIgC69qSFXiAGsnlBSR7vQ6wbDWeyTVAkBMvqkIf7A7jk_FUgKkK9Ws8PbiGx9BsBTtT_lAAO7U1BoRz7SGnEoxdp4GKpbB4IuGlURpIkmD42s90BgRNFpcuz65A1hjo7vOQ1lKo9NUvlwahos1usNpvHlvdd6szvJ7DbV-GrCcpcVzXVIexgCpVgQMtMAwCZUV7MhQC-GBt1jI8c3DU9bSrbprwrO9XwfetG0-dDKTbD8u2_fY-wHdBh1HJJx0nadZ3nS8oEAzNV2qEDqM3FDFx5J093aA9YwTHY41CXYgA)

![image](https://user-images.githubusercontent.com/13038071/218209067-633ec752-3ff3-41ca-bda5-31edc84b0348.png)

**Comment by LiangJavaDS** [comment]
Thank you for taking the time to help me out. Your expertise has been invaluable! I have a follow-up question, could you provide me with some guidance on this as well? How do you keep the arrow out of line, put the arrow on the line ?

**Comment by helgasoft** [comment]
Variable **sv1** contains [SVG path commands](https://www.w3schools.com/graphics/svg_path.asp), like M = moveto,
L = lineto, etc.  They are all relative to the start point, which is the line end.
