### ISSUE TITLE
Setting `moveHandleSize` to `0` causes "Cannot read properties of undefined (reading '0')"

### ISSUE THREAD

**Issue by uhafner** [apache/echarts#18367]
### Version

5.4.1

### Link to Minimal Reproduction

https://github.com/jenkinsci/echarts-api-plugin/blob/master/src/main/webapp/js/configurable-trend-chart.js

### Steps to Reproduce

The chart is created via the method shown above. Options:
```
{
    "tooltip": {
        "trigger": "axis",
        "axisPointer": {
            "type": "cross",
            "label": {
                "backgroundColor": "#6a7985"
            }
        }
    },
    "toolbox": {
        "show": true,
        "itemSize": 16,
        "feature": {
            "myTool1": {
                "title": "Setup",
                "icon": "ipath://M487.4 315.7l-42.6-24.6c4.3-23.2 4.3-47 0-70.2l42.6-24.6c4.9-2.8 7.1-8.6 5.5-14-11.1-35.6-30-67.8-54.7-94.6-3.8-4.1-10-5.1-14.8-2.3L380.8 110c-17.9-15.4-38.5-27.3-60.8-35.1V25.8c0-5.6-3.9-10.5-9.4-11.7-36.7-8.2-74.3-7.8-109.2 0-5.5 1.2-9.4 6.1-9.4 11.7V75c-22.2 7.9-42.8 19.8-60.8 35.1L88.7 85.5c-4.9-2.8-11-1.9-14.8 2.3-24.7 26.7-43.6 58.9-54.7 94.6-1.7 5.4.6 11.2 5.5 14L67.3 221c-4.3 23.2-4.3 47 0 70.2l-42.6 24.6c-4.9 2.8-7.1 8.6-5.5 14 11.1 35.6 30 67.8 54.7 94.6 3.8 4.1 10 5.1 14.8 2.3l42.6-24.6c17.9 15.4 38.5 27.3 60.8 35.1v49.2c0 5.6 3.9 10.5 9.4 11.7 36.7 8.2 74.3 7.8 109.2 0 5.5-1.2 9.4-6.1 9.4-11.7v-49.2c22.2-7.9 42.8-19.8 60.8-35.1l42.6 24.6c4.9 2.8 11 1.9 14.8-2.3 24.7-26.7 43.6-58.9 54.7-94.6 1.5-5.5-.7-11.3-5.6-14.1zM256 336c-44.1 0-80-35.9-80-80s35.9-80 80-80 80 35.9 80 80-35.9 80-80 80z"
            }
        }
    },
    "dataZoom": "[{\"type\": \"inside\"}, {\"type\": \"slider\", \"height\": 25, \"bottom\": 0, \"moveHandleSize\": 0}]",
    "legend": {
        "orient": "horizontal",
        "type": "scroll",
        "x": "center",
        "y": "top",
        "textStyle": {
            "color": "#14141f"
        }
    },
    "grid": {
        "left": "20",
        "right": "10",
        "bottom": "30",
        "top": "40",
        "containLabel": true
    },
    "xAxis": "[{\"type\": \"category\", \"boundaryGap\": false, \"data\": [\"#1\", \"#2\", \"#3\", \"#4\", \"#5\", \"#6\", \"#7\", \"#8\", \"#9\", \"#10\"], \"axisLabel\": {\"color\": \"#14141f\"}}]",
    "yAxis": "[{\"type\": \"value\", \"min\": 49.76, \"max\": 100, \"axisLabel\": {\"color\": \"#14141f\"}, \"minInterval\": null}]",
    "series": "[{\"name\": \"Line Coverage\", \"type\": \"line\", \"symbol\": \"circle\", \"data\": [55.86, 55.92, 55.74, 55.74, 56.46, 53.44, 52.64, 52.32, 49.76, 49.86], \"itemStyle\": {\"color\": \"#A5D6A7\", \"borderColor\": \"#ffffff\", \"borderWidth\": 0}, \"areaStyle\": {\"normal\": true}, \"stack\": \"\"}, {\"name\": \"Branch Coverage\", \"type\": \"line\", \"symbol\": \"circle\", \"data\": [59.65, 59.65, 59.13, 59.13, 59.13, 54.8, 54.8, 54.33, 51.11, 51.11], \"itemStyle\": {\"color\": \"#C8E6C9\", \"borderColor\": \"#ffffff\", \"borderWidth\": 0}, \"areaStyle\": {\"normal\": true}, \"stack\": \"\"}]"
}
```

### Current Behavior

With version 5.4.1 I get the following error:

```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at e._resetInterval (echarts.min.js:45:861474)
    at e._buildView (echarts.min.js:45:855184)
    at e.render (echarts.min.js:45:854739)
    at echarts.min.js:45:215695
    at Array.forEach (<anonymous>)
    at E (echarts.min.js:35:5064)
    at Vv (echarts.min.js:45:215633)
    at zv (echarts.min.js:45:215475)
    at e.update (echarts.min.js:45:210800)
```

### Expected Behavior

With version 5.4.0 I get correctly a zoomable chart.

### Environment

```markdown
- OS: macOS Ventura 13.2.1
- Browser: Version 111.0.5563.64 (Offizieller Build) (x86_64)
- Framework: n/a (Within a Jenkins plugin)
```

**Comment by helgasoft** [comment]
First to fix -  xAxis, yAxis, series are strings, not arrays.
Second - in _toolbox.feature.myTool1_ the **onclick** function is missing. 
I would consider the second issue **as bug** because there is no error handling and the error thrown is nondescriptive - _"Bind must be called on a function"_.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&version=5.4.0&code=PYBwLglsB2AEC8sDeBYAULTsBEZjABtIRsAuZdLKnMAJwgHMGBTWsnAQwA8IBnbADSVqmbNz4AFYBGhhW7VBhHVcATxDN22AMa1gvfkKXKs2AhwBGzAguEmR2Cx20BrBnoCu0ACYBhQsBs5NgAxABsHADsAJwAHACs2Hb2AL7JVGnGsClGVLj4BBbAXLZZebwAFsAA7ux0Hsy5ytgQcgC2AMoQAF6a5ACMYU0OAGbMHGAetH0UZSptqgAqBf2l9iqQYAQz2B3MkyQCsOn2MNoEEK7kABQAlAgAfMiwAPQAVLBnF66w1Ry8sDafF4MgYsDeL2yw3WOEuMC0EBAEwqpBeLwAsgAWWKRAB0mNgAGZ-vFcZECABaTEAJlxYQp1MxdO0TMJDMJuOpsFZVMisAADBTIvzOQQaXSGUywizcdEGbjYrA8f0KbE6bBSfEKf1Mdr-riVYTSfTCYKwnjYhT4kzIhTolKKRzLUyVf1BaTXUzLbTCQAZQmxEWK_pu7TavFykn4x1qrXUvFssJBx0egBq1NJsW07olHMjIq10WjIbJjrCpbV1KFPIt2v5Ra5OfisH1VaLBPLKvbLf1kVTkXiYeptK5EaptODRctSYVRI9vtiar5CVxg6psvllpD2o3OtnPslZNg1PLtsxHLCGrVcutR_tEt7Gvx6pLXM1LcxvvNuMJx-p_TDVljw5KsgMxPl-SVEVqUpcVL0ZZl12iY8FSFA1YDVel3x1Ht0KNdVTVgb9FVvPl70vJ1uXQt0n36D99x_MVaXpBDpX6CMW1JAkA1XY8EyIoM5wNAA3TEG2zJ8KNlFsC1gbsSz5QlTwwzklSAi0ZIbAUny1Vs5OjTt9N1BThKpcTh05NDkPFLcpwE1D8P6Jj1VYmVkInHsW2kvdvR_Y8bQZZTzwleJrw1ALyK8rVNQpUsSzZY1tRdbp0QzCilMAl0BVVQV8LlQMct4PKcowwVA1KoTkPKgq8tKkrA26JI5gyE5MEyDJoWwbwJg4AAtfA2nYABtJA1A0BFoBBbxNByZAxp2XgLmmtgjmwCpmEYCowHYDNVqKMA8EG8h-VWtpgGE5gAAkOB8bYul6dh-RSABdTrthYHw1maQIIGYWQtCqehuhgMAOBsaE8jAdQFt0QhwdanASmCbQ_rkFaEewVQtDwQ4MbkLgwA6KHti-9YdACIIcBCHUaZGJqTHarAcmSbB3AgbxSZUbYRm24JqX5QQMfoBgtq0N1BeanB9sOrRTQlkx8hIYJMQFiHTG0EGOBkX1LGsOpaAaZJmaybAuAAQR4fhyBG-atG0CZmAYQIsb24AvG62hVAAcQ4JXYBGMHeEaY45i6nrhtCVZVpCalBCpwk49CTFE5CRJo7CFPIhT2IU-iFPxdekOHHEXgdasGxyFGjWCECLRqcxWnsBSF7OtUC2-GG0aofG4JhLBhpE6BaB2DEskhhwNpuHYN0TqLlQS7LvXK_JmvKcjhuG7p2bsCHgBJWRWD7ivYGgDwCAIFuWaD-hmCt2AhpOUboA4Nodl9GRmFgfwLtoDgWET7uOwLjQE0KtXgqg2hFGPjoCAtBzigLnnkbqoNhrxEzOPNBspqRHEwZETEODSR4JweWTEGCOSYnwRqZilD4g-mwdyIskRx6j1iGEQuJwWjtCJqoEmy9q612CCEM28QAAiYQzZZ1drQZa_hV51xGAoxRicijSNYAAdXZmACoj1ZocI4NMDg3DeFzWgIESex96jMG3rwUGrgtBNyOI_bAz9X5aAAEK_2gNoCoX9zqsD_gg22wRgGBPAZAwgdtYHwLjhw5BHBUFFjCPEHBiTkkaiLP0QkKSDRZPSTknBXoCkKiKYSXJ8R9QhhwRU_o7DQ6tGYJ0YmMwq4Uzrr4WIABRMIvg85SJka0wRiilF9PUZo7Rx1dGh30eMIxzTnFmLBvrBo1jbEuHsYzTAz10ApCAA)

**Comment by uhafner** [comment]
Sorry, I copied the options from the browser console log. In the debugger the options are arrays, or am I missing something?  How can I simply export them? The onclick function is also missing due to the copy operation, here is the original: https://github.com/jenkinsci/echarts-api-plugin/blob/master/src/main/webapp/js/configurable-trend-chart.js#L38 

Here is a screenshot:
![Bildschirm­foto 2023-03-10 um 22 46 12](https://user-images.githubusercontent.com/503338/224434539-95215205-d72b-4975-835b-0dd2c8c550b1.png)

I will try to export the options correctly and provide a demo...

**Comment by helgasoft** [comment]
you could also work on my Demo Code and copy/paste with _Share_ button on bottom.
Best demos do not include frameworks or plugins, just JS + ECharts.

**Comment by uhafner** [comment]
After digging into it a little bit deeper I noticed, that the affected option is the data zoom:
```
        dataZoom: [
            {
                type: 'inside'
            },
            {
                type: 'slider',
                height: 25,
                bottom: 0,
                moveHandleSize: 0
            }],
```

This causes the error in 5.4.1 but not in 5.4.0. When I remove `moveHandleSize: 0` then the chart renders in 5.4.1! 

I don't understand why it works in your example, I''l try to reproduce it there as well...

**Comment by uhafner** [comment]
I think in 5.4.1 it is not allowed anymore to set the `moveHandleSize` to zero. When I use 
```
{
                type: 'slider',
                height: 25,
                bottom: 5,
                moveHandleSize: 5
            }
``` 
then everything works.

**Comment by uhafner** [comment]
Seems to be a conflict with one of our own JS libraries we are using in parallel in our application.
