### ISSUE TITLE
[Bug] 环形图自定义中心文字与第一条数据绑定，包括鼠标移入显示的tooltip以及点击功能

### ISSUE THREAD

**Issue by hou18103912159** [apache/echarts#18397]
### Version

5.4.1

### Steps to Reproduce

1,创建环形图
2,自定义series.label为中心的总值
`option = {
  tooltip: {
    trigger: 'item'
  },
  legend: {
    top: '5%',
    left: 'center'
  },
  series: [
    {
      name: 'Access From',
      type: 'pie',
      radius: ['40%', '70%'],
      avoidLabelOverlap: false,
      legend: {
        selectedMode: false,
      },
      label: {
        position: 'center',
        show: true,
        formatter:() => {
          let num = 100
          let str = num +'\n'+ '总量'
          return str
        },
        color: '#000000',
        lineHeight: 26,
        fontSize: 16,
      },
      labelLine: {
        show: false
      },
      data: [
        { value: 1048, name: 'Search Engine' },
        { value: 735, name: 'Direct' },
        { value: 580, name: 'Email' },
        { value: 484, name: 'Union Ads' },
        { value: 300, name: 'Video Ads' }
      ]
    }
  ]
};`

### Current Behavior

1，环形图制作
2，自定义环形图中心文字为‘100 /n 总量’
3，鼠标移入中心文字出现tooltip与环形图第一条数据关联，如图所示即为鼠标移入中心文字时发生的情况。
4，期望：鼠标移入中心文字不出现tooltip或出现自身值得tooltip，且不与环形图第一条数据关联（包括点击事件）
![image](https://user-images.githubusercontent.com/20158693/225792475-c688669f-7a1c-48c1-86bb-371afa0e7903.png)

### Expected Behavior

期望：环形图，鼠标移入中心文字不出现tooltip或出现自身值得tooltip，且不与环形图第一条数据关联（包括点击事件）

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
not-a-bug
Use **title** instead of _series.label_ - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=pie-borderRadius&code=PYBwLglsB2AEC8sDeAoW7aTAGwKYC5k0MMxcAPMQgRgAZbYBqWAcgB1oWnXBuA0HnElgBpiJWOUIsAxrmhkATkNgBPCdNm4Fw0ejKUAymCV58qbRknBswORIDE9B7SEjtAMxhg9EAF4FYAJloXDABfFxCtTGBLSBBCJEw5CABzZI0JCDIAWy4I4jw06AATeKi41gBWAFJFPFcqVjV5XMiAZw0IXFbCAG0XU1FDED8WEE7nbTkAQyKIAFdu2B6WABZaGsFWAHZ1lgBdSJIiqbAp3uCMBIA3Kew5vzoVgA5N6Cmskb1cKblJAAtYABRaDJCDQXAtC7oa63e6ELYAZgqr3eIwAIhA5LhJGBIWZkLAbnc_BUnrQUR8JICslMINg8WYYcTCM8VhSRgBVaBQOAAQSKrQZ2iZcNgCPo7IkADUIEVcMBYPzBbAwto9uFiOqQgBuIA).
![image](https://user-images.githubusercontent.com/13038071/225812023-4a253173-6461-4ae8-b756-2190e7fd3bda.png)

**Comment by hou18103912159** [comment]
好的，谢谢。
