### ISSUE TITLE
[Bug] (pie): incorrect response area of pie piece when applied `selectedOffset`

### ISSUE THREAD

**Issue by 100pah** [apache/echarts#18412]
### Version

5.0.0

### Link to Minimal Reproduction

[Demo for Reproduction](https://echarts.apache.org/examples/editor.html?version=5.0.0&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQM5YBOEWrJA2lXSp0I2NACGAWywkA5CG6zKo9GACeIGbHmLlK9tgDGYLAQCywAltmsI0HNiWCRAC2AA3TgEFoESeMgYEgAzcQx2PVEDLGNTAHlg4PYwEgBmAAZIkUMMYEMAawB3CHYSMA4AVyws9A5xAggK3lg-AFZM2ABGdPSAXRrYcV9_QOgQsIjndAIA8X4pkSRYdzCqkg6JaTkAEQgOGLBYL0NDHlZZWBYVReXVrVTu8jEpawBRfwgMWDNxDnysSD2C5Xa7IW4YNawABMqQALE9NtYAOpYABGthMRwI50uAyE4MhnVSrQRLzkADUIFZgFicSDrksVhCtJ1WrCABykrbaADKWF-hhcsFe9jsWGBC16zlIVClpAA3EA)

### Steps to Reproduce

firstly, click one section:

![image](https://user-images.githubusercontent.com/1956569/227084608-2f850506-1755-4131-b37b-2270fdca5c36.png)

Then click the section again to make it return the original position:

![image](https://user-images.githubusercontent.com/1956569/227084644-4c5d05f3-64e3-428e-ad65-80d52533c478.png)

At present the clickable area is not returned, but still:

![image](https://user-images.githubusercontent.com/1956569/227084671-0d37449e-77ac-439b-a4c2-9b315a6fe17b.png)

Then the clickable area is not correct for ever.

Then I run the visual test, but the visual test about pie all passed, not cover this case.

### Current Behavior

-

### Expected Behavior

click area should be correct.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by LaxusT** [comment]
The problem lies in animation.
you can circumvent this issue through animation attributes.

My [demo](https://echarts.apache.org/examples/zh/editor.html?version=5.0.0&code=PYBwLglsB2AEC8sDeAoWsA2BTA5l6AJgFzIC-ANGrGMMBpCCUhVQM5YBOEWrJA2lXSp0I2NACGAWywkA5CG6zKo9GACeIGbHmLlK9tgDGYLAQCywAltmsI0HNiWCRAC2AA3TgEFoESeMgYEgAzcQx2PVEDLGNTAHlg4PYwEgBmAAZIkUMMYEMAawB3CHYSMA4AVyws9A5xAggK3lg-AFZM2ABGdPSAXRrYcV9_QOgyyurndFYwAKwfPwCoMeQpkQIKutGSdrWWFVgCAPF-NaFYdzCqkg6JaTkAEQgOGLBYL0NDHlZZWH2D5AXK5aVLdchiKTWACi_ggGFgZnEHHyWEg9l-_wOSCBGGusAATKkACzgu7WADqWAARrYTO8CD8_gNzpdcVpOqlWqTIXIAGoQKzAemMzEqbGsvGdVpEgAc3Pu2gAylgkYYXLAofY7FgMWtes5SFR9aQANxAA)
