### ISSUE TITLE
[Feature] 在数据为空时，不会展示label，希望可以展示label

### ISSUE THREAD

**Issue by AdrianDuan** [apache/echarts#18456]
### What problem does this feature solve?

在数据为空时，label不会展示，我想在数据为空时，展示自定义的标签，想问一下是否有配置项允许在数据为空时展示label呢？

以下方配置数据为例：

```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, '-', 218, 135, 147, 260],
      type: 'line',
      label: {
        show: true,
        formatter: (params) => {
          if(!params.data) {
            return '暂无数据'
          }
          return '有数据'
        }
      }
    }
  ]
};

```

无法做到在没有数据的时候展示空标签

### What does the proposed API look like?

希望label有配置选项，允许数据为空时也会调用formatter展示标签

**Comment by helgasoft** [comment]
Workaround with individual line segments - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=CYQwLiAEC8kNoChLwOQFkD2A7FAaSAjAKwAM-WArgDZUC6uSqAKhQKZ6QBMAzGYfYzgoA6q2AdOpfCXrIA9HMgkYkAJZYAbqoDOqgEZVWkKuqMBjDFQwAnfJOWwqIPayqQADhl1hV2QSiYACwoJAgAOaQFkIQAxa1UOAm4ifAIo1ABlcESAFgB2VPShDIocOwA2PjSEWgBuBG1QCBUmkAA6AFsQdwAKHvcAShgAPkgAb0YwDvcVShp65FUAM0h-uE5aSABCWDmqAcZkKZnYCeRzyDAAT3dWAC5IFBMsdgYL5FaHxHfzuHdrVgaOAyfD_QFwNLpH5_YGydwQ2i0Q7nKHnZ6sDLXQwPMaQZEXCxWawPeEbaDQZQAfkeYGsICw2ncIABWDAKEgDxQBjYHHx5wA7qpgGBAg9uJAAL5vd6qMCsDqYq7Y8Z85AYJlmWVXEnrWjkqlKDmEaU_Qk2Tnc9h8qV8pwuKg41WQbSBDD8h60tgm97qkCa64PAjei5LGxdMBy4lO5BrMkUoYAMlWYKBcZIBx-P2pKEAQWaAA9NAA6mgDtjFDR86cwCQ5sXSz8JciJQsPACNCp3I2AWAKNYsJdpvUJQN6uqfNgVGdIAAPACCE50jou11unLM4FYAHMbFc8MjPqhMGVHixXo9ROJ8AFghwUHEEuesmy76UUEjkDbkFcZ3Pxm_nax4qxtAeRpwBABgGyAA)
You'll still need a value for the "missing" point so that its label has a valid position. 
Does that "feature" make sense to me?  No, just the coding is fun.

![image](https://user-images.githubusercontent.com/13038071/229206494-7c45f792-7e56-45b4-8097-620036efa21c.png)

**Comment by AdrianDuan** [comment]
@helgasoft Thanks for your reply! This workaround helps me. Hope can get api and achieve this in a more elegant way. But I totally agree with you "coding is fun" :)
