### ISSUE TITLE
"this.__layers is null" error clicking on a chart that has a legend or toolbox

### ISSUE THREAD

**Issue by dsargent** [apache/echarts#18459]
### Version

5.4.1

### Steps to Reproduce

I don't have a minimal reproducible sample as this is proprietary corporate code, but my use case is pretty simple:

1) Create a 3D surface plot
2) Add a toolbox or legend of any kind
3) Add an onClick event like this: `onEvents={{click: onChartClick}}` as a property of the EChart. My particular onClick event updates some fields on the page that generate a re-render
4) When you click on the chart, boom -- exception down in zrender. The null pointer is happening on the `this.__layers` part of this code from canvas/Painter.js in zrender:

```javascript
  CanvasPainter.prototype.eachOtherLayer = function (cb, context) {
        var zlevelList = this._zlevelList;
        for (var i = 0; i < zlevelList.length; i++) {
            var z = zlevelList[i];
            var layer = this._layers[z];   // <---- boom! this.__layers is null
            if (!layer.__builtin__) {
                cb.call(context, layer, z);
            }
        }
    };
```

If I remove the legend and toolbox, everything is fine. Adding either of those causes the exception to happen when clicking on the chart.

I've tried googling, searching your issues and doc, searching zrender's issues and doc, and even asking chatGPT. The latter suggested adding a `z` property to the series, which I tried but it didn't help.

Thanks for any suggestions.

### Current Behavior

Crashes with an exception when handling `onClick`

### Expected Behavior

Correctly handles `onClick` without crashing

### Environment

```markdown
- OS: Tested on Ubuntu and MacOS
- Browser: Same on Chrome & Firefox
- Framework: ReactJS/Typescript, using echarts-for-react to wrap ECharts.
```

**Comment by helgasoft** [comment]
not-a-bug
**Minimal Reproduction code** is actually "pretty simple" to build - [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=simple-surface&gl=1&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMgL4A0as2ApgOaXQAmhSp5mOARsAB5MBmlAQzABXAE6Um4gM6ZxTIgrLp2AgMYBraqODCGAYRzBRhAOQBiXpZNLYANwhThA7AFkBBZOXRSAFsADuhLzOUpQ26PQQALZ0UlDQhABM4bBREAmwALQAjClRAjywuV6w6QBKAtC0TCXoqobGsADateiw5gDM2R0AbACcAKzWrejmACwDAOwD7GPDbQvtZpNjAvT02fOLo2YC7PR9lH1b2-aUAAy8HbwAHCeL5paW7Lz3C4-UF33nb22P9AJKD1Nil3hYxj16GMOr8dvRJh1zolJrClgIBuckT0TK0ALolIjkFjoLgAQS4Dg6ABEagswABPEASdq2ZzCSg49DE2D08mUmmeOmM5kmVnYdmc2DcgBefKk1NpbQZTNMYolRJsWgg9AVgra9ko_gM0DA2mwioWAHpLbAQNoAFaUVSQGCmIxgPxadw-CCqSVcjXkUKiCCUKSEFoLVDbZUixyiYKqDkkWDQAQxUyqLO_fwQcS8UTp5nR7awa2wXwBIIhSitbkLSgARycLoyJe2hXbpZklA85wAdOcBiMpaC2vSLd2wL3CAOhyP64tpUFdM74rAABRcFP0gCUetLpV4m7cHv7eykW_3AB5YAPsrAAGSP2Cnnzn9iXvewW_3_ddw9xBEUQ4BMTITAAbhHAND3QICxDgN9-ziaAt1gAAqV8hHfAAFABJfdMKQlCN3pDCsLPfDdygw9CW2Oi2gY_EiCgqJ6T0HwBFEMB-xgDcTFUbBfXUaxN33eAAD49XqaApBwSh-2wYBqH4zhgCiAB-ExqJQIhdyAA)
Does it "boom"? No.  
Maybe crash is due to ReactJS overhead.
<details><summary>disclaimer</summary>
opinions expressed in this post are strictly personal, as ECharts user, not a developer
</details>

**Comment by dsargent** [comment]
But the onClick in the sample isn't doing any re-rendering, just logging to the console. Maybe that's the difference. Or it could indeed be something in the React machinery or the echarts_for_react library that's causing it. But whatever the cause, the error is happening down in zrender, and only happens when adding either a legend or toolbox to the chart.

**Comment by helgasoft** [comment]
> But the onClick in the sample isn't doing any re-rendering...

you could modify it to include whatever is needed for the crash
> error is happening down in zrender

zrender has its [own repo](https://github.com/ecomfe/zrender/issues), but without Minimal Reproduction Code I doubt they will be able to help.

**Comment by dsargent** [comment]
Thanks for the quick responses. I am new to the whole of front-end development (many years backend dev) so even something that might seem simple like coming up with a minimal JS example is non-trivial for me -- I'm only somewhat familiar with Typescript. Working on a simple example using the links provided above.

**Comment by dsargent** [comment]
I don't have bandwidth to create a reproducible demo and we found a workaround by doing things in a different way, so feel free to close.
