### ISSUE TITLE
Gauge chart inherit color has bug when there is multiple data

### ISSUE THREAD

**Issue by abdurrahmanyildirim** [apache/echarts#18527]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/abdurrahmanyildirim/pen/JjmKgQr

### Steps to Reproduce

Just use that chart options. You will understand what I mean.

```
option = {
  series: [
    {
      type: 'gauge',
      axisLine: {
        lineStyle: {
          width: 10 ,
          color: [
            [0.25, '#FF6E76'],
            [0.5, '#FDDD60'],
            [0.75, '#58D9F9'],
            [1, '#7CFFB2']
          ]
        }
      },
      data: [
        {
          value: 60,
          name: 'Grade Rating1',
          title: {
            color: 'inherit',
            offsetCenter: [0, '10%']
          },
          detail: {
            color: 'inherit',
            offsetCenter: [0, '15%'],
            overflow: 'truncate'
          },
          itemStyle: {
            color: 'inherit'
          },
        },
        {
          value: 20,
          name: 'Grade Rating2',
          title: {
            color: 'inherit',
            offsetCenter: [0, '25%']
          },
          detail: {
            color: 'inherit',
            offsetCenter: [0, '30%'],
            overflow: 'truncate'
          },
          itemStyle: {
            color: 'inherit'
          }
        }
      ]
    }
  ]
};
```

### Current Behavior

I use 2 pointers. I wanna use 'inherit' for color. Gauge set same color for all pointers.

### Expected Behavior

I expected that gauge set color by value and should inherit color according to current axisLine color

### Environment

```markdown
- OS: Win 11
- Browser: Chrome
- Framework:Angular
```

**Comment by helgasoft** [comment]
workaround: use 'auto' instead of 'inherit' for [itemStyle.color](https://echarts.apache.org/en/option.html#series-gauge.data.itemStyle.color).
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWBnApgJwhywC5YBtdTTVDKzMATxB1IHIBzAQwFd2dWANJTqxOADwhYAMhGgtkwkbAA2snAGVGy-TSV0A7hAAmYABakAjAAZYQ2ntgBjYMuB5SivRXsPyVgHQATACsArCsAMQAYlEAbACiAOyxrAC6dr5UZAGh4dEAIoWxVmkZmX7-ibmRwQAc-QCcUQ2lng5kFmGRiQDCMQBCgWltIqmwI5gAviOTZXRGnGCcpN4Our4AbpzK3PLFc3rQnAC28qwA4nicRjiwAEqLsuwWghNUkGDapOuZzq7u4VkpnwEDArx8DmAADMobgwD0cNAwPgVlYutYAKTDCEiWZvTA3JYQZTffFUP5uNhAkFgg6QmFwhFIlF-dHBLHpMmYYAbfBQ1z6NhgPDcaCORb8Ml4nF0UE4Y6aBhfBQykQUgGsHhgYCsKV0qjStZkrY7eSBNFko6nNiXa63B6QaDsIb6ugfZU_XzqqnQYEEWlc2DQ2E4eGI5EA7JdEIcvVkwmcYmk1V0b2A3008HlIMM0NMiOoroAZisHNdIh5fIFQpFYolupTsENvjlCq0OkDac13G1Dcy01VA6UqU8Q9gI7QkwA3EA)
![image](https://user-images.githubusercontent.com/13038071/232846044-76a2d3ea-56fc-4572-a51d-5e2bb4e940f1.png)

**Comment by abdurrahmanyildirim** [comment]
> workaround: use 'auto' instead of 'inherit' for [itemStyle.color](https://echarts.apache.org/en/option.html#series-gauge.data.itemStyle.color). [Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeBYAULWBnApgJwhywC5YBtdTTVDKzMATxB1IHIBzAQwFd2dWANJTqxOADwhYAMhGgtkwkbAA2snAGVGy-TSV0A7hAAmYABakAjAAZYQ2ntgBjYMuB5SivRXsPyVgHQATACsArCsAMQAYlEAbACiAOyxrAC6dr5UZAGh4dEAIoWxVmkZmX7-ibmRwQAc-QCcUQ2lng5kFmGRiQDCMQBCgWltIqmwI5gAviOTZXRGnGCcpN4Our4AbpzK3PLFc3rQnAC28qwA4nicRjiwAEqLsuwWghNUkGDapOuZzq7u4VkpnwEDArx8DmAADMobgwD0cNAwPgVlYutYAKTDCEiWZvTA3JYQZTffFUP5uNhAkFgg6QmFwhFIlF-dHBLHpMmYYAbfBQ1z6NhgPDcaCORb8Ml4nF0UE4Y6aBhfBQykQUgGsHhgYCsKV0qjStZkrY7eSBNFko6nNiXa63B6QaDsIb6ugfZU_XzqqnQYEEWlc2DQ2E4eGI5EA7JdEIcvVkwmcYmk1V0b2A3008HlIMM0NMiOoroAZisHNdIh5fIFQpFYolupTsENvjlCq0OkDac13G1Dcy01VA6UqU8Q9gI7QkwA3EA) ![image](https://user-images.githubusercontent.com/13038071/232846044-76a2d3ea-56fc-4572-a51d-5e2bb4e940f1.png)

That worked. Thanks
