### ISSUE TITLE
[Bug] Tooltip display data no match with xAxis

### ISSUE THREAD

**Issue by cloudups** [apache/echarts#18602]
### Version

5.4.2

### Link to Minimal Reproduction

https://codepen.io/cloudups/pen/WNazoeL

### Steps to Reproduce

Mouse hovering on the xAxis, you will see it like image: 
![image](https://user-images.githubusercontent.com/13176866/237053839-036a0a7b-a516-4d18-addc-5797f930e042.png)

### Current Behavior

tooltip display data(time is 2023-04-01) no match with current xAxis(jul)

### Expected Behavior

tooltip display data should match with current xAxis(jul)

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

**Comment by helgasoft** [comment]
There are too many bars per day/month. 
Axis label shows the position of the very **first** bar for the day/month. The others are added side-by-side and since each bar has a _barWidth_, they gradually move to the right further from the label. If too many, they could even spill to the next axis label.
Conclusion: bars are not a good option for this type of data.  Try _scatter_, add this code at the end of yours:
```
option.series.forEach(s => {
  s.type = 'scatter';
  s.data = s.data.filter(a=>a[1]); // remove nulls
});
myChartEchart.setOption(option);
```
![image](https://github.com/apache/echarts/assets/13038071/3598ba25-17cc-4b67-8f2e-d42021cacc59)

**Comment by cloudups** [comment]
> 

ok, tanks
