### ISSUE TITLE
[Bug] charts not always sync the axisPointer

### ISSUE THREAD

**Issue by spiral2k** [apache/echarts#19133]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/s/echarts-charts-sync-issue-z4r2qw

### Steps to Reproduce

hover on the last chart on the list, you cant see that the sync of the axisPointer works great, but when hovering on the other charts, the last chart doesn't display the axisPointer most of the time.
 

### Current Behavior

I'm trying to create a couple of charts that will be synced (only axisPointer for now).
it does not always work and I don't understand why, for example when hovering the line & bar charts, the last chart in the list is not displaying the axisPointer, but when hovering the last chart i see the axisPointer on all charts

### Expected Behavior

i want to be able to sync the axisPointer when hovering on one chart to others, including the custom one

### Environment

```markdown
- OS: Mac OS x Monterey
- Browser: 115.0.5790.114
- Framework: React@18.0.25
```

### Any additional comments?

appreciate any help with that
thank you

**Comment by helgasoft** [comment]
Please make an effort to create **Minimal Reproduction code**, otherwise the chance of getting traction on the issue is minimal.
Minimal Reproduction means preferably straight Javascript code shared through editable examples like [this one](https://echarts.apache.org/examples/en/editor.html?c=line-simple).
Using React or Angular frameworks is fine, provided that code is **short and relevant**. 
Dumping entire applications is counterproductive since reviewers need to spend their time doing specialized **debugging**. This is not meant to be used for Github issue resolution.

>  last chart in the list is not displaying the axisPointer

your last chart is a **custom** [image chart](https://codesandbox.io/s/echarts-charts-sync-issue-z4r2qw?file=/src/utils.tsx:4626-4657), which I think cannot be [connected](https://echarts.apache.org/en/api.html#echarts.connect) to the others.
Eventually a core developer could give a definitive answer to that.

**Comment by spiral2k** [comment]
@Ovilia i've created the issue with a demo

**Comment by Ovilia** [comment]
@spiral2k Your code has error. BTW, please make it minial and use [this template](https://codesandbox.io/s/echarts-basic-example-template-mpfz1s) instead.
