### ISSUE TITLE
[Bug] sankey 设置 nodeWidth 节点的 click 事件失效

### ISSUE THREAD

**Issue by wmasfoe** [apache/echarts#19145]
### Version

5.4.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/xenodochial-einstein-8n457d?file=/src/components/Echarts.vue:22,9-23,25

### Steps to Reproduce

1. 点击 sankey 的node，预期是：与它连接的link与node都是高亮的，但只有点击的link高亮。
2. 去掉 `nodeWidth: '10'` 这个配置，正常工作 

### Current Behavior

1. 点击 sankey 的node，预期是：与它连接的link与node都是高亮的，但只有点击的link高亮。
2. 去掉 `nodeWidth: '10'` 这个配置，正常工作 

### Expected Behavior

1. 点击 sankey 的node，预期是：与它连接的link与node都是高亮的，但只有点击的link高亮。
2. 去掉 `nodeWidth: '10'` 这个配置，正常工作 

### Environment

```markdown
- OS: Mac
- Browser: Chrome118
- Framework: vue
```

**Comment by helgasoft** [comment]
[nodeWidth](https://echarts.apache.org/en/option.html#series-sankey.nodeWidth) should be a number (not a string)
_selectedMode_ instead of 'selectMode'
```selectedMode: 'single'``` inside _series_, not outside
> Click on the node of sankey. The expectation is....

ECharts only fires the click event, does not handle it.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=sankey-simple&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXMmurGAJ4hbEDkGAhtANZYW0A0p6WAtiAAsGGCERJkyAM2ABjAK5jaDACYArBjKzQZ7brAC-XCdGDKsAdQjKwA4gEYADB1h7sAGywywWZQFlTNLD0ENAA5h6cLhLunmDEqBLoyqIMAEYeyoSSDG7YznroEN68AMqUHvGwqcA4ZjiW1rYATM7VtbgAwsBuNYS0OD60hgWwbiFYZRQVyDLdvbTpclhDRok-oVgAMmlYbvEYAsAA7oRgOEv6esMSyjgMoaFp09m5WKtJDGAMxADaIwmJdDQBi8QJKWgja6JAGA4GguipCGAqESGGJOFghh2JGJFFkNHGEGYpo4iR49AEsgYhHYyHvfEjIFEugyUlkS4SAC69LGLDEf0BlPQGGAchwmjoDE4jPIDBwGziQSx0sB6AAbjklsQAKx0_4ykViiVKlWqr7yrCKpQk-kSDVuLWwADMesFBtF4rBiNtZHNCpppsB9sdAA5XdD3UbMYHEn7LQGferNYEXcifULMB7jQtsYnZRarcq88HAnZw6jI56EzK41bWcXk8QmpC9JzSJd9ABuIA)

**Comment by wmasfoe** [comment]
> [nodeWidth](https://echarts.apache.org/en/option.html#series-sankey.nodeWidth) should be a number (not a string)nodeWidth 应该是一个数字（不是字符串） _selectedMode_ instead of 'selectMode'选择模式而不是“选择模式” `selectedMode: 'single'` inside _series_, not outside `selectedMode: 'single'` 系列内部，而不是外部
> 
> > Click on the node of sankey. The expectation is....单击桑基的节点。期望是....
> 
> ECharts only fires the click event, does not handle it.ECharts 只触发点击事件，不处理它。 [Demo Code 演示代码](https://echarts.apache.org/examples/en/editor.html?c=sankey-simple&code=PYBwLglsB2AEC8sDeAoWsDOBTAThLGAXMmurGAJ4hbEDkGAhtANZYW0A0p6WAtiAAsGGCERJkyAM2ABjAK5jaDACYArBjKzQZ7brAC-XCdGDKsAdQjKwA4gEYADB1h7sAGywywWZQFlTNLD0ENAA5h6cLhLunmDEqBLoyqIMAEYeyoSSDG7YznroEN68AMqUHvGwqcA4ZjiW1rYATM7VtbgAwsBuNYS0OD60hgWwbiFYZRQVyDLdvbTpclhDRok-oVgAMmlYbvEYAsAA7oRgOEv6esMSyjgMoaFp09m5WKtJDGAMxADaIwmJdDQBi8QJKWgja6JAGA4GguipCGAqESGGJOFghh2JGJFFkNHGEGYpo4iR49AEsgYhHYyHvfEjIFEugyUlkS4SAC69LGLDEf0BlPQGGAchwmjoDE4jPIDBwGziQSx0sB6AAbjklsQAKx0_4ykViiVKlWqr7yrCKpQk-kSDVuLWwADMesFBtF4rBiNtZHNCpppsB9sdAA5XdD3UbMYHEn7LQGferNYEXcifULMB7jQtsYnZRarcq88HAnZw6jI56EzK41bWcXk8QmpC9JzSJd9ABuIA)

thx，`nodeWidth` 应该是个数字，`nodeWidth: 10` 就ok了
