### ISSUE TITLE
[Feature] option to center the single data point

### ISSUE THREAD

**Issue by Gumichocopengin8** [apache/echarts#19166]
### What problem does this feature solve?

[Example Code](https://codesandbox.io/s/line-chart-in-cartesian-coordinate-system-forked-cq8tcg?file=/index.js)

When there is a single data point in the Cartesian Coordinate, the data is plotted on the top right. That would be useful to have an option to have some margin to make it center without calculating min/max value.

### What does the proposed API look like?

TBD

**Comment by Ovilia** [comment]
This is because the axis max value is calculated based on the max value of data. In the case of one data, if the value is *nice* like 10 or 40, it will be the max value so it's at the top-right corner. However, if it's like 9.5 or 123, it will be smaller than the axis max value, so it won't be at the corner.

**Comment by Gumichocopengin8** [comment]
got it. thanks
