### ISSUE TITLE
[Bug] - 'init' not found in imported namespace 'echarts' - version 5.4.3

### ISSUE THREAD

**Issue by BramDecuypere** [apache/echarts#19269]
### Version

5.4.3

### Link to Minimal Reproduction

https://github.com/BramDecuypere/nuxt-ag-grid-demo

### Steps to Reproduce

1. 'init' not found in imported namespace 'echarts'

### Current Behavior

Eslint is complaining about `init` not existing into the echarts namespace

### Expected Behavior

Have it inside of the echarts namespace

### Environment

```markdown
- OS: MacOS
- Browser: /
- Framework: Nuxt
```

**Comment by plainheart** [comment]
Looks like it's caused by the [import/namespace rule](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/namespace.md) as echarts.d.ts (for UMD module) re-exports `init$1` as `init`. You can disable this lint rule if you hope to import all modules, or use the recommended [on-demand import](https://echarts.apache.org/handbook/en/basics/import/#shrinking-bundle-size) in ECharts v5,  which has no such problem.

```ts
import * as echarts from 'echarts/core'
```
