### ISSUE TITLE
[Feature] Support stretching height when color image does not repeat

### ISSUE THREAD

**Issue by He110te4m** [apache/echarts#19329]
### What problem does this feature solve?

[Example](https://echarts.apache.org/examples/zh/editor.html?c=line-simple&code=MYewdgzgLgBAlgWwOYwLwwCYmAVwQUzCgDpgAnfAQynwFEAbfAogCgHJEk2BKAKE-IQywNDAAGGapQBciSknwB6CADckAagAeCegBoApAGYAwqpTb6kVGwAWUKAAdpixQHd3xV4eIgySRQBMAAwhympsMABmcPT01mDg-BGucBhQNtYALBE2-HBIdtYAjCFBESpw-K4AQiCa1kEwjZkwAJxlRrRGxhj4kRCd3fRwYFRkAOJklBiVRPAY1pQRSFMzhFAAKlOQkb4I1mQgUNT4LO3cbIMm0CAOMCCR_fhQDfoBAKwRNw4AtKD0vgOSAARpQWAA2Vq6GBFTKGaEfd7QoLEQwXRRXUxQW73R4QZ7Wd5BN6fGDfP4gAFkIGgiFQmFwhHvJFNYgBdGY764p4vNglYkfL7Y37_QFsPy0yHQ2HwmCI5EcwxdEyKYajSgTVazKCYxS9fqYijAWApNIZNgBHJ5Aq89oRMj1NhlKIxOJsHBkegsN6GSiK5XGI2wR2WmCm9LWUO5fKFNh2mAOhoRaKxaxQbYQBwa9ZsDFK7phJCdMS8Xi3KBwcCiADevBgME0AEFNHAINIYLX6_WoABPBz4dtsYAnJC-HtsXR1ruSY7tgDabAAsuAJzA2BscEloWwAOr4DCr9c2HCHgBiZDgh4AytRrzgwGwALqT-sAXxfMB7zdb7c7Xd7_aDiolD0JuE5Tu-U74he-BtjAc5TvWf5dpgUjzkURIIoYQQIgEmQIkUAAc0qGCysIAOwIuCQTPoh_59gOa5qludH1tmlBXr2jC_qxXaimQPEoUJ8AIPIjGcB-wn1hQ_bUIOMlUFAPyaOBUkwJBwkaV2r5To-vCvgA3EAA)

### What does the proposed API look like?

```
{
      color: {
        image: getLineChartAreaStripeImgEl(options.value),
        repeat: 'repeat-x',
        stretch: 'stretch-y' // 'stretch-x', 'stretch-y', 'no-stretch'
      },
}
```

**Comment by helgasoft** [comment]
But [areaStyle.color](https://echarts.apache.org/en/option.html#series-line.areaStyle.color) (from your Example) does not support images...?!?

**Comment by He110te4m** [comment]
> But [areaStyle.color](https://echarts.apache.org/en/option.html#series-line.areaStyle.color) (from your Example) does not support images...?!?

Yes, I'm not sure if it's the documentation or the type.

In the TS type, this configuration is of type ColorString, or string.

**Comment by He110te4m** [comment]
> > type ZCOLOR, and can be displayed in the playground
> 
> Having a 'Z' in front of 'color' just disables the color attribute because 'zcolor' is invalid. Please provide **relevant** Example code.

[areaStyle.color](https://echarts.apache.org/en/option.html#series-line.areaStyle.color), which is configured as a picture, is used in the examples mentioned above.

![image](https://github.com/apache/echarts/assets/16161582/a11d48e1-ffa1-4c15-bc43-5b1f37f43e35)

**Comment by helgasoft** [comment]
The problem is with your SVG image. If SVG image is correctly set, areaStyle [shows OK](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBAlgWwOYwLwwCYmAVwQUzCgDpgAnfAQynwFEAbfAogCgHJEk2BKAKE-IQywNDAAGGapQBciSknwB6CADckAagAeCegG5gAC0pkI-KKhxQAZgA4ANAB5VKFXHwB3AEIhNqAEQADDBBAIwBAEwALDBhUX4w7nAYUAb-IenxBvhwSAbmfukh8Sr4JnDgacRFMNr0kP55UAAO0oqK7h3E7gDMxCBkSIrhASPKan4AfA5N1AaY_gCyAKwh4TA2S8Td2zv0UQCcxABsMOH7NsdHV0cA7AAS4UfhxJEAXpMOijMpU99zGItIo9LtcbjBusMDCEbgEQdcVEsbkcDABaaGw67Xd5TL6zHHOCZiXhtARCEToNiNJoQVqKSgzQz4PoDRScZQ4JpNfpQFH0yiM4gAKyaXF4ICaUHKYFEAG9eDAagBBTRwGkwOUKhVQACeTXw0hgbGA1HwSH62rYdnlmskUBkMAA2mwFuBLYaACo4fButgAdXwGB97oMOB9ADEyHAfQBlagxnBgNgAXStCoAvqmYNrlaqDTKYBnraZI_g1Q7rQqNZqFbb7Q6QksAnZTt0m6cos3wiF7DFuktmyFIjdO0cAimK5qdXqDWx6HAwN7M9XjFRozrGHmJ9XQPR-pvqwf4Ah5Pqj0hm1uD20KHrqDOb1QeZpLZf00vNYXq2nrUneGndEAA).
📌 please close issue if problem solved.
