### ISSUE TITLE
[Feature] Add an attribute, `title`, to the legend?

### ISSUE THREAD

**Issue by Lazydd** [apache/echarts#19345]
### What problem does this feature solve?

When the text is too long, I will cut it off and move the mouse up and it will display the title. If empty, do not display. Similar to the title attribute in html

### What does the proposed API look like?

```
legend:{
   title: 'this is title'
}
```

**Comment by plainheart** [comment]
1. Do it with pure HTML/CSS rather than the title component of ECharts
2. Listen to the `mouseover` event of the chart and set the title when it's overflowed. [Demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQAqAFhAM6yOwCGsWMA5h979D0y5KAGiLowAJwhcuOSQFEAbjmgUMkgK44xxEuQDKYAJ64CqPegDuEACZhaBAEwAGF7svAVkgGacrVFKa0ADGrGA4lOKwAL5EMR6kAIKkjObRJiD4sJRhEVzAksai0bbhrAQA2pQAsjCiOdTaDZQA6ji2LXSaLQBi0i0G4YPBlAC68R7GKWmEepnZlEqsWM2TRAzyEDgMVdEWlmVgFbCVAIwArO6wTgDM105OACwiN2cAHK9ntxdfTwDsrycADYXGMPPNjFkqFgINBItE4ugJjEANwoFAAW2MAGFaKxJGAAHQwAAUlExwE0my88gapJwAEoEAA-OawEIwBhgDn4wk4mDHOHyBCwbF4gnEuRgAAiwExpMZ6PQEB8sAZRM5mJAMFUYGoUJwsAAhPBEJQhJFmQd0CE-WABWpWMLJETLaLKJRlcRJDgwJpJNBvUiOVyeT5NFgsNQINgjYhQJAYG7Y7g3WQwN7OdBubAcFGICAGBAAF4dUU4Ik4FRqN0E6VE7mmSsRcgms2wCNRmNxrP2x1C-Gu92IfOwoul8sAfk7kejqaNVC9KBiSox4vtJOg5Mp1JwVLA9KZrPZ2dzdslA-dQ9FG8lROlcoVa5Vao1Wp18LUBqyCA7FoXShrWiC9-UFa95BTOMPWXdA4lXVEgA)

**Comment by plainheart** [comment]
The legend component can't accept the HTML parameter for now and we have no plan to support it yet. It's easy enough to use ECharts instance API and HTML to make customized legends.

**Comment by helgasoft** [comment]
try [this](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEksByTxUjVQrFF-ZFhoRgBbGloAGwhoKlgALyTklNSk3iDBYTEARgBWAAYeWAAmAGYi0pKAFmKSnIAOYpyyvObqgHY6gDYC60dSdApqOhi42iDPQfR3UIiCaNj4gCNVtfWM6dghMBEAwuKKutrYRsO22E7i3v7MskoaWTHlSZJb9Ci2KmgBAndPgBmYAW1QKAFJaB5iiRIGBPn88ApliwMMDol8fmQIHDIsVsVQwgBxRggAiVIysbRo3oQuwoOwAbiAA)
