### ISSUE TITLE
[Bug] 折线图设置type为time时，渲染出来的数据概率性丢失无法渲染在图表上

### ISSUE THREAD

**Issue by ysswebdev** [apache/echarts#19369]
### Version

5.4.3

### Link to Minimal Reproduction

https://codesandbox.io/p/devbox/nkc39d?file=%2Fsrc%2Findex.js

### Steps to Reproduce

进入链接，和鼠标移入到tootlip最后一个数据，对比传入的data第一个，能发现对不上，建议直接用edge浏览器测看看

### Current Behavior

图表最后的节点与实际最新的差了好条数据，不同的电脑不同浏览器表现不一致，目前我自己测了三个人的电脑的chorme以及edge浏览器，一台chorme无问题，两台chome最后的图表与实际差了10分钟，也就是10条数据，1条一分钟的间隔，三台的edge都有问题，两台也是10分钟，一台5分钟

### Expected Behavior

期望图表的数据是完整的，

### Environment

```markdown
- OS:window 11
- Browser:chrome最新版/edge
- Framework:
```

**Comment by plainheart** [comment]
这个能否提供渲染图表的 option？

**Comment by ysswebdev** [comment]
> 这个能否提供渲染图表的 option？

已更新复现链接，里面包含option

**Comment by ysswebdev** [comment]
> 好像并不是丢失，而是 tooltip 识别有些问题，可以把第一个 data 数据项的值改大些，是可以看到它被正常渲染。或者增加 dataZoom 组件，缩放后再使用 tooltip 悬浮查看也是可以正常看到最后一条数据 (1701932006234 / 14:53:26)。

这个能优化吗？用户不一定知道要缩放，这种我们开发自己都没办法识别，更不用说用户

**Comment by plainheart** [comment]
你看到的最后一条不一定是真的最后一条，数据多的情况下，tooltip 识别似乎有问题，最后几个点难以选中，后面抽空会研究看看逻辑是不是有缺陷。

**Comment by ysswebdev** [comment]
> dataZoom

我尝试配置如下dataZoom然后缩放到最大，也是取不到最后一条
dataZoom: [
    {
      type: "slider", // 缩略轴类型为滑动条
      yAxisIndex: [0], // 对应 Y 轴的索引
      // 其他配置项...
    },
    // 可以添加更多的缩略轴
  ],

**Comment by helgasoft** [comment]
I think the problem is not tooltip, but **cursor position**.
When multiple points have same Y coordinate and very similar (close) X coordinates, axis tooltip is different at different cursor positions. And that makes sense.
Right of vertical    |  Left
:-------------------:|:--------------:
![image](https://github.com/apache/echarts/assets/13038071/eeeaf611-f184-4698-be87-10d457867bcd) | ![image](https://github.com/apache/echarts/assets/13038071/66da4fb0-b41a-49ce-93aa-b89619ec7da5)

The solution is to set ```xAxis: { type: 'time', boundaryGap: ['5%', '5%'] }``` so both sides of the vertical axis tooltip line are visible at chart's edges.
[Demo Code](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=CYQwLiAEC8kNoChLwIwHYAMKCcBmATBhgGz64AsANJAET7EB0ArBjQLqVKqY647nE--agHJ6zDCI5c46LHhQAORcXL40o8SynUuAej0MjMuekX5yaJmuybG2SdOSyeac-RzZyVSGPuPOZAMjBhMeYncrGzsGBx0wrAiLT28YuKduRPNcJiYKW19xdMDMlCT8bCY0ejTHBDYAbgQEAHsABzAASxaAOxhIAG8uAA8AQWHOgGcALkHILmQAIxaAVx7QACcATwBxEDbZuBEmAFIRUVP45GQwLbaAU1mRLoBbe_OuAF8SrfGp2aG10gtweTwAbiAADYrd5fEpgFotSFdA6DBbAjadADmWPuGyeIAmkw-yG-XEmeM69xm8HRgKBwLuj18kM6PXeJSBoAgs25IE511Z7IAyrdIcz6QzIABjJEtfG-ADE-RQADFRiSpZAAO6dYBgAAWsxQ6NJ6M-XDYCE-DSAA)
📌 please close issue if problem solved.

**Comment by plainheart** [comment]
@helgasoft Thanks for your reply. Yes, I agree with you. I'm sorry I didn't make it clear. As many points gather some place, the cursor can't find the expected point accurately. I also checked the behavior in some other charting libraries, it seems they have similar problems. I think it is acceptable and has no need to fix. @ysswebdev
