### ISSUE TITLE
[Bug] `on` API doesn't work on `line` type graph when `symbol: 'none'`

### ISSUE THREAD

**Issue by yogat3ch** [apache/echarts#19562]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/yogat3ch/pen/NWJXVwy?editors=1111

### Steps to Reproduce

The Codepen in it's current state will not log any events to the console. Change the `symbol` argument from `none` to `pin` or any of the options besides `none` and the mouseover events will start being logged.

### Current Behavior

When `symbol: 'none'` all the events don't work.

### Expected Behavior

Events work regardless of symbol type.

### Environment

```markdown
- OS: Mac OS X Sonoma 14.2.1 (23C71)
- Browser: Chrome - Version 120.0.6099.234 (Official Build) (arm64)
- Framework: R Shiny, but the example is pulled from an echarts demo
```

**Comment by plainheart** [comment]
Do you want to listen to the line or the invisible symbols? If it's the line, you will need to enable the [`triggerLineEvent`](https://echarts.apache.org/option.html#series-line.triggerLineEvent) option, if it's the symbol, you can set the [`itemStyle.opacity`](https://echarts.apache.org/option.html#series-line.itemStyle.opacity) as `0` rather than set the `symbol` as `none` as ECharts will skip to render these elements and cause the event not responding.

**Comment by yogat3ch** [comment]
> Do you want to listen to the line or the invisible symbols? If it's the line, you will need to enable the [`triggerLineEvent`](https://echarts.apache.org/option.html#series-line.triggerLineEvent) option, if it's the symbol, you can set the [`itemStyle.opacity`](https://echarts.apache.org/option.html#series-line.itemStyle.opacity) as `0` rather than set the `symbol` as `none` as ECharts will skip to render these elements and cause the event not responding.

Ahhh! `triggerLineEvent` is the ticket! Thanks @plainheart for the help!
