### ISSUE TITLE
[Bug] When opacity is specified in bar chart the border is rendered internally

### ISSUE THREAD

**Issue by blackat** [apache/echarts#19603]
### Version

5.4.3

### Link to Minimal Reproduction

https://codepen.io/blackat/pen/KKExXxd

### Steps to Reproduce

I have just add the following code to your example
```js
color: '#37A3EB',
opacity: 0.5,
borderColor: '#37A3E',
borderWidth: 20
```

Try to remove and add the opacity, with opacity the border is rendered internally rather than externally.

### Current Behavior

The border is rednered internally and not around the column.

### Expected Behavior

The border should be rendered around the column.

### Environment

```markdown
- OS: Mac Osx
- Browser: Chrome
- Framework: Angular 17.1.1
```

**Comment by helgasoft** [comment]
> the border is rendered internally rather than externally

Yes, bar border is rendered 'internally'(inside the bar) so that **bar width remains constant**. It seems this is by design and not related to _opacity_. 
OTOH [opacity](https://echarts.apache.org/en/option.html#series-bar.itemStyle.opacity) is applied to both bar and its border. [Demo Code](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxEksByTxUjVQrFF-YlJSITARAIBGAFYABh5YACYAZnikxIAWBMTIgA4EyOTogoyAdmyANljrRxCyShpZACNGDl4g9AgWAFsTCgAbRtQ60npgfs46AGJk0qxkgFEAIXaR9AB6ddBGei7yIliAOmKO0ibOAR8AYXHJ2Q4NGU3aGbnF1bXzjkuOVQgBMDaIiJWKnOxBcHoWx2ADcQA)
📌 please close issue if problem solved.

**Comment by blackat** [comment]
Hello,
thanks a lot for you answer, the issue is that the border get opacity applied as well reducing the contrast with the bar color.

Finally to obtain the effect I wanted I have used the rgba gradient as color of the bar, in this way without opacity the border is visible as it should.
