### ISSUE TITLE
Co-ordinate doesnt match on global area of map 

### ISSUE THREAD

**Issue by neonarc4** [apache/echarts#19795]
### Version

5.2.2

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/exciting-mayer-rdvvrn?file=%2Fsrc%2Findex.js%3A11%2C34

### Steps to Reproduce

lang long is showing in wrong position 

### Current Behavior

cor-ordinate not working

### Expected Behavior

co-ordinate is based on country how can we make it work ? 

### Any additional comments?

@MatthiasMert

**Comment by helgasoft** [comment]
> lang long is showing in wrong position

correct order is lng/lat. And many other things to be fixed in the code - [Demo](https://echarts.apache.org/examples/en/editor.html?code=CYQwLiAEC8kNoChKQN5OZAdiAtgUwC5IByAWQFccAjEAS2IBp1kA3EAG3MPgHYAmAHQAOHjwDMQhpACMATgEAGHgFZZKqdIC66AL5NkaDFlzdiAETzsAFvX0Y2nbnFEC-0gGzuhfKXyEDPd1FlX21kPXRDDGx8ImIAZTpMMEgABTwwPAAnAGcqciyAc0ZmSAcuIjgxBVd3ABYfSFVhWTq2qTEwyAiDUpjTAAkAe0xCyABpEeK7Vg4K-GlpOoFpZR53WUa-QT9lZTcpOq6e1D6TOIBBHBzMrNAcEqNyp2WhNRCmwTEVWSllY7sUWQ_TiiUwkAAYlkQJgAMa0HKwoaPexzJwAWmk2wEDTqH2-Ah4QgUv0g7mOCE0AG4EAB6WmwsBZGDwL58WQfOr-Dkc6kIIYABzAtBGLKihTwQyIQMgYAAngLTDgQAKUchlQK4gB3IZZdjANWQLJDXBEJlcGaQemwvDJbJERlZS0ALyGQxwRB8ujsYDd7GFmtQ3SY6BosIA1oVjeRMMAAMJDdi6ogAIgAxNIqJnMymfbQwOxuDL6ZkAB5gOIAGRARTw6MRHDwkDwADMW3hGTlDTlyFQyxWSBDaIz8yLyF3LaW4ja7VlDf34vLC9LSsgkUmsnE022W8RSjpvehCxLYyujLraLaB8QWNlhbCOIapyRCy2wPO8OXF3Ll6cjGvE2TEhtzbPcjAPcIfT9KghmfGUcisIYtTNLILVKC8rziW8snvR9JziLJaEKKx30tOVpyvbJDXbcACiLVdIGVLJw2lSAEKQlCuGDBjQAgAA1S9kKDdihPNPApCyPAQGAAB5TB2HIyAWw4HImxOIxJJuXUizYxDRNQtTLWQHIQFvC4cgASWVCVWJEzi1P3Q90FUwi8BySpShlYFzhIAB1KS-HDQ1kHlRU4gbMBbmCyAkV1YBaGwTJ4jlG48A9EgJWRIyYsAzcSEkg1st4kAiGK7LfUTANWIY5AW11ZVIvtSAAAoBQAShgAA-INJLAApwQFAR-gAamIaBiGGwbnjgPhqW6SAGIgjAlu0HQqSAA)

![image](https://github.com/apache/echarts/assets/13038071/91a8a5b1-6b06-4fd2-a2b8-b838f81745cc)

**Comment by neonarc4** [comment]
@helgasoft  thnx again bro u always help  me >.</  love echart people so much helpful

**Comment by neonarc4** [comment]
@helgasoft sorry bro for disturbing u again

how do u color any map like i want to pre color china map yellow 

inside geo:{selectedMode:'' } but i want china by default

**Comment by neonarc4** [comment]
@helgasoft sorry for disturbing u bro where can i get this data https://echarts.apache.org/examples/en/editor.html?c=lines-ny

like i want to get china or russia or any other country data

**Comment by helgasoft** [comment]
@neonarc4, your link example shows **data for NY streets**, you need to search the web for similar data for other countries.

If your question is about **map data**, then see the following:
https://github.com/johan/world.geo.json/blob/master/countries.geo.json   countries contours
https://github.com/nvkelso/natural-earth-vector/tree/master/geojson	lakes, airports, countries...
[Official Example](https://echarts.apache.org/examples/en/editor.html?c=map-HK) for setting a _geoJson_ map in ECharts.

**Comment by neonarc4** [comment]
1 last question i am bit confused https://echarts.apache.org/examples/en/editor.html?c=geo-svg-traffic

how u get co-ordinates of x and y so accurately is their any software or tools 

i use inkspace and gimp but it only show 1 x and y at a time   is their a short of tutorial

**Comment by neonarc4** [comment]
to  be honest bro i didnt understand new Float64Array(rawData.length - 2);    

like how can i send the response.data from my server  and where i can get the streets data is geojson
```

@app.get("/data/{chunk_id}")
  //return {''what should i return here"'}

```
is any hint what type of data shape u return in that example

**Comment by neonarc4** [comment]
@helgasoft  i was bit confused of this part 
   ROOT_PATH + '/data/asset/data/links-ny/links_ny_' + idx + '.bin';

@app.get("/data/asset/data/links-ny/links_ny_/chunk_id}")
   return{ }

isnt the street data on google  gpkg or mbtiles or obf format ?  if i can see bit backend of urs that i can understand how can i make mine work 

if it was gpkg and u convert it into bin chunks am i right ?
