### ISSUE TITLE
[Bug] 对数坐标轴设置 customValues 后，区域缩放过程中，轴线溢出坐标系

### ISSUE THREAD

**Issue by Jefy-Wang** [apache/echarts#20157]
### Version

5.5.1

### Link to Minimal Reproduction

https://jsfiddle.net/vb31ezm8/2/

### Steps to Reproduce

1. 配置对数坐标轴 customValues
2. 配置dataZoom 
3. 鼠标在坐标系内，滚轮滚动过程中，对数轴线会从坐标系溢出
![image](https://github.com/user-attachments/assets/2a583b6a-5af8-4cf1-8f17-419a8c6b452c)

### Current Behavior

对数轴轴线随着区域缩放，溢出

### Expected Behavior

对数轴轴线随着区域缩放，不溢出

### Environment

```markdown
- OS:
- Browser: Chrome 126.0.6478.127
- Framework:
```

**Comment by helgasoft** [comment]
Apparently _dataZoom_ does not like _min_,_max_ values on a log axis. 
Also please try to use **minimum** instead of maximum option settings - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=MYewdgzgLgBMCu0QFsBqBDANvAphGAvDANoCMOAtAEwAsANDOdQMwNNVVuVWkMAMbNnwC6AbgBQIAA5QAluEIwA3uJgwoOAB5QAylACemHAC5lqtXBCYQAJ1MByAMTMX9uubUAzcLoNGHYLbIWG4eMN5gUADqOLIA5gAWUAFBIe4W4T4AYujIspj6DgAS6DbI4PoA8jowOuiQtQDCoRkRurIAXiaMVOYAvunqIFZyUqZKA-ZxNrIAJuOWkeiyYAAy6ABGOJimUDa4MJNq-gCCmrIQpsRhKhlqBlLd9tZxbjBguSbPIK-DGQD0_xgeTADlm6Cg6AAsis3sFNGCIdD0JoWncURdViturc7moIAkQAB3Xb7HB_O6YbF6Qw4sJ40DWOwwJyzYCzHA4ZhovFqIlzKAJUykekWPqio7o84QdZbHZmXkwAnE0m4CkZBBINBYXAQdUWbxlCEaZkACgAblgAJSEAB8MEtmBgAGoWfYJfqMRAACqyYAAa3GovxhJJ6jJ-rUmqgKAw2DwkZgVLAOBp_gVissTIcjj4efzPN5_NmguFwcOiaMYDipZg1AlYXFamEg00ZwuVxuoogUipUCxKYWyrDniwEBwFdFIMRkJhYELanhM-RqM90oHdMVydTfk3mcZthzbI5XIXd2LtZFiqbdxvahvLfM45meE7GVxGQeT23Z4-yCeACiUKkGeEDlCAtZ7Gqorbmme4MlYh4so4VAAGyoVQHJnnyApCjAnAeqKsgaMgcFBoqB7Mk4ng0bR2EwBstgcjYUS4aYBGKoxNjMY0iFUSh6GYTgZ6Shkw46PoyCMfKUHkt2knSQ4wCyDYwBGGe4KQm-vJkPwAB0-akAA7MwRmPoqxCcDAfAGVQACcRmkOZOmsDARl6TQZmJsQ9CMHpqHMOwTneQArAw7moQAHHZ3DBeWxCoQwqF6cwIU0NwNDOXixBGQwVAGUZRmUKQkVZXcxCRQwkV6VQRmodwIjeXZbA1VQIXFaV3mkAIMDVXZzAxRQpB2cIoplWoRhxDgYCzEUIDmjgNgDoG4bQXiODIFICToBAHYZniEDAFg3SyZWmzbOMd5io25jOZp6AAFrDMgCxfg4Ky7VhDCePkJpQiAHIpCm9iHOIfSiEAA).

**Comment by Jefy-Wang** [comment]
Thanks for your help very much

helgasoft ***@***.***> 于2024年7月15日周一 13:53写道：

**Comment by Jefy-Wang** [comment]
感谢指导，该问题非bug
