### ISSUE TITLE
[Bug] Name attribute of markLine is not shown

### ISSUE THREAD

**Issue by lucajung** [apache/echarts#20150]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpAC2jBwA1gAyvd7uCYlgIjFxszOzHtCMg960AHIbVLDAAGZk2vvDYxG8S6vYuNEARFLQ99cedq-wtrPvbyS2dgBuIA

### Steps to Reproduce

It is reproducable in any chart. You just have to set the options like this: 
```
option = {
  xAxis: {
    type: 'category',
    data: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
  },
  yAxis: {
    type: 'value'
  },
  series: [
    {
      data: [150, 230, 224, 218, 135, 147, 260],
      type: 'line',
      markLine: {
        data: [
          {
            name: 'Name of the marker',
            xAxis: "Mon"
          }
        ]
      }
    }
  ]
};
```

### Current Behavior

The name of the vertical marker is the value of the x-axis.

### Expected Behavior

The name should be the name specified in the options.

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome 126.0.6478.127
- Framework: -
```

**Comment by plainheart** [comment]
Not sure if it's a bug. This looks like a traditional behavior that the name will be ignored if it targets a specific value rather than a coordinate.

A workaround is to use `label.formatter`. [Demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpAC2jBwA1gAyvd7uCYlgIjFxswD0y7AK4bD-jABGVP4AdABmnMNgLBxkVIMg2yywfka7_lRLCTOzHti40QBEUtBfgNPrBoIxBt5aAA5cFUWDAI5kbRw4ZjCK8N6zbZ7fxuTGfE4cM4XOhIHZ2DEgjx2fHoBy02CreGXDZw7H7Y7AQYcZgXWACCAcKj0MD-cgMj5U76uWD_GBAhnodm4-JUjyE4kROgwiHwxFgZGwVGjdHAz40tUWz62WZWukkWx2ADcQA)

**Comment by lucajung** [comment]
> Not sure if it's a bug. This looks like a traditional behavior that the name will be ignored if it targets a specific value rather than a coordinate.
> 
> A workaround is to use `label.formatter`. [Demo](https://echarts.apache.org/examples/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAeBBDEDOAXMmurGAJ4gCmRA5AMYCGYVA5sAE7m0A0J6AE2aMiAbVoBZGL1i0AKgFcqM2gHUqAlXIAWClQDEOEFQGVmphdFoBdEgF8-6cjnxFUpMpRqyAbowA2SrT2jrB4VEZUhLCi_MQegsJiAIwArAAMPLAATADMmTnZACxZ2ckAHFnJualVRQDspQBs6dahHhTUdP4Q0MrtpAC2jBwA1gAyvd7uCYlgIjFxswD0y7AK4bD-jABGVP4AdABmnMNgLBxkVIMg2yywfka7_lRLCTOzHti40QBEUtBfgNPrBoIxBt5aAA5cFUWDAI5kbRw4ZjCK8N6zbZ7fxuTGfE4cM4XOhIHZ2DEgjx2fHoBy02CreGXDZw7H7Y7AQYcZgXWACCAcKj0MD-cgMj5U76uWD_GBAhnodm4-JUjyE4kROgwiHwxFgZGwVGjdHAz40tUWz62WZWukkWx2ADcQA)

Thanks! But this behavior is not [documented](https://echarts.apache.org/en/option.html#series-bar.markLine.data.0.name) and makes no sense to me.

**Comment by plainheart** [comment]
I'm sorry for the misleading documentation. I will confirm this behavior with other team members and fix it if it is taken as a bug, otherwise, I will update the documentation accordingly.

**Comment by plainheart** [comment]
@lucajung Just let you know, I have confirmed this with other members and they think this is a default behavior. I will update the documentation and add a tip for using `label.formatter` to customize the marker name.
