### ISSUE TITLE
[Bug] VisualMap on series-line no color the line

### ISSUE THREAD

**Issue by electroheadfx** [apache/echarts#20298]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoW7YCIDmAnCAJpgFywDaaGVqVtGmANgKYBmYJsADADSV1WZ82ABbtSPPv3SYA7oTDCOmAJwAWAKSZeUgcKYQRY2AA5OEnfQDOw4DI5hcAVybaLWQh3NvMYUJ8lUAL6SALqu0gAeAIIREJYcFFI03h7i4To-AJ4gTEqQALa56VKY-RDQSgBMnJWVALScAGwNygAqAIzGxACsnMTt3VoB_KUAhhFVNfXt9TUdfZVdqsZDblh4hACS0ARME2nDdJgARsCOO6O4mQDioyAcLKMMli6HtJgAXhyVxSPjcQAFYDlMBMXAcZJraSWaB3exOJhvIK_I7_SwAGVGxyYDAhSJG1ls8OcKIyAGNgAxgODSJgAMTKRmrKHSABuYMgZKeUQYBgqtN891JJV50CYAAl9IYOO1GsKRiwYGAAOpS0RKU4MIjyo6EmQAWXKmOxuNIj2erxZ0JsBvGxpxDyeL3x6ECOqwaPR5VypEhUMweuJlqtjG9AGUwJlmHire8KVSaVg6e0AGKVZQAZgA7JgXbRgms3XmAyBeWAvWKYyHA6QHCS8wJRUwI1GfcgGyN49SlHSmH3c7GC24i2tMGjWhAyQBrKssgM2oPuxtMaDYBQcbpL-hNlvR30do5dxOyYQQUEDq1DixX_OhdKYTIxOIJN5-kqpLjurI5JSsp7OZkLBwfACG2XZ9k_YtLFLM8KzbN9vB3SM93bWMBDkAh13EA9YBvKQR28EBgEsM8oH5LAhHVL8vlIdovCAz1vVnf0a1gc1nULL9x0nGd91jeciVrBEt2kZhVyw2BNxw0MxV3eCcIEI8lBkU9zxwvD-AIhjYgxLEHT46sbX1O09NNNinWDOclNpBkmRErB2VwTluV5bByJ8Px7JkiU1SMOivMVaAwDDCAPjbfzpPyS5sHKDc8y0jIynI9pVAzOViyiiCUqzVQ3hvMJJADMEICYeJSESfgEKOD8ivwUq6hAXBSpXMA6ibQCMkjH9aXar9YUKJQXjq-IvwIUYwFGF9YwqtCsHaDr-MaRoFpDapagaZoUtaTgs36ZRiE4DMVrnKIAFVWgAeX1KJWk2ABhY6oRS7pugAOmUKTZvQDMcIK6aFPoSpHtHThge8NbZk27ptt29p9sOsGLGgRwGAYeyqGexpXozF70YwH7Yz-q0ZrQzBVERjJQbx6QIY2up2izGG9oOo7qdgZHUbZ56s1e2VPq-gmrSJlkScWimSipgGaamOm4aZuGWfF_gObRqXYG596s352bBZZYWoVFkMczZzBJa-rBaaaOpqnl-HWbVlWudUbpjGx4w2d1qF9bWQ25xWE2za-zBLeaSp2ltxW2cdtXntdrNjG1tDPbWb23F9_1lCVo5A9m4OZat2oI4RqOUdV83nuUXnlA9377PT0d2nmk3OkaJu1bz9aC9UVpqgOvozCz94ADkLoAJQAUTui6ADVx9HgBNQeMdURp6KT2ucPr7wc9Jnf-MtrN6eMHvKj7vul4waPzavr7csJuv27Si_pE6F3n4t_PD7l2oz4Hk3rqHqdKI6J34pVUGvWM7QN7_XNpgbM79TYIIPtbTgJ9f57ytDfWaYDOC8zDlzaBxNH7-3bhgucyCw5oLMOfEunMY6qHAa9Soqgfgx0ISLdu4CEFkP9BQjMVD-48LWFgtCODXrLETpA9hBtOFt1gUI8Gn9rbdx_tQv-DtS5O0YavdK5dpE-04UDAOSClGVGhqowR78RGQIYbgrMlQswEPvpvTh9t5EmM7ofSojQBE0I0XQ8utjXrGGWE4oWD9YEMO4R42YXjGYWL8dfTR9DGHKEcWw5xMCg6qGNqQmJDRD4ZlQQk9RSSAlfTAe0bGGYMxhL1hE7JJD3Em2QRmcOJSFFI2SYE1QVTnaSKtFAzJRDImZ2MS0_OxgGjtNPmozpOhrGDIYVU7oWZdEVP0WnduvRokTM7lMuYHSrHdIqcs16jQ0l1K9rwFxsDuhuKDvMkolsDnmNmZY2hZdTksNek0doVyU4NNzt0cm4z24vI2r40pX1FksjAZUXmxhWF6OGRwu5gwwWwIhTtKFTzlYnOwQwhFRTakZPCbcoO3RlqYqDti4-RzPlaIRSw1QAK3CpwsFvICb8aW5whXRXFxzymEp-UtdJKLyVZOBWMvJezZhTMboKxlKSEXx3dmS-pFLc6r12eCyZ9NKhKv8V8kVCLlCcGrhq65WrSat11Vi_V7R-EMuNVojMvzSUSs1VK21Dzc54qOPyt56ChUmtEQw91DjPUbNRTI2BjRQWyr1fs-mPiXVlLDTY1K2M1BsosBynQXKMiNAxUmh1KaGZGozW6163QBh5p0AWqQRaShLXtbSx19L3mJJhQS8N2bGhpQbVIJt_AW0jEaLk5pyb5X0zaOm3twr-3uq1uqr11qfWLRlbA1-26O0psoZ0ENJsR4TynrPBeoCGGsqtYCm1_EswBveE-gQELC5HrmaGrRb1swDJZJUTZnL25ZjkY8_JnApmVH4R-j5rqUlYy1mzADsaDGwPse2vl-rmEdC6J-5VPTXYzD_VCZDkqRlByzH63e4HIPQxgz22asKnoMMrsRtYpHvXkdzjlDDpM30-Po9CxjfabG9GCYhtWyd2VAtJms3j-8sPH0Ey-y-Imln3POWYmuKGtloanUHFuKnpYHvnd2oTpNT2TxnnPReTtcaScA4WstYG5UtAaM6szRn2ZqZZExtYUn80yf4sYKj_EW5GJnW5zgKjPMIIAUAkBWiIGDMc829uIT5OrXzsoBowa8NwZ6bg5FMayNoqDgnTL5DsuQoXcJpdWbcE3vXXezdIZjDUuc5hzuOWcW1bQn5twYj1nYNS2O9L-n_XgZ61249BXvm4LXSVzjZXc7GD3ZN1zFr6bFNi_h75VTisjZ00B2ByhQMbci1tmYVbF2ZqWb085w7-CjroOOo4mYEEt1C1l7r9MYuzdgZZ89Nmr0sKe3QF7tA3vvDUJV3h1WBg3bq3duFRLxHg9oJDqg0OBAfTh6OS2OXZRI_6z55jPzFtHdK3GoOygOvTvLbMIn8TdtzZFZGjHVAscYBx_QNJ-PFG_c6CT2MA2LBgPdcN0Ro3Xvt2UE0lzl2iemYB7drRTWlsbq46TOynW-PVZtn10XZO1hgNUOj290n70hjol5xBm2cuUKN5gk3g3r3BM5xgbn6BecvxqALoChPrYedV8j79j21Yca1yt0mdFvtzhbomxnbnsPO7nED6zl6tFS9jFHlOeZIeYGiDpMCexPBfkfCXnYZeDijhopJL8NhHJRGgBAKKkAYCLmLKMVv7eyJd9HJYTI-RNQhTChwDXQEh8j8pEoMkEBcBkmjF-FcBB7RmSqhkVi7FEScWLAwUycFmKD4XGaCy8UV_QApLsY_3hfCUkgPccqkm2Z32p6OCCh3_SZAnxf_f4ZkJ5J-IMIJIv9Rwuo2wAxKQPA_9RwzwmB8g5Jb8gJrJ1hcBRgf9YDvAECQBhBRgSIypUJqwuQUI6xLJ_R4DEDADkD_RThcBdhcBlR5BFBSBGh1J4o8pSRN8BAaoFAmpCQtQ6gvE_sS0KZvxIDepix-pIC-DSobBBDJDRwxoJopptcFN1oZgGhDU6JiBFhiBlgr0S0ZcodLtmgLUcMeg-gBhDDuhfoC8vxi84hS8IJksjhK8nDq8XCvw9Qwxh9NRHQLRG9gBm9e9xp-8z9Aju9QiO9yIyDvC_DKQx82xXD3h69GRLVRxV918aCShWI4jpJUD6QWAzAmAMwk8QxApgpQpwoUiShKjVQDB1RaRNQiAsCgID8TRMRMgzgjBuCRhTxdgLpHID8n9YB8j-Ing-QlBmA2BB5MACAvDpICAf9WC2iMgOicQj8DI5xt9z899RwkJWwciRgIDBpoDtRpJQBRh59IxPBa0vJCi6RijOBSjyi5wQCWD1Y1iSgcC8CCDjjdQSC2wd8ApgAyRHBCDMBoAYBcgOD8IuDixeDhB-D5CCA6gMx0S_sdkvxTieomI-pRgBoBRkS5DKQ0TFDvBlDJpn9WsqsNDZhtCFglgFdCVehjDsdTCWgLDeh-hS1Ak2TCZ7DixHDLBnDy9ix3DRTPDxST9bBfCZ8zIQTiwm8wQW828wjO8IiXh4iFSkiZTvA0jGRL819TIAT3g8jhICjKRuwbIWAWAyRTAn1MBKi9TaJaiFQlQGjpRmiySLxrwvwNiGAuieizTdBCAmAhiwQRiB8QxJi3JpjWB2AvIFj9S5xliOA2D9jEJD8mJtiWJT9zILRviRhDiUI-ijhcSsBLBzi5iribiViuB7irSEwew7SHTzNRwPiZRiyjhfj8Dnw8zB8gSAjtTpJFRwTIToTKw4TNIES4CiBiSUSyTrY6hVA_tnYxDKzvIxDpC8gSSBDyT8TiwqTVCY91DpgGT5hdDmTQdbDjsnNk8rZzCj0eTrDv07CWtvARSxTa9vBJSfzIJZSZB5T_CtTyCSgVTcA1S-9NTCzRzRwe91SYiYyp8EiGBXTAKDSOB0jjTsjBzvALT6x-JHjG5jgQkigxylQMKIp-J6jfINRfSez3hAzgzHBejpIBiIzhi4QhIiLYzXJ3IZikyljFj-J0zVisz2iczKx8Kp8Cyd8mLGwACjjZLOpshIDqzeQLj-I6yzwGzcE2NOxrTjxkx2gyLVAKLgDmDuzJKMg-z_jVLcjhywLQSJylApzYTCw8o7xCoqSAAtYAYAfIU82gcsrALc8oEiG_L8TKMMEAHvGUMwGK8oOKhK8QX5Qy6ECaJyVMuynYRK90yIJ8KU8CXKuoiABgUEXAfUYAG_WkDysQj4QK_IC6aAGqiEpgZUPQfSLAMkBwXETg18YsCK6AKKyyv84qgCwqrAFgCqqqmquqrABq6iZq1q9ql4LqvsMyecCAWYwapIYa9SwaLSsEMQ_86U38oCWayqsEBayA5a_ayqQ67qKsk68EHEvwUgELaaovSai6zCq6ua262q-6mEx6fKe8VkOIRwJ4YyUY9OMK8QpQEAEqMkJgOQF4MQ3YyIpQtvFcEiWCn61A6HekTgAgZQSoJgSaIUwfNCjCn6noi6FgUeHvbAIAkMQo8oAgAwYAOY6fUfao_wWykoFGpgNGwg6HMKkUU05ohgACE2JKDgIdduTKDMjIoOR4smimqmv0qEBKNYKWksmWrAY4OW8a3ORWr66NC28YAqk2TW8mym6mwceyQ2o4QMpQPAPsCoBW2KUgR9BW22_2620mEisy8i3W4WtwN25i424Cb2hBS29WTgf5FWoO9WWUe24ynsUiiO9SV29uD22kTIHEKkOwX25KBmQOrKJaLOls20-0x0yO4cAu2BIurAEu1GIkCumUau74SfUO7Ohu9s0GfOnCGOxsOOzusuxOv22AHKPur6sAjmoepMNspu9gz8qfYqUqACscVGZu10HygQe_SqiAUYzfMcHSIEEEU6xy-gLcskXAYieIby5EFAQIIAA

### Steps to Reproduce

I use time for xAxis and value for yAxis I setup visualMap with dimension: 0 (ID) and construct the pieces with min and max.

[Here the codepen](https://codepen.io/electroheadfx/pen/LYKrJjj)

thanks

### Current Behavior

It color only the symbol

### Expected Behavior

It should color too the line (itemStyle)

### Environment

```markdown
- OS: 14.6
- Browser: Arc 1.5.7.2
- Framework: x
```

### Any additional comments?

I dont know if its a bug or not ?

**Comment by MatthiasMert** [comment]
It seems that echarts doesnt color the line if the depicted visualmap dimension is not an axis dimension. Which makes sense because it cant tell where the breaking point, from one piece to another along the line, is. Since the markings in your plot suggest that the coloring is dependant on the yAxis value you could change the visual map dimension to the yAxis dimension.

[Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWsDmAnCATAXLANprrKlmwA2ApgGZiEAMANBWThgBaOyvvoA7njBdCAcgCcAFgCk4tpXRcaEbrwAcTfktgBnLsEGEwWAK41FSvMyuUwoZuwC-pALpWAHgEFPEPYQklKi6Nnx2ZGAAniA0EpAAtjQKArAJENASAExMWVkAtEwAbIWSACoAjBr4AKxM-BU1KboJAIae2bkFFQW5lfVZ1dIazUrYeACS0Lg0HeGpAEbAZtOtWFEA4q0ghHStVHqWqQBehFkR6O3-AArAGWA0WIQhuvrQ2ybmNKnOF7BXegAMq0FjQqM9UugDEZPhY_ugAMbAKjAJ6wcQAYkk2NGugAbo9IAj9t4qGpMuiHCBcUoydAaAAJVTqQgVIrw2B0GBgADqzJ4EiWVFwNMo0MEAFkMsDQeDOftDhzxRL2jKwbsFd9dL9UgDARk4uRXvpDMZYKY4ZDqAaAMrRWgQ42I5GoiQYioAMSykgAzAB2cRW1zav56EBksD6-mO17i2FHY10mh2qIOo1OpEotGYmi5wPG4NKHW6AFlCAIgDWMd0cfNXw5tGgGFEhBqDdt9sNL2Nmdd6MEXAgD3zr0LlDHsELHlIUV8_kC7G7ZDCOiU0ViEjx-wsoswOFwUxmc1XYvDQ6jXatSZTaaXumEuBbfCDPz-IGAeiHUAp4k4PF3pywBUJ5kHqBrVkotZ7AcWpFn8pbllW6Y1qa8YNjQTZPm2V4dqml5OrAvbZgOQ7JC-Ia6n4QIguqyGQaaKqeGqcrQYqVpEW62KSLu6AElgRIkmSGA_lSPHWvSTJqAKQEgZQXLQGANoQMchrARybRYBgGStq-qTpBSFTSD67J6e0rLSH60guO4ViHDgNABMQi6pGE4h2RADn5CAWAORhYD5Emu7roa4iBX87xJBI7kObuuCtGArQLsaRDiBUCjokURTpeIOR5IUJSGWUTB-g0kj4EwPrZd4ACqZQAPISt4ZQTAAwulhk1DUAB0khtrAPrTslOXZUw2W5b0BU1EVJUVGVFXpdAZhUFQLBAdINRFF1PqdatA0cil0gjWNXT5fkFR-tNpXlZVq2Lctq0dX6XVsn1e1WilWWreIo1feNp2zZds3XQtS0rWtNRPZIfqvYNrwpQGX0_eif3FPkOSA3NN2wHdYMdRoW0aLtsO6ClIyI8deWo1kFQY8Dt2gw963436Ggw_tUhHb9J1U1ktPzfT93g5Iz2SET7MVGlX1VEUkvI9zJRZNIZQ5OV9TaNlABydUAEoAKItXVABquvawAmu10hFKw_XE0oKVI99FO9H6Z0aMrWSq6rIOCzjq3SLblApcZ2VVDUZNy5TLsA3knvq19jUa9V3iAhb0jWxUAdkEHCPog7KMu-jMfaF7Au49IafPdTD2Z-gQfh47XOR2jNNF2rSO-2tFeK-cQE18Q4hp5zEfO2jPru7H7cM53TBdcMfUZ-z0iyw3w-FAXSutyX2NT4ZFdW-yveL1kQ85dzBdTZvcfb4Lu8z36WR-tXi9Yyvp9N1kRTj8XV8d7fXUaMMJ-70B6HXJo3EeD8v5t29mXCuUMgFDQsiffO-QfRMCgVvX-5cKhbR9D6BBcMB71zzmfVBLcPbf0njfbBs8dqH2AdIbiYDV5MA0IUchE8YGMyXl1CGB8F7ALqMg7mbC-iXyobAnBRR4H0MES_EhlNREXwodA0u3CshdWKBUAhJNxA1FAbnJ2hRRGf3EVwzuGiqg9wEUNTqwjFFrwwT_He5cNFoPwfQ2xn1DHgOMcYpxEj1Gz0Vjou2ejiFGNYWddBZi1EWK6plR-njCE1CYT4lhbCJYBPMbvDRLNCbJN0VbexvRMm81idfWBGjJBMFFoUsJMsSl-IqGPCpWCjKaI8TYwhRR5GRMycozhcTd4-i6g_LpfcPoGNfijTJpiVGYJcR0n0MhQmB3EEUJozC36lLOhdNpSzRk1EaGsrOGzvEzJEa7bJwzy6jN6fwyZGyc6XIcdHBZzjqEdOhgU7pRS0mpVZgC2ZzdKjVEoZrHW-sjYm3Ntw6Qpza7iD9A7BRuy8hgqGZU7h3V_R9SyE8v0y80V-KyGPKoWL2mbWhqtAl7N75NKiYrTFELbnDErviwlfTfFMqmhS1l2LO7C05fS6ZJKmWf35aowVHUZ4aBpTbelFzxVsMGCy6VWCaj3KyGzYBfoXnSxVWjcoFTxBaz1gbY2ZsLZ0LekNVFkTJCFFaR8wJgq7WEI0C_aWx8eVOqYBvV12UE5JxTtw9OTyAGMv9YMgV7SZ7WMjVs9JOzSj5RuTK8uM8EX1PWRoZVjrHEHK-TPR57N5XRv8cW2BcrEX9w0AC8VTrgIZvaTgxN7NJDEsLT0VtSypF1pSr6EO-aX4o2bYGrFZqoWWthanDtwCZCVsaH2r5Gic1_LCb1Zd8zKVLI0b8p5kgC1-r2au2BoyF1DShsut21buH3MHVICJp73l7q-Ruo9jbC2FyDWy6Qs8n3AQdae6m574X_yA7kStZLwOd26gfOlwDgLevzdM8daNJ0CunRamF1ruGIbcKkTOPgqKHlmLYVIs4yPTAo_MXQgFsK6EMHxbw0AIBtEgDANCup2Oce_DxmsUQEhCiUipQgCLUh6GE0KCQCIIBYARLQXcGFcDMQgmKVC8oYK6V0FQGiVALwabIFBTUumlAYSRDMYz6AHDIkgDsYgHj_YcjmOcK0UQJPmcoNeTsNnYAPifO540wUorIjwCOccfxSIJBvPhV4HF0TYFaFESLZBiwWYSCALgrRPyOTvCZ4kaYLQJleDFuL_n0BLCwDMLAPIRBiFgEUciRYXARAK65UQPloTCnyAXM6lstmpFC-iMKqQIohS6w5QwvWxu6DiglJKhC_o9EKLzYC-BBj4GGBbTZTyUYlFqZiuoDRk2GT28Rv4pH_DkePH8ajN3aN3ak6aG0MnkQahgn8Fjjw2McfigJ7TbESx8YB9xuslohMieRGJw0slYCAS4n8VT6m6KaZhBD0ruhEuYjoNoGgPpQFWnkopZSql4foBJ3yKSvBxBChFN5sg-nZTAiiMsXgBXlB4BoHVPi-nHMlY5PsckEhaAMDErgZ7xpcCeaa4z9AzOwRGbRyZrTrFYJRdSL5vC_mRtuXCyKDkoBWjyeiMwXhHIccYjx0wAnRPjSBcaxUeXsAaBZZy3l_zegiuGnVxyLkCIzCOXENAGAZFtRtecqEAglIuDdZm7gVBSfZVBRiCFObSgJvxDj9N5EieM-UAW4lJyQ0Vu9HWwMIY4dZX7flqUY79RGg2qYER3QJG5x6Fu5R3QD3O9Pe7_RIwb3ocsU1N94ArHQdcYpH7qT72qCw4H5QRH2JkfTFR5zk0GPBfsRdNma3dAERaB-sT7ki-ZL--5NTlk6J6dpfQBlnzBnWfs_84OGYvPHj88E68YXwlRf0BgAS5S6vAy6EDNYUR6bP7gQq5Qhq5maQG0i4S3hWh656AG5iTG6m6y4zxMYJZ75uh0CH7H5iSO6sgu5u7Za5bziwH6A-6fbA6vAB5B4SCh70j36TiR7BAuQx7iBTY9aJ4FDSADbrSp4bijYGi7hZ6x7x554BSSF_BF5La6Jl5rb9CbZV6pw1C16UyHblAUonZN44qt5KDt40ZHhL5kC95d70aD6CDD6yZA5Y5kA_ZYB_b8bg6z4g7_bT4_5ijz7n7w4r6iypAo4GZe5aY749gEHojugVALAALJCX4KTn5qSn4KTX7SR0554cGP5M7P4pav60Hv48584fCY5C5CQ_hi5AEciS6WGF6y4QFwRa7QHRi0GmY6aIE-bIHxa6BoEYFG4gAm5Dg4EW675ZhugSwJHSBJFWhkFAQUHu7UH5ZWje77C-5j6n6B7B5sHh6tbjg2SkBF4ABawAwACQyhKueuGQn4Mwu4bQngNowxBk2gfw-kzxrQFIM8TAeBYoCU_EDRru0wrIbxqQ12feFhthckEAVADwWAEowA1m6IexAE5xCQdU0AiJQeNAPIKgtE4gCIpgVAaWeRBWNx0AdxcxPeHeNh8OdAsJ8JiJyJIeYeaJFxmJ2JhweJuYcobkg44uXBZA5JaeUUZItWu41h_e0JZADJcJjwzJIUqJQp6AIp4hbk4pjwQUjgsAXq8OEJdJfwcpTJSJSpbJ1k6AsMeI_gZg-wKojmQQwpw2op6IIAHkCINAwghwu4nRjBheHGGEn44OkmugbpNAHpjkjpugm-Cu4Rt-VAO4HI6Ajx5k60SZhEMRmITAuAkgWQNArQYkeR3BBEiufJ2AuY0AYkyZ2k8Gmi2g2iVoyZZk4Mfx-BkxsR0xiRHBD-HIMZ1AcZ4gUQYIKIggVZaQNZHU3U2gTADZBEKZa0my6ZVuRBR-6sQYvZjZ_ZsoEgPkhum5-k5kmydZM5S5mZu53ZnBbeEQU4VgdmcJEAjmS4AItw9wjwxmeuCIWAH4egpJpArgzgAA3EAA)

**Comment by electroheadfx** [comment]
thanks @MatthiasMert
