### ISSUE TITLE
[Bug] Invalid legend (type: scroll) horizontal paddings when data names are too short

### ISSUE THREAD

**Issue by Butsyrin** [apache/echarts#20470]
### Version

5.5.1

### Link to Minimal Reproduction

https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBKOAZjgE5OzB2wCGsA6jgEYBnCGByUANEXQCArnxHkqAMQ4BrHLAAiHMB3GTYuOhViUAxjmgjGlIgF8J6MMGBZIIAqmIZGEAOa-mKmEcAFsbdHsiXADoABMPfTAATxB8EwFTRhcsPS9gHwtjSgA3JkhTDhyHYkNjAAZqx1AqEIhY2Nxc4j582KZuNrAACwIARkbYEA52iGhfAgBtBtg6gF0J2O0ORcoAZUpVu2qBJggcAUX9Ty9YaA4QtMoAQVNzAQFYRSywiccUx5AZy6XkY0wg0guJgArHUAKTA4ibHSXG7EJCwYqVaRpUZ1AAsAA4xLd7o99rBIqj0OjMVhsQQAOwAZihxLuDyoGggzFMYEoFN-aIxWLSUIJy3ZjwAoiEOBAcgL9F4aSKCIS8WzSVQAKrQKBwJ6xAT8ylUlV0tJMuoSrUmABqbRwwFghuNFKVsHWHtCICGHCEkOuqOCIV2yVwCSpxAEftiwAA7gAhOmMMYND1eGPTBMAeTodBOYAAGgR01GpLGEwBhFz5KiMXx8DgACmWbeJdQAdFCAJThKm2D2DrzDz0oWwAbiAA

### Steps to Reproduce

Nothing, just open the demo.
I set paddings in 0, but rendered horizontal paddings are not 0.

### Current Behavior

On scrollable legend horizontal paddings are invalid when data names are too short.
If name is long enough, paddings become correct.
In plain legend paddings are corrent too.
Tested in chrome and firefox, behavior is the same.

### Expected Behavior

Horizontal paddings must be equal to the value specified in the settings

### Environment

```markdown
- OS: windows 11
- Browser: chrome/ff
- Framework:
```

**Comment by helgasoft** [comment]
_type:'scroll'_ adds some horizontal space because it has [pageIcons](https://echarts.apache.org/en/option.html#legend.pageIcons). Their size could be adjusted with [pageIconSize](https://echarts.apache.org/en/option.html#legend.pageIconSize).
Otherwise _padding_ works correctly both horiz/vertical, regardless of name lengths - [Demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6sAzgK4BGYOAHmAQOS4DmO0AJrCAIbvsTRmDIgF8ANERZt2BANqpiGAJ4h8sBiQDGAJ2BYsDCYp6sAkppgBlCAC81ABiPFg2iG3rqAbjm2RN3Ayd0XAAzD0cMUAIAZmig2AoXdh8AdQh2MAALAgBGMQSknwBhPRdGbRx2QyJ0Hj4BZjkI-wBdJ3EFZ1d3Rm9fCH9AmthQjwA2MfywKNhY-MTtZO00jOzYPILF4tLtcsrq415-QSb8gCYztuGIagBbAHFuEAJ7USv0Eh83EjlhzsUwCo1AwQG4DopYNpeBAyD9YAAWfKadw-PCyBhjewAUkMDAuOPeEPY3DA3F-EOISFgngCZDUOXs8IAHPloNxbsD7gxYOJhooqTSsHSCAB2aIAVlZ7OBACVubyKegBbS1OKmRE2RzGABReXxfnUlUEZmI2Ca4EAQT1fMphqFami9g10sYABV5TaWsMREQvSIANxAA)
![image](https://github.com/user-attachments/assets/1133da6f-6af0-40cf-ab9d-6bc592a5c46b)

📌 please close issue if problem solved.

**Comment by Butsyrin** [comment]
With long enough names paddings are OK without setting any pageIconSize properties. [demo](https://echarts.apache.org/examples/en/editor.html?code=PYBwLglsB2AEC8sDeAoWtJgDYFMBcya6GOAHmAQOQBKOAZjgE5OzB2wCGsA6jgEYBnCGByUANEXQCArnxHkqAMQ4BrHLAAiHMB3GTYuOhViUAxjmgjGlIgF8J6MMGBZIIAqmIZGEAOa-mKmEcAFsbdHsiXADoABMPfTAATxB8EwFTRhcsPS9gHwtjSgA3JkhTDhyHYkNjAAZqx1AqEIhY2Nxc4j582KZuNrAACwIARkbYHsY-xgBhF3yqZliu9BAOdohoXwIAbQbYOoBdCdjtDj3KAGVgEPUsGF9YaA47yiO7aoEmCBwBPf0ni8z1eaUoAEFTOYBAJYIosmEJo4UmCQL9VsRGBsINJ_iYAKx1ACkGPQZx0AOBxCQsGKlWkaVGdQALAAOMQgu5UG53AyPTmiWCRKnoGl0rAMggAdgAzPiOS8uSYNBBmKYwJQhUjqbT6Wl8ayDoqwQBREIcCA5LX6LxivUENnMhWgqgAVWgUDg4NiAk1wpFdolaRldSNLpMADU2jhgLBvb6hTbYCck6EQEMOEI8UCqcEQldkrgEiLiAIM7FgAB3ABCEsYYwaSa8ZY2VYA8nQ6N8wAANAiNktSctV-YPesmRi-PgcAAUB3nHLqADp8QBKcIi2xJrdeHfJlC2ADcQA)
![image](https://github.com/user-attachments/assets/9bf8c804-d272-4c75-829d-69f2f8a49bbd)
Setting pageIconSize solves the problem, but with short and long names behaviour is not the same.
