### ISSUE TITLE
[Bug] Treemap disappears on interaction / scroll / drilldown (Vue 3)

### ISSUE THREAD

**Issue by DotoPototo** [apache/echarts#20530]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/echart-treemap-vue-bug-q74ljp

### Steps to Reproduce

Click on a node within the treemap OR click on the breadcrumb OR try to zoom with the mouse wheel and the treemap disappears. 

A refresh brings it back. 

### Current Behavior

Treemap disappears/minimises to the top left. 

### Expected Behavior

Drilldown or zoom change

### Environment

```markdown
- OS: Any
- Browser: Chrome
- Framework: Vue 3
```

### Any additional comments?

It uses data (data.js) which is the data directly from the [disk usage example](https://echarts.apache.org/examples/en/editor.html?c=treemap-disk)

**Comment by helgasoft** [comment]
not-a-bug, probably due to error in Vue environment. Same code works fine in the Editor - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=LYTwwgFghgTgLgOgM4QPYHcAyqoBMCWAdgOYAUAlANwBQAJAsQKZykBKA8uwCoD6ACgEEuACQAEAalEByAPS4ocKDKhIkzOQqUEkAawRwYjRggBWSVISkAaUdQBmAV0IBjOPgujS2nQBFN5UQBvalFRUEhYRAh8XEZsPCIyKhDRGRlnCyQ4UTtUGGAFAFU3ABtRAF5RRmdoeCQEXPyFGlDHFzcPJjhMRgA3RhL2AAcOwgoglNDDOAcYQlEAbUnQiZW10Xw4RmAAZTgQEsYALlX1tYAjPNiYAHUYuAgTgAYrZbPiKCG73AeTgFY3isAL6AoGvM7BM6hTbbPYHY6nKGiD5fe6PUQARkBoRBZzBgMhUIyJTyOwUswU7kIJwWTwQAGY_jY6X8ALrgqEw3b7Q4nQlIlHfX6YjlIy4wa5gVAkmBkmYwSkWZ4IABs2NEuPWmtCrJaGpSqBGVIqiNEahg-EYSBpBPVhCgwARUh8-F0okKSCgTGs6v2QydBiMBSGPqRvVd-HOhwAskQTvSni91SUoOcBnz1aEUBgTgYHIxRVDGgU4FsYCcpIFzkCpOr8UiHEN_TBMKn06aztn0LmYPnC2cIIx8MQIHB4086_2Vly4byO-txZLpXkKwBiOwb2tI-tQtKHfola3I5g9A_DUYUKeheSKE7ePyKUHLVkpIF68K1RBqODnqmkQ2jMkQJUEAA)

**Comment by DotoPototo** [comment]
@helgasoft just because something works outside of a framework doesn't automatically mean the bug is within the framework.

**Comment by helgasoft** [comment]
Are you using the recommended [vue-echarts](https://github.com/ecomfe/vue-echarts) ? There are examples to follow there.

**Comment by plainheart** [comment]
@DotoPototo Try to use `shallowRef`

```diff
-const chart = ref(null); 
+const chart = shallowRef(null); 
```

Or a local unresponsive variable.

```diff
-const chart = ref(null); 
+let chart = null

// ...

onMounted(() => {
- chart.value = echarts.init(document.getElementById("main"), "dark");
+ chart = echarts.init(document.getElementById("main"), "dark");
  updateChart();
});
```

See also other similar issues [here](https://github.com/apache/echarts/issues?q=vue+is%3Aclosed+label%3Athird-party), especially https://github.com/apache/echarts/issues/17723#issuecomment-1268311307.

**Comment by DotoPototo** [comment]
@plainheart That makes a lot of sense! Perfect, thank you 💯
