### ISSUE TITLE
[Bug] Boxplot chart is not working when y-axis type is time

### ISSUE THREAD

**Issue by rtilak-oleti** [apache/echarts#20570]
### Version

5.5.1

### Link to Minimal Reproduction

https://codepen.io/Rajtilak/pen/OPLXvpo

### Steps to Reproduce

1. Use the configuration below for an ECharts instance.
2. Load the provided dataset.
3. Observe the behavior of the boxplot chart.

```
{
    "dataZoom": [
        {
            "id": "dataZoomX",
            "type": "slider",
            "yAxisIndex": [
                0
            ],
            "filterMode": "filter",
            "minValueSpan": 5,
            "showDataShadow": true
        }
    ],
    "tooltip": {
        "trigger": "axis",
        "renderMode": "html",
        "backgroundColor": "rgba(0, 0, 0, 0.8)",
        "borderColor": "rgba(0, 0, 0, 1)",
        "borderWidth": 1,
        "appendToBody": true,
        "textStyle": {
            "color": "#fff",
            "fontFamily": "LATO",
            "fontSize": 11
        },
        "padding": 10,
        "extraCssText": "box-shadow: 0px 3px 6px rgba(0, 0, 0, 0.3); border-radius: 8px;"
    },
    "grid": {
        "left": "2%",
        "right": "2%",
        "top": "20%",
        "bottom": "25%",
        "containLabel": true
    },
    "legend": {
        "type": "scroll",
        "orient": "horizontal",
        "pageButtonPosition": "end",
        "left": "3.5%",
        "top": "2px",
        "icon": "roundRect",
        "animation": true,
        "data": [
            "desired heating",
            "desired cooling",
            "calculatedParameter_1"
        ]
    },
    "yAxis": {
        "type": "time",
        "name": "Date & Time",
        "nameLocation": "middle",
        "nameGap": 30,
        "nameTextStyle": {
            "fontFamily": "Lato",
            "fontSize": 13,
            "lineHeight": 14,
            "color": "#999999"
        },
        "boundaryGap": false,
        "splitNumber": 5,
        "axisLabel": {
            "formatter": {
                "myear": "{yyyy}",
                "month": "{MMMM}",
                "day": "{MMM} {dd}",
                "hour": "{hh}:{mm} {A}",
                "minute": "{hh}:{mm} {A}"
            }
        },
        "data": [
            "2024-11-26T18:30:00Z",
            "2024-11-28T00:00:00Z"
        ],
        "axisLine": {
            "lineStyle": {
                "color": "#CCCCCC"
            }
        },
        "axisTick": {
            "show": false
        }
    },
    "xAxis": [
        {
            "axisLine": {
                "lineStyle": {
                    "color": "#CCCCCC"
                }
            },
            "position": "left",
            "name": "Values",
            "nameLocation": "middle",
            "nameGap": 40,
            "nameTextStyle": {
                "fontFamily": "Lato",
                "fontSize": 13,
                "lineHeight": 14,
                "color": "#999999"
            },
            "axisLabel": {}
        }
    ],
    "series": [
        {
            "name": "desired heating",
            "unit": "°C",
            "defaultNameForExports": "desired heating",
            "type": "boxplot",
            "symbol": "none",
            "itemStyle": {
                "borderColor": "#897A5F"
            },
            "data": [
                [
                    "2024-11-26T18:30:00Z",
                    11,
                    13.5,
                    12.5,
                    11.5,
                    14
                ],
                [
                    "2024-11-28T00:00:00Z",
                    10.5,
                    13.5,
                    12.5,
                    11,
                    14
                ]
            ],
            "yAxisIndex": 0
        },
        {
            "name": "desired cooling",
            "unit": "°C",
            "defaultNameForExports": "desired cooling",
            "type": "boxplot",
            "symbol": "none",
            "itemStyle": {
                "borderColor": "#8FDB5A"
            },
            "data": [
                [
                    "2024-11-26T18:30:00Z",
                    11,
                    13.5,
                    12.5,
                    11.5,
                    14
                ],
                [
                    "2024-11-28T00:00:00Z",
                    11,
                    14,
                    13,
                    11.5,
                    14.5
                ]
            ],
            "yAxisIndex": 0
        },
        {
            "name": "calculatedParameter_1",
            "defaultNameForExports": "calculatedParameter_1",
            "type": "boxplot",
            "symbol": "none",
            "itemStyle": {
                "borderColor": "#FD8013"
            },
            "data": [
                [
                    "2024-11-26T18:30:00Z",
                    22,
                    27,
                    25,
                    23,
                    28
                ],
                [
                    "2024-11-28T00:00:00Z",
                    21.5,
                    27.5,
                    25.5,
                    22.5,
                    28.5
                ]
            ],
            "yAxisIndex": 0
        }
    ]
}
```

### Current Behavior

1. The chart fails to render.
2. The y-axis and x-axis labels do not appear as expected.

### Expected Behavior

The boxplot chart should render correctly with the y-axis representing time-based data. Each series of boxplot values should align with the specified time values on the y-axis.

### Environment

```markdown
- OS:
- Browser:
- Framework:
```

### Any additional comments?

- I have ensured the time values are in JavaScript timestamp format.
- Switching the yAxis.type to 'value' resolves the rendering issue, but it does not meet the requirements of my use case.

**Comment by helgasoft** [comment]
Barplots, like bars, do not function well with axes with continuous data, like time or value. Because they have **width** which takes space. So yAxis _type: 'time'_ won't work for you, but _type: 'category'_ will - [Demo](https://echarts.apache.org/examples/en/editor.html?c=line-simple&code=PYBwLglsB2AEC8sDeAoWsAmBDMWBawwAtgFywDaa6yV1sEGZA5NrgcQBpMA0t1YATxABTZgGcANg2EAnHn3QCAggA8IYgJLQMwlWXIAGALq866AGYQJYWQFlgO5peuz5Z2EQjQAalgkBXYQBlECxoMgBWUzMxAAtgAHcAERwsINisDESyMBlAvgBfKhMqMEJrCBAyVDpciABzetlmLDUxN2oZYW07B1FYJliwIgkO9AAjLABjAGt6mWB_bQBhYAlgGWYZesmACgNuWAOjw4MAOgAOAEox2HGNnRlV9c2B7b3jz8OARhvoiYesgA6gwwLEyN9_rAsCARNoACrAABCDgEOTywihNhUYCCggk_RqZimaw2zAAxOYqbcLDAwAAxLCeCRogYAGSU8IA8jTYOY6UEIAAvfrfb6FKGhDAYLz1CEHPi6XJYZZiMTwpUkBQDe4qAC0cUy2SOIBUsAAzKbYAA2K3vLD7U5Oo5nc1XADcd0BMj1MkyEH8YjIF1N7qYVAK0XmDGqfAJ5jAzAATABSW4yBpDZNprGgZMGHN8e5gMqkAZJiKFugk6C4LxsrDjYQSdH5dCRqgEpraWO1IT9JhiKYLCSjKEbCDdRMDeIZoV0vy3UJNJH-EswAAKwDEEEgMGY3Qwt3j06Y5rOlduZSq5dNtwgNa2i20ACVhFMwLcwhAiDgoOFYFyQIoVYLB9BYYQdy6DBYFiYQ_2geoeAGHQoOEGCSTWWVkKYKY_CmfwJBwdCNywP0iGEGwZAAfW-JgjAjaJlDaXt-H7Zg8JseoNgEW5oCZAcUhsWAADJYHhH9hD4gS2WATj_2YTxpQJaSKIAcRhMhzQVOh-IojUcTxAQCVYuh-VrRlmVZJgGzKXlzNxYVRXNKF0CkaBhAACWETNp2-AAWVzYBJF4KQATgiyLwzoDs6HuJZsBkAQNJvcw_DETE-DEEApDAAA5fwiCbV4oj4Vp1AbJsWxodx-RkX8S2aGr3A8AR4NeJgkAEbqBAKXl0CIOlwQGJBbDG2w-qC9BsGs0axoKZBpUm7V0HifwOqQWJYgKEgkCIIgFqQJRlpajwvDXAdNu23b9sO47orMIoYpA1JwKTAwk38vUxT1JNrXhb4LhIbSSAMAw8Bw97Pu-75foueEwdBgwkYhko6HKsQ2S8QltXc4J8Rx06QrJAZyWWcmKYemKJTKtoJNmUzqDiY00okDLCkYqgVFUdR9D4Il0baLGPMZug8aMkzmqJ0kOrJinyapx7tViswQG3XcFIGE9eT0gdfACSCdZkuS_33AYlIwFSgt1lKyH8nSzF1gzcQJ0XqAcyyrGs2zgH6vkBSciEXJW2A8e83yIUCkPidlyKouVoKMcq5tqie6g07R2AMozSC-boAXqF15hUIgaDYPgyBEN5JZd2YAAG5ZeR0NLCPygT6Q2ABRFQ1ZkMAgxQyDS_Q8uEKQoLBBEZhdRy4BPyCjgxAEIq1mYaAYCkoLd2EIgJcJlr7hkR5nhJphyQuMKAHYlAielFfbILQLzlqkCLpgoa-n6_oBoGQbBiHDiwAAG5-ECCQcgYofjniiLAb4SYLw_G-Ag2B_kjAq3cK_ASJB34fU_rDJM8NEZEPBshYBoDRAQPODA740CfjwOoZCFBaDtSZzoMxdQWgdB6CODTfO2oi6DzQhhco2Ego11PA3JuwgW7WDyu3LuPcNj92LkPMumF3Lj21JPAcM91jz21NvXerspZmEPsfGWFILj0iSEiCISh76wHQdQJ-FAQ6YIotgj-MNfr_UBsDZG_9kIgINuAyBsDaGwPoYg5BAU0FTWQG_LxX9CEBNSQA9AwSwEQMYQFKB0TqH-QvMw9wDFnr834VggYeEJAESIjYDApFyKUVkLRKRMi24UQ7jIbuvdlFVPwoRYiDSyICSoq0ie7EdTAB7no3kS8V7VSYOvDyvJDF7zdgCI-sgT6y2sRcAwNCHFOOmq9Vxp13GiBwdDL-vjf5pKCeQ8BsAkxJkOEmS-byYFJhcs8i4cS3GJNwd4ghCNUkoweSE8gzykFfMvsgis8Kom_KKWnOgpT07FBQAUd0QA).
