### ISSUE TITLE
Sunburst add label dynamically for the available width and add ellipses to overlap 

### ISSUE THREAD

**Issue by Sri-5555** [apache/echarts#20575]
### Version

5.5.1

### Link to Minimal Reproduction

https://codesandbox.io/p/sandbox/dl4y3x?file=%2Findex.js

### Steps to Reproduce

I have created the Sunburst chart and adding label to each item, for now given hardcoded width for overlap 

Solution required for adding label text dynamically inside the chart available width 

### Current Behavior

fixed width is given for overlap 

### Expected Behavior

required dynamic width calculation to add overlap 

### Environment

```markdown
- OS:macOS Sonoma
- Browser:chrome 
- Framework:Angular
```

**Comment by Ovilia** [comment]
It may not be possible to show ellipses without setting `width`. See the [demo](https://echarts.apache.org/examples/zh/editor.html?c=pie-borderRadius&code=PYBwLglsB2AEC8sDeAoWszGAG0iAXMmuhgE4QDmFApqYQOQRjUC29xAvgDTHbU3QAJoVQkMoBgFYApPR5i-AMzAMAxtWjNS7dN2IBnWhGr7CAbWLpRY2NACGLagwCCq9fv2wAYqWBt5NmAAniBOsPQgxnKWJKR2ghAArqawZvQALAAMslzhAOzZ9AC6AWJ2AG7AEIIAMnYARtTYAPLltNh2BLCKdtiGpSRMrADKwXwiMWL1wKSCtABK8UkpAIyZA1Mzc6QAwjgzDADEiifRNiTTs7QA6tVgABaEAEyTsHrnHY3YE-fo-vfAADuhDApES1A2JBAwH0TCg0AYEGgsLmZ1-gLuj1gAGZMutXuhgG1SIpsECGKDEtBVHZmGjzk1sBAQLCUvQAHTsnQ2d42Vgge52Vk_X6fJoi36wf7ksjgyFiRQwMDDCAALzCWXlJEVmmu1Eo9xU4Wm2EE3POHFevIUDSaNSRYWs52lwO6vUMVshglpdnMBOQsHKvXBhDW6QAHLl7I4GNj6ulFE9qIIngBaeqSVSCVPpQSZVSp8MATmxADZU08GkXqJlqCsi0XFOl6G8tUhA8GwnlsZIow4wvQ4wmk080xmszm8wXi2WK1Wa3WG02W9abO2g9gQ7BJOH1rZ-7H46Pk2PM9nc_nCyXy5X6tXa_XG823q8ijFLeg3xwANxAA) of a pie series, it's hard to tell the width to clip the text even in this very simple situation.

**Comment by Ovilia** [comment]
That being said, you could still provide a width calculated from some parameters you know. For example, if we know the inner radius `r0` and outer radius `r1` of a certain level, and you have `n` nodes of this level, then we know that the tangential text width can be approximated to around `2 * Math.PI * (r0 / 2 + r1 / 2) / n`.

**Comment by helgasoft** [comment]
@Sri-5555, sunburst can have self-adjusting labels when all items have [value](https://echarts.apache.org/en/option.html#series-sunburst.data.value) - [Demo](https://echarts.apache.org/examples/en/editor.html?helgasoft=sunburst+self-adjusting+labels&random=58gr94wyc6&code=CYQwLiAEC8kNoFgBQlIG9IDsQFsCmAXJAOQCCkAjAEwDMALAKwBsA7ABwCcADNcQDSQAbiAA2AV0KQaXSAF8-yVBmz4ixAEKVajJvyGiJRKjPmL0WXJOIBhLTT3DxkiieQBdANzIATiGABLMQBnWDhiYwBSPWJuKM9kILEcWC4vJFAIADocEAAHAApIAA8YAD5zSEScSABqWCLMxwkPOQBKZGQAe1ywf07MGHQzXrARQjQwPCKwAmIgvBEAMwBaPwArYN7MAHNIERAAIwWgvUSDyenZ7zwg_wAvPEgwTsq8PGJTFFfvfxuiRC-SjMqFQYAAnrkrIlMAcxN4gmB-MCQb4AsEFICQRkQBiQSD9kcREQMN5OhBJmoIDs8JheqIPsjZGY3MhZGlFmJMABjXr9SDXYC-ADu-VaQy-QqFg0gODB1gAFiBvGBMts8GAAOr-YBgeWitKoeXy6WyhVKlVqsAACTw_m28rA-rMtzugwAsuB5dl_Jh8pKBEbWgb-d5BgA5JJHbyZXJK-YAMREnXA-XysfheETycdqMCQTgXDcYpqkHTCaTKdzwTgFCLYoA9FRIPWXDIAFQu1qZZ7x_xFPDAfJUINmXK5QZUNse3WZAAKAEk295vC1m_XS9AqIAB4FDpbwP3wk1DnUWkC5_m8XLGzq5ojwsBYq_r66Ct7GkH8QUqYgOazwPP8QRHjMbFMkWTpvAAURALk9WKMpzGRIVtXqRoDDwesqkgNtS3HTC3zwVdkQaAkFlgNBkJ1eUiEogROiA7xFiTIVZjAbxOVvSYGS-WR2i-U1FWVTJ5jAAB5Ho-l9DB5h-P44DQbFZDcNo0iZJBkMwYBOiFTI_GASCgNpAAZT9Jkwfd8mIa4XXeAQBWFVogA).

Your example is a multi-level sunburst where only outer-level items have value. In such cases ECharts calculates inner-level item values level-by-level until the entire chart is built.  It would be great to know **which internal function** to call (wink-wink, developers 😉) - to get these hidden calculated values. Otherwise it's DIY - a recursive function to calculate all values starting with the outer-level.
