### ISSUE TITLE
Radar chart spokes disappears on mouse hovering

### ISSUE THREAD

**Issue by vasu-vvp** [apache/echarts#7136]
I have tried this under E-chart demo for Radar chart. It seems this is a bug?
using following data:
```js
option = {
title: {
text: '基础雷达图'
},
tooltip: {},
legend: {
data: ['预算分配（Allocated Budget）', '实际开销（Actual Spending）']
},
radar: {
// shape: 'circle',
name: {
textStyle: {
color: '#fff',
backgroundColor: '#999',
borderRadius: 3,
padding: [3, 5]
}
},
indicator: [
{ name: '销售（sales）', max: 6500},
{ name: '管理（Administration）', max: 16000},
{ name: '信息技术（Information Techology）', max: 30000},
{ name: '客服（Customer Support）', max: 38000},
{ name: '研发（Development）', max: 52000},
{ name: '市场（Marketing）', max: 25000}
]
},
series: [{
name: '预算 vs 开销（Budget vs spending）',
type: 'radar',
// areaStyle: {normal: {}},
data : [
{
value : [null, 10000, 28000, 35000, 50000, 19000],
name : '预算分配（Allocated Budget）'
}
]
}]
};
```

For values in data observe that first value of an array is "null".
Now radar is rendered. Hover a mouse on red spokes of radar. You will observe that these red spokes disappears.

Refer image :

![image](https://user-images.githubusercontent.com/30551082/33303079-afb6d6b6-d426-11e7-96f4-399a1de8d41c.png)

**Comment by cDanowski** [comment]
Hi there,

first of all, the project is great!

I stumble over the same issue, when adding radar indicators whose value array contain 'null' entries. The data points are depicted correctly, but sometimes the lines are drawn correctly and sometimes (especially after interacting with the radar, i.e. hovering, tooltip, toolbox), the lines vanish and do not return.

PROBLEM STATEMENT && VERSION:
I use version 4.2.0-rc.2 of echarts.
I have several indicators in radar, only two of them contain numeric values for the selected features, the rest is null. After selecting my features in map, I see the radar chart as expected (lines only connect the numeric points):

![image](https://user-images.githubusercontent.com/11268338/60514664-3eaf7300-9cda-11e9-9c2d-65bed8e40ca8.png)

But as soon as I hover over any item to force the tooltip to show, or open diagram (or sometimes when adding another feature to radar), the lines connecting the data points of a certain feature with null values disappear.  Also the point color of the hovered item spreads to several data points, that actually do not belong to the feature entry (see by comparing both images)

![image](https://user-images.githubusercontent.com/11268338/60514810-8cc47680-9cda-11e9-9dc4-c2c15a1e4d9c.png)

The lines will not come back by hovering or anything, also the "restore" toolbox-tool does not bring them back.

EXPECTED BEHAVIOUR

In my opinion, the lines should not vanish, but stay as in the first image.

I hope I provided enough information and would be glad about any comment on this issue.

Regards,
Christian

**Comment by apoorv-2204** [comment]
?
