### ISSUE TITLE
Legend scroll using mouse wheel

### ISSUE THREAD

**Issue by jarben** [apache/echarts#7909]
Version: 4.0.4

Would be great if legend can be scrolled using mouse wheel:)

**Comment by Myll** [comment]
+1. Same for the dataZoom slider.

**Comment by guylando** [comment]
Also legend scroll on mobile using swipe would be great

**Comment by pedroviniv** [comment]
I think this would a great improvement too, mainly for using in a mobile device with a larger dataset. But since the legends is rendered using canvas, I think implement it wouldn't be so easy as it appears. As a workaround it could be implemented a feature where the legend is rendered as a SVG rather a canvas. Then, in the chart option we'd set the legend type as 'plain', define a max width (static or inherited from parent) and then, with css, use overflow-x: scroll.

**Comment by akenverus** [comment]
Still not implemented?
