### ISSUE TITLE
折线图label因为showSymbol属性设置为false显示不出来bug

### ISSUE THREAD

**Issue by shentao1** [apache/echarts#8885]
### One-line summary [问题简述]
折线图label因为showSymbol属性设置为false显示不出来bug

### Version & Environment [版本及环境]
+ ECharts version [ECharts 版本]:
+ Browser version [浏览器类型和版本]:
+ OS Version [操作系统类型和版本]:
echarts:4.1.0
chrome:版本 68.0.3440.84（正式版本） （64 位）
W7

### Expected behaviour [期望结果]
设置了折线图 label.show 为true，该折线图就应该显示出来

### ECharts option [ECharts配置项]

```javascript
option ={
  "xAxis": {
    "show": true,
    "name": "",
    "type": "category"
  },
  "yAxis": {
    "show": true,
    "name": "",
    "type": "value"
  },
  "series": [
    {
      "type": "line",
      "showSymbol": false,
      "itemStyle": {
        "color": "#4191FA"
      },
      "lineStyle": {
        "color": "#4191FA",
        "width": 2,
        "type": "solid"
      },
      "label": {
        "show": true,
        "fontSize": 12,
        "color": "#999999",
        "offset": [
          0,
          0
        ]
      },
      "encode": {
        "x": "x_idata",
        "y": "s_idata"
      }
    }
  ],
  "dataset": {
    "source": [
      [
        "2010/01/01 00:00:00",
        100
      ],
      [
        "2010/01/02 00:00:00",
        160
      ],
      [
        "2010/01/03 00:00:00",
        100
      ],
      [
        "2010/01/04 00:00:00",
        16
      ],
      [
        "2010/01/05 00:00:00",
        100
      ],
      [
        "2010/01/06 00:00:00",
        10
      ]
    ],
    "dimensions": [
      "x_idata",
      "s_idata"
    ]
  }
}

```

**Comment by momogugu** [comment]
@shentao1 
I checked the code, label is connected with symbol. If `showSymbol = false`, it won't draw label.
And if you want to show label without symbol, you need to set `symbol: 'none'` instead of `showSymbol: false`.
![image](https://user-images.githubusercontent.com/20534564/48199693-e36df080-e397-11e8-9040-c36e8d24235a.png)
However, when I set `symbol: 'none'`, it still doesn't draw label. 
I checked the code again, and found a function `symbolNeedsDraw`.
![image](https://user-images.githubusercontent.com/20534564/48199840-54150d00-e398-11e8-9863-4dc303abb7c3.png)
so when  `symbol: 'none'` , this function will return false, it won't draw symbol, neither label.
I think maybe the developer doesn't want to show label without symbol, so I'm not sure whether it is a bug or not.
And I tested, if the condition `data.getItemVisual(idx, 'symbol') !== 'none'` is  removed, we can draw the line chart like this.  
![image](https://user-images.githubusercontent.com/20534564/48199869-68590a00-e398-11e8-9282-35278709fde8.png)

**Comment by yufeng04** [comment]
The  case when "showSymbol = false" and "label.show=true" is not handled. So I think we can add a judgment to deal with this case. The way consists of the following steps:
1. In the function `render` of line
<img width="472" alt="9ab9209d3e0959f2bde8e696c" src="https://user-images.githubusercontent.com/22974511/55855455-2972ee80-5b9a-11e9-9d06-7ecb08bf4f48.png">

2. In the function `symbolProto.updateData`
<img width="522" alt="3ee35cffc4d0c30849f5d811a" src="https://user-images.githubusercontent.com/22974511/55855675-c3d33200-5b9a-11e9-91fa-6d5c9e56f735.png">

We can draw the line chart like this.
![a03102b97758d534de9ea447d](https://user-images.githubusercontent.com/22974511/55856074-c8e4b100-5b9b-11e9-8570-d81fd3b8a220.png)

Hope it helps.

**Comment by ghostlhq** [comment]
可以通过设置symbolSize: 0解决
